plugins {
  id 'com.android.library'
  id 'expo-module-gradle-plugin'
}

group = 'com.nsfinance'
version = '1.0.0'

android {
  namespace 'com.nsfinance.microsoftauth'
  defaultConfig {
    versionCode 1
    versionName '1.0.0'
  }
}

dependencies {
  implementation 'com.microsoft.identity.client:msal:8.3.2'
}
