namespace NSFinance.Api.Modules.Transactions.DTOs;

public sealed record TransactionDto(
    Guid Id,
    Guid AccountId,
    string AccountName,
    string Description,
    decimal Amount,
    string Currency,
    Guid? CategoryId,
    string? CategoryName,
    int? TaxonomyDomainId,
    string? TaxonomyDomainName,
    int? TaxonomyCategoryId,
    string? TaxonomyCategoryName,
    int? TaxonomySubcategoryId,
    string? TaxonomySubcategoryName,
    string? TransferKind,
    Guid? LinkedTransferTransactionId,
    string? Reason,
    string? Notes,
    DateTime BookedAtUtc,
    DateTime CreatedUtc,
    DateTime? MetadataUpdatedUtc,
    string Direction);
