namespace NSFinance.Api.Modules.Users.DTOs;

public sealed record UserProfileDetailsDto(
    Guid Id,
    string PrimaryEmail,
    string FullName,
    string DisplayName,
    string? Handle,
    string? ProfileImageUrl,
    string? ProfileSubtitle,
    string Timezone,
    string Locale,
    string PreferredCurrency,
    string OnboardingStatus,
    bool BiometricUnlockEnabled,
    bool TwoFactorEnabled,
    string? PhoneNumber,
    DateTime? DateOfBirth,
    string? CountryRegion,
    IReadOnlyList<string> FinancialFocus,
    string? EmploymentStatus,
    string? IncomeStability,
    string? PrimaryFinancialConcern,
    bool EmailVerified,
    string PlanTier,
    DateTime CreatedUtc,
    DateTime? LastLoginUtc);
