namespace NSFinance.Api.Modules.Banking.DTOs;

public sealed record BankConnectionDto(
    Guid Id,
    string Provider,
    string? ProviderId,
    string ProviderEnvironment,
    string? ProviderDisplayName,
    string? ProviderIconUrl,
    string? ProviderLogoUrl,
    string? ProviderBrandBgColor,
    DateTime? BrandingLastSyncedAtUtc,
    string Status,
    DateTime CreatedUtc,
    DateTime UpdatedUtc,
    DateTime? LastSuccessfulSyncUtc,
    DateTime? LastSyncAttemptedUtc,
    string? LastErrorCode,
    string? GrantedScopesCsv = null,
    bool? SupportsInfo = null,
    bool? SupportsCards = null,
    bool? SupportsDirectDebits = null,
    bool? SupportsStandingOrders = null,
    string? ConnectedFullName = null,
    DateTime? IdentityFetchedUtc = null,
    string? SyncLifecyclePhase = null,
    string? SyncLifecycleReason = null,
    string? SyncEnrichmentStage = null,
    int? LinkedAccountCount = null,
    int? ImportedTransactionCount = null,
    bool? SyncStateReconciled = null,
    bool? SyncStateStaleProtectionApplied = null);
