namespace NSFinance.Api.Modules.Banking.DTOs;

public sealed record DeterministicCategorizationStatusCountDto(
    string Status,
    int Count);

public sealed record DeterministicDiagnosticsBreakdownDto(
    string Status,
    string? ReasonCode,
    string CandidateFamily,
    string Provider,
    Guid FinancialAccountId,
    string Direction,
    string AmountBucket,
    bool DuplicateClusterMember,
    bool HasCounterpartyAccounts,
    bool HasPlausibleCounterpartCandidates,
    bool DeferredOnCounterpartyExpectation,
    int Count);

public sealed record DeterministicTransactionDecisionDto(
    Guid TransactionId,
    Guid FinancialAccountId,
    decimal Amount,
    string Currency,
    DateTime BookedAtUtc,
    string NormalizedDescription,
    string Provider,
    string ClassificationStatus,
    bool Terminal,
    bool RetryEligible,
    int? ClassificationVersion,
    string? RuleKey,
    string? ReasonCode,
    string CandidateFamily,
    string Direction,
    string AmountBucket,
    bool DuplicateClusterMember,
    int DuplicateClusterSize,
    bool HasCounterpartyAccounts,
    int CandidateCounterpartCount,
    Guid? TopCandidateTransactionId,
    int? TopCandidateScore,
    bool HasSavingsSignals,
    bool HasTransferSignals,
    bool CooccurredWithNearbyMerchantSpend,
    bool HasPlausibleCounterpartCandidates,
    bool DeferredOnCounterpartyExpectation,
    Guid? LinkedTransactionId,
    string? RelationshipType,
    Guid? RelationshipGroupId,
    int? MatchScore,
    DateTime? EvaluatedUtc);

public sealed record DeterministicCategorizationDiagnosticsDto(
    Guid ConnectionId,
    int ClassificationVersion,
    int TotalTransactions,
    int TerminalTransactions,
    int NonTerminalTransactions,
    int ActionableRemainingTransactions,
    int DeferredMoreContextTransactions,
    int DeferredCounterpartyTransactions,
    bool QueueEligible,
    string QueueEligibilityReason,
    string ContinuationDecision,
    string ContinuationReason,
    IReadOnlyList<DeterministicCategorizationStatusCountDto> StatusCounts,
    IReadOnlyList<DeterministicDiagnosticsBreakdownDto> UnresolvedBreakdown,
    IReadOnlyList<DeterministicTransactionDecisionDto> SampleDecisions);
