namespace NSFinance.Api.Modules.Banking.DTOs;

public sealed record GlobalBankSyncConnectionResponse(
    Guid ConnectionId,
    string? ProviderDisplayName,
    string Status,
    string Outcome,
    int AccountsSynced,
    int BalancesSynced,
    int TransactionsImported,
    DateTime? SyncedAtUtc,
    bool DataChanged,
    DateTime? LastSyncAttemptedUtc,
    DateTime? LastSuccessfulSyncUtc,
    DateTime? ProviderBackoffUntilUtc,
    DateTime? LatestFetchedRowUtc,
    bool? HasFetchedRowNewerThanCheckpoint,
    string? FreshnessSummary,
    bool? HistoricalEnrichmentInProgress,
    bool? HistoricalEnrichmentCompleted,
    double? HistoricalEnrichmentProgressPercent,
    DateTime? HistoricalEnrichmentCheckpointUtc,
    string? ErrorCode,
    string? ErrorMessage);

public sealed record GlobalBankSyncResponse(
    string Trigger,
    string Outcome,
    DateTime RequestedAtUtc,
    DateTime? CompletedAtUtc,
    bool DueNow,
    int CooldownRemainingSeconds,
    DateTime? CooldownUntilUtc,
    int EligibleConnectionCount,
    int ChangedConnectionCount,
    int NoChangeConnectionCount,
    int FailedConnectionCount,
    int SkippedConnectionCount,
    DateTime? LastSuccessfulSyncUtc,
    DateTime? LastManualSyncRequestUtc,
    DateTime? NextEligibleManualSyncUtc,
    int ProviderBackoffConnectionCount,
    int NoNewerRowsConnectionCount,
    IReadOnlyList<GlobalBankSyncConnectionResponse> Connections);
