namespace NSFinance.Api.Modules.AI.Services;

public sealed class RealWorldDomainCapabilityCatalog : IRealWorldDomainCapabilityCatalog
{
    private static readonly IReadOnlyList<RealWorldDomainCapability> DomainCapabilities =
    [
        Capability(
            domain: RealWorldDiscoveryDomain.Cafe,
            family: RealWorldDomainFamily.FoodDrink,
            canonicalConcepts: ["cafe", "coffee_shop", "coffee"],
            suitableEvening: true,
            suitableFamily: true,
            suitableChill: true,
            suitableSocial: true,
            suitableSolo: true,
            suitableQuickErrand: true,
            suitablePlannedOuting: true,
            suitableBudgetFriendly: true,
            suitableIndoor: true),
        Capability(
            domain: RealWorldDiscoveryDomain.Restaurant,
            family: RealWorldDomainFamily.FoodDrink,
            canonicalConcepts: ["restaurant", "dining"],
            suitableEvening: true,
            suitableFamily: true,
            suitableSocial: true,
            suitableSolo: true,
            suitablePlannedOuting: true,
            suitableBudgetFriendly: true,
            suitableIndoor: true),
        Capability(
            domain: RealWorldDiscoveryDomain.Takeaway,
            family: RealWorldDomainFamily.FoodDrink,
            canonicalConcepts: ["takeaway", "takeout", "delivery"],
            suitableEvening: true,
            suitableFamily: true,
            suitableQuickErrand: true,
            suitableBudgetFriendly: true,
            suitableIndoor: true),
        Capability(
            domain: RealWorldDiscoveryDomain.PubBar,
            family: RealWorldDomainFamily.FoodDrink,
            canonicalConcepts: ["pub_bar", "bar", "pub"],
            suitableEvening: true,
            suitableSocial: true,
            suitableNightlife: true,
            suitablePlannedOuting: true,
            suitableIndoor: true),
        Capability(
            domain: RealWorldDiscoveryDomain.MovieTheater,
            family: RealWorldDomainFamily.Entertainment,
            canonicalConcepts: ["movie_theater", "cinema", "film"],
            suitableEvening: true,
            suitableFamily: true,
            suitableChill: true,
            suitableSocial: true,
            suitableSolo: true,
            suitablePlannedOuting: true,
            suitableIndoor: true),
        Capability(
            domain: RealWorldDiscoveryDomain.ParkWalk,
            family: RealWorldDomainFamily.Outdoor,
            canonicalConcepts: ["park_walk", "walk", "park"],
            suitableEvening: true,
            suitableFamily: true,
            suitableChill: true,
            suitableActive: true,
            suitableSocial: true,
            suitableSolo: true,
            suitablePlannedOuting: true,
            suitableBudgetFriendly: true,
            suitableOutdoor: true),
        Capability(
            domain: RealWorldDiscoveryDomain.Playground,
            family: RealWorldDomainFamily.Outdoor,
            canonicalConcepts: ["playground"],
            suitableFamily: true,
            suitableActive: true,
            suitableSocial: true,
            suitablePlannedOuting: true,
            suitableBudgetFriendly: true,
            suitableOutdoor: true),
        Capability(
            domain: RealWorldDiscoveryDomain.Pharmacy,
            family: RealWorldDomainFamily.EssentialService,
            canonicalConcepts: ["pharmacy", "chemist"],
            supportsServiceDiscovery: true,
            supportsEssentialService: true,
            suitableQuickErrand: true,
            suitableIndoor: true),
        Capability(
            domain: RealWorldDiscoveryDomain.PetrolStation,
            family: RealWorldDomainFamily.EssentialService,
            canonicalConcepts: ["petrol_station", "gas_station", "fuel"],
            supportsServiceDiscovery: true,
            supportsEssentialService: true,
            suitableQuickErrand: true,
            suitableIndoor: false,
            suitableOutdoor: true),
        Capability(
            domain: RealWorldDiscoveryDomain.Gym,
            family: RealWorldDomainFamily.Wellness,
            canonicalConcepts: ["gym", "fitness"],
            supportsServiceDiscovery: true,
            suitableEvening: true,
            suitableActive: true,
            suitableSocial: true,
            suitableSolo: true,
            suitablePlannedOuting: true,
            suitableIndoor: true),
        Capability(
            domain: RealWorldDiscoveryDomain.ElectronicsRetail,
            family: RealWorldDomainFamily.RetailCommerce,
            canonicalConcepts: ["electronics_retail", "electronics_shop"],
            supportsCommerceDiscovery: true,
            suitableQuickErrand: true,
            suitableIndoor: true),
        Capability(
            domain: RealWorldDiscoveryDomain.ConvenienceStore,
            family: RealWorldDomainFamily.RetailCommerce,
            canonicalConcepts: ["convenience_store"],
            supportsCommerceDiscovery: true,
            suitableQuickErrand: true,
            suitableBudgetFriendly: true,
            suitableIndoor: true),
        Capability(
            domain: RealWorldDiscoveryDomain.Grocery,
            family: RealWorldDomainFamily.RetailCommerce,
            canonicalConcepts: ["grocery", "supermarket"],
            supportsCommerceDiscovery: true,
            supportsEssentialService: true,
            suitableQuickErrand: true,
            suitableBudgetFriendly: true,
            suitableIndoor: true),
        Capability(
            domain: RealWorldDiscoveryDomain.ShoppingGeneral,
            family: RealWorldDomainFamily.RetailCommerce,
            canonicalConcepts: ["shopping_general", "shopping"],
            supportsCommerceDiscovery: true,
            suitableEvening: true,
            suitableSocial: true,
            suitableSolo: true,
            suitablePlannedOuting: true,
            suitableIndoor: true,
            isGeneric: true),
        Capability(
            domain: RealWorldDiscoveryDomain.OutdoorActivity,
            family: RealWorldDomainFamily.Outdoor,
            canonicalConcepts: ["outdoor_activity", "outdoor"],
            suitableEvening: true,
            suitableFamily: true,
            suitableChill: true,
            suitableActive: true,
            suitableSocial: true,
            suitableSolo: true,
            suitablePlannedOuting: true,
            suitableBudgetFriendly: true,
            suitableOutdoor: true,
            isGeneric: true),
        Capability(
            domain: RealWorldDiscoveryDomain.EntertainmentGeneral,
            family: RealWorldDomainFamily.Entertainment,
            canonicalConcepts: ["entertainment_general", "entertainment"],
            suitableEvening: true,
            suitableFamily: true,
            suitableSocial: true,
            suitableSolo: true,
            suitablePlannedOuting: true,
            suitableIndoor: true,
            suitableOutdoor: true,
            isGeneric: true),
        Capability(
            domain: RealWorldDiscoveryDomain.NightlifeGeneral,
            family: RealWorldDomainFamily.Entertainment,
            canonicalConcepts: ["nightlife_general", "nightlife"],
            suitableEvening: true,
            suitableSocial: true,
            suitableNightlife: true,
            suitablePlannedOuting: true,
            suitableIndoor: true,
            isGeneric: true),
        Capability(
            domain: RealWorldDiscoveryDomain.FoodDrinkGeneral,
            family: RealWorldDomainFamily.FoodDrink,
            canonicalConcepts: ["food_drink_general", "food_drink"],
            suitableEvening: true,
            suitableFamily: true,
            suitableSocial: true,
            suitableSolo: true,
            suitableQuickErrand: true,
            suitablePlannedOuting: true,
            suitableBudgetFriendly: true,
            suitableIndoor: true,
            isGeneric: true),
        Capability(
            domain: RealWorldDiscoveryDomain.ServiceGeneral,
            family: RealWorldDomainFamily.EssentialService,
            canonicalConcepts: ["service_general", "service"],
            supportsServiceDiscovery: true,
            supportsEssentialService: true,
            suitableQuickErrand: true,
            suitableIndoor: true,
            isGeneric: true),
        Capability(
            domain: RealWorldDiscoveryDomain.CommerceGeneral,
            family: RealWorldDomainFamily.RetailCommerce,
            canonicalConcepts: ["commerce_general", "commerce", "shop"],
            supportsCommerceDiscovery: true,
            suitableQuickErrand: true,
            suitableIndoor: true,
            isGeneric: true),
        Capability(
            domain: RealWorldDiscoveryDomain.ExploratoryEveningActivity,
            family: RealWorldDomainFamily.Meta,
            canonicalConcepts: ["exploratory_evening_activity"],
            supportsFocusedPlaceSearch: false,
            supportsFocusedThemeSearch: false,
            supportsExploratorySearch: false,
            suitableEvening: true,
            suitablePlannedOuting: true,
            nearMeAppropriate: false,
            explicitLocalityAppropriate: false,
            exploratoryFallbackEligible: false,
            isGeneric: true),
        Capability(
            domain: RealWorldDiscoveryDomain.ExploratoryFamilyActivity,
            family: RealWorldDomainFamily.Meta,
            canonicalConcepts: ["exploratory_family_activity"],
            supportsFocusedPlaceSearch: false,
            supportsFocusedThemeSearch: false,
            supportsExploratorySearch: false,
            suitableFamily: true,
            suitablePlannedOuting: true,
            nearMeAppropriate: false,
            explicitLocalityAppropriate: false,
            exploratoryFallbackEligible: false,
            isGeneric: true)
    ];

    private static readonly IReadOnlyDictionary<RealWorldDiscoveryDomain, RealWorldDomainCapability> CapabilitiesByDomain =
        DomainCapabilities.ToDictionary(static capability => capability.Domain);

    public IReadOnlyList<RealWorldDomainCapability> GetDomains()
    {
        return DomainCapabilities;
    }

    public bool TryGetDomain(RealWorldDiscoveryDomain domain, out RealWorldDomainCapability capability)
    {
        return CapabilitiesByDomain.TryGetValue(domain, out capability!);
    }

    private static RealWorldDomainCapability Capability(
        RealWorldDiscoveryDomain domain,
        RealWorldDomainFamily family,
        IReadOnlyList<string> canonicalConcepts,
        bool supportsFocusedPlaceSearch = true,
        bool supportsFocusedThemeSearch = true,
        bool supportsExploratorySearch = true,
        bool supportsCommerceDiscovery = false,
        bool supportsServiceDiscovery = false,
        bool supportsEssentialService = false,
        bool suitableEvening = false,
        bool suitableFamily = false,
        bool suitableChill = false,
        bool suitableActive = false,
        bool suitableSocial = false,
        bool suitableSolo = false,
        bool suitableQuickErrand = false,
        bool suitablePlannedOuting = false,
        bool suitableBudgetFriendly = false,
        bool suitableNightlife = false,
        bool suitableIndoor = false,
        bool suitableOutdoor = false,
        bool nearMeAppropriate = true,
        bool explicitLocalityAppropriate = true,
        bool exploratoryFallbackEligible = true,
        bool isGeneric = false)
    {
        return new RealWorldDomainCapability(
            Domain: domain,
            Family: family,
            CanonicalConcepts: canonicalConcepts,
            SupportsFocusedPlaceSearch: supportsFocusedPlaceSearch,
            SupportsFocusedThemeSearch: supportsFocusedThemeSearch,
            SupportsExploratorySearch: supportsExploratorySearch,
            SupportsCommerceDiscovery: supportsCommerceDiscovery,
            SupportsServiceDiscovery: supportsServiceDiscovery,
            SupportsEssentialService: supportsEssentialService,
            SuitableEvening: suitableEvening,
            SuitableFamily: suitableFamily,
            SuitableChill: suitableChill,
            SuitableActive: suitableActive,
            SuitableSocial: suitableSocial,
            SuitableSolo: suitableSolo,
            SuitableQuickErrand: suitableQuickErrand,
            SuitablePlannedOuting: suitablePlannedOuting,
            SuitableBudgetFriendly: suitableBudgetFriendly,
            SuitableNightlife: suitableNightlife,
            SuitableIndoor: suitableIndoor,
            SuitableOutdoor: suitableOutdoor,
            NearMeAppropriate: nearMeAppropriate,
            ExplicitLocalityAppropriate: explicitLocalityAppropriate,
            ExploratoryFallbackEligible: exploratoryFallbackEligible,
            IsGeneric: isGeneric);
    }
}
