namespace NSFinance.Shared.Taxonomy;

// Full-coverage characteristics: Religious Or Spiritual Giving (300), Legal &
// Professional Fees (310), Refunds, Reimbursements & Adjustments (900), and
// Income (910) - categories and subcategories.
public static partial class CategoryCharacteristicsCatalog
{
    private static readonly IReadOnlyList<CategoryCharacteristicsDefinition> GivingLegalIncomeDefinitions =
    [
        // -- 30010 Regular Giving --
        new(30010, null, "Steady giving to a faith community.",
            ["Weekly parish contribution"],
            ["Payment is regular religious giving", "Direction is outflow"],
            ["Secular charity belongs to Charitable Giving"],
            ["PARISH", "DIOCESE"], CharacteristicsDirection.Outflow, CharacteristicsAnalyticsTreatment.Expense, 0.7),
        new(null, 300101, "Tithes.",
            ["Monthly tithe"],
            ["Payment is a tithe", "Direction is outflow"],
            [],
            ["TITHE"], CharacteristicsDirection.Outflow, CharacteristicsAnalyticsTreatment.Expense, 0.65),
        new(null, 300102, "Weekly and monthly offerings.",
            ["Collection envelope standing order"],
            ["Payment is a recurring offering", "Direction is outflow"],
            [],
            [], CharacteristicsDirection.Outflow, CharacteristicsAnalyticsTreatment.Expense, 0.5),
        new(null, 300103, "Contributions to a temple, mosque, or church.",
            ["Contribution to the congregation"],
            ["Payment supports a place of worship", "Direction is outflow"],
            [],
            ["MOSQUE"], CharacteristicsDirection.Outflow, CharacteristicsAnalyticsTreatment.Expense, 0.55),
        new(null, 300104, "Faith community support.",
            ["Support for the faith community"],
            ["Payment supports the faith community", "Direction is outflow"],
            [],
            [], CharacteristicsDirection.Outflow, CharacteristicsAnalyticsTreatment.Expense, 0.5),

        // -- 30020 Ceremonies & Events --
        new(30020, null, "Faith ceremonies and observances.",
            ["Ceremony offering"],
            ["Payment funds a religious ceremony", "Direction is outflow"],
            [],
            [], CharacteristicsDirection.Outflow, CharacteristicsAnalyticsTreatment.Expense, 0.5),
        new(null, 300201, "Wedding ceremony costs.",
            ["Church wedding offering"],
            ["Payment funds a religious wedding", "Direction is outflow"],
            ["Venue and reception costs belong to Entertainment"],
            [], CharacteristicsDirection.Outflow, CharacteristicsAnalyticsTreatment.Expense, 0.5),
        new(null, 300202, "Baptisms and christenings.",
            ["Christening offering"],
            ["Payment funds a baptism", "Direction is outflow"],
            [],
            [], CharacteristicsDirection.Outflow, CharacteristicsAnalyticsTreatment.Expense, 0.5),
        new(null, 300203, "Funerals.",
            ["Funeral offering or undertaker payment"],
            ["Payment funds a funeral", "Direction is outflow"],
            [],
            ["FUNERAL", "UNDERTAKER"], CharacteristicsDirection.Outflow, CharacteristicsAnalyticsTreatment.Expense, 0.65),
        new(null, 300204, "Festivals and holy days.",
            ["Holy day contribution"],
            ["Payment marks a festival or holy day", "Direction is outflow"],
            [],
            [], CharacteristicsDirection.Outflow, CharacteristicsAnalyticsTreatment.Expense, 0.5),
        new(null, 300205, "Pilgrimage costs.",
            ["Pilgrimage deposit"],
            ["Payment funds a pilgrimage", "Direction is outflow"],
            [],
            ["PILGRIMAGE", "LOURDES"], CharacteristicsDirection.Outflow, CharacteristicsAnalyticsTreatment.Expense, 0.6),

        // -- 30030 Educational & Community Support --
        new(30030, null, "Faith-based education and community programmes.",
            ["Faith programme payment"],
            ["Payment supports faith education or community work", "Direction is outflow"],
            [],
            [], CharacteristicsDirection.Outflow, CharacteristicsAnalyticsTreatment.Expense, 0.5),
        new(null, 300301, "Religious education.",
            ["Faith formation class"],
            ["Payment is religious education", "Direction is outflow"],
            [],
            [], CharacteristicsDirection.Outflow, CharacteristicsAnalyticsTreatment.Expense, 0.5),
        new(null, 300302, "Retreats.",
            ["Weekend retreat"],
            ["Payment funds a spiritual retreat", "Direction is outflow"],
            [],
            ["RETREAT"], CharacteristicsDirection.Outflow, CharacteristicsAnalyticsTreatment.Expense, 0.55),
        new(null, 300303, "Youth programmes.",
            ["Faith youth group support"],
            ["Payment supports a faith youth programme", "Direction is outflow"],
            [],
            [], CharacteristicsDirection.Outflow, CharacteristicsAnalyticsTreatment.Expense, 0.5),
        new(null, 300304, "Mission support.",
            ["Supporting missionary work"],
            ["Payment supports missions", "Direction is outflow"],
            [],
            ["MISSION"], CharacteristicsDirection.Outflow, CharacteristicsAnalyticsTreatment.Expense, 0.55),
        new(null, 300305, "Spiritual counseling.",
            ["Spiritual direction session"],
            ["Payment is spiritual counseling", "Direction is outflow"],
            ["Clinical therapy belongs to Healthcare's mental health"],
            [], CharacteristicsDirection.Outflow, CharacteristicsAnalyticsTreatment.Expense, 0.5),

        // -- 30040 Other Spiritual Spending (real subs, category is the Other bucket) --
        new(30040, null, "Spiritual spending that fits nowhere else; a human choice, never an AI guess.",
            ["Genuinely unclassifiable spiritual expense"],
            ["Only deterministic rules or the user may assign this catch-all"],
            [],
            [], CharacteristicsDirection.Outflow, CharacteristicsAnalyticsTreatment.Expense, null),
        new(null, 300401, "Spiritual books and materials.",
            ["Devotional books"],
            ["Purchase is spiritual books or materials", "Direction is outflow"],
            ["Bookshop brand signals belong to Entertainment's books"],
            [], CharacteristicsDirection.Outflow, CharacteristicsAnalyticsTreatment.Expense, 0.5),
        new(null, 300402, "Ritual supplies.",
            ["Candles and ritual items"],
            ["Purchase is ritual supplies", "Direction is outflow"],
            [],
            [], CharacteristicsDirection.Outflow, CharacteristicsAnalyticsTreatment.Expense, 0.5),
        new(null, 300403, "Donations to spiritual organizations.",
            ["Donation to a spiritual body"],
            ["Payment donates to a spiritual organization", "Direction is outflow"],
            [],
            [], CharacteristicsDirection.Outflow, CharacteristicsAnalyticsTreatment.Expense, 0.5),

        // -- 31010 Legal Services --
        new(31010, null, "Lawyers and the machinery of law.",
            ["Solicitor invoice"],
            ["Charge is personal legal services", "Direction is outflow"],
            ["Business legal work belongs to Business Expenses"],
            ["SOLICITOR", "LAW FIRM"], CharacteristicsDirection.Outflow, CharacteristicsAnalyticsTreatment.Expense, 0.7),
        new(null, 310101, "Solicitor and attorney fees.",
            ["Conveyancing fees"],
            ["Charge is solicitor fees", "Direction is outflow"],
            [],
            [], CharacteristicsDirection.Outflow, CharacteristicsAnalyticsTreatment.Expense, 0.5),
        new(null, 310102, "Court fees.",
            ["Court filing fee"],
            ["Charge is court fees", "Direction is outflow"],
            [],
            ["COURTS SERVICE"], CharacteristicsDirection.Outflow, CharacteristicsAnalyticsTreatment.Expense, 0.65),
        new(null, 310103, "Notary fees.",
            ["Document notarization"],
            ["Charge is notary services", "Direction is outflow"],
            [],
            ["NOTARY"], CharacteristicsDirection.Outflow, CharacteristicsAnalyticsTreatment.Expense, 0.65),
        new(null, 310104, "Document filing fees.",
            ["Official document filing"],
            ["Charge files legal documents", "Direction is outflow"],
            [],
            [], CharacteristicsDirection.Outflow, CharacteristicsAnalyticsTreatment.Expense, 0.5),
        new(null, 310105, "Mediation.",
            ["Mediation session"],
            ["Charge is mediation services", "Direction is outflow"],
            [],
            ["MEDIATION"], CharacteristicsDirection.Outflow, CharacteristicsAnalyticsTreatment.Expense, 0.6),
        new(null, 310106, "Immigration services.",
            ["Visa application support"],
            ["Charge is immigration services", "Direction is outflow"],
            [],
            ["IMMIGRATION"], CharacteristicsDirection.Outflow, CharacteristicsAnalyticsTreatment.Expense, 0.6),
        new(null, 310107, "Estate and probate services.",
            ["Probate administration"],
            ["Charge is estate or probate work", "Direction is outflow"],
            [],
            ["PROBATE"], CharacteristicsDirection.Outflow, CharacteristicsAnalyticsTreatment.Expense, 0.65),

        // -- 31020 Financial & Advisory --
        new(31020, null, "Paid financial guidance.",
            ["Advisor fee"],
            ["Charge is financial advice", "Direction is outflow"],
            ["Fund and platform charges belong to Savings & Investments' costs"],
            [], CharacteristicsDirection.Outflow, CharacteristicsAnalyticsTreatment.Expense, 0.5),
        new(null, 310201, "Financial planners.",
            ["Financial plan engagement"],
            ["Charge is financial planning", "Direction is outflow"],
            [],
            ["FINANCIAL PLANNING"], CharacteristicsDirection.Outflow, CharacteristicsAnalyticsTreatment.Expense, 0.6),
        new(null, 310202, "Investment advisors.",
            ["Advisory fee"],
            ["Charge is investment advice", "Direction is outflow"],
            [],
            [], CharacteristicsDirection.Outflow, CharacteristicsAnalyticsTreatment.Expense, 0.5),
        new(null, 310203, "Tax advisors.",
            ["Personal tax advice"],
            ["Charge is tax advice", "Direction is outflow"],
            ["Tax return preparation belongs to Taxes' tax services"],
            [], CharacteristicsDirection.Outflow, CharacteristicsAnalyticsTreatment.Expense, 0.5),
        new(null, 310204, "Insurance brokers.",
            ["Broker arrangement fee"],
            ["Charge is an insurance broker fee", "Direction is outflow"],
            ["Insurer premiums resolve deterministically to Insurance"],
            [], CharacteristicsDirection.Outflow, CharacteristicsAnalyticsTreatment.Expense, 0.5),
        new(null, 310205, "Mortgage brokers.",
            ["Mortgage arrangement fee"],
            ["Charge is a mortgage broker fee", "Direction is outflow"],
            [],
            ["MORTGAGE BROKER"], CharacteristicsDirection.Outflow, CharacteristicsAnalyticsTreatment.Expense, 0.6),

        // -- 31030 Identity / Compliance / Documents --
        new(31030, null, "Official documents and identity paperwork.",
            ["Passport renewal"],
            ["Charge is identity or document services", "Direction is outflow"],
            [],
            [], CharacteristicsDirection.Outflow, CharacteristicsAnalyticsTreatment.Expense, 0.55),
        new(null, 310301, "Passport fees tracked under legal and documents.",
            ["Passport renewal fee"],
            ["Charge is passport services", "Direction is outflow"],
            ["Passport signals resolve deterministically to Travel's passports"],
            [], CharacteristicsDirection.Outflow, CharacteristicsAnalyticsTreatment.Expense, 0.5),
        new(null, 310302, "ID renewal.",
            ["National ID or licence renewal"],
            ["Charge renews identification", "Direction is outflow"],
            ["Driving licence fees belong to Transportation"],
            [], CharacteristicsDirection.Outflow, CharacteristicsAnalyticsTreatment.Expense, 0.5),
        new(null, 310303, "Background checks.",
            ["Vetting or background check"],
            ["Charge is a background check", "Direction is outflow"],
            [],
            ["BACKGROUND CHECK"], CharacteristicsDirection.Outflow, CharacteristicsAnalyticsTreatment.Expense, 0.6),
        new(null, 310304, "Certification and authentication fees.",
            ["Apostille on a document"],
            ["Charge certifies or authenticates documents", "Direction is outflow"],
            [],
            ["APOSTILLE"], CharacteristicsDirection.Outflow, CharacteristicsAnalyticsTreatment.Expense, 0.6),

        // -- 31040 Other Professional Fees (real + category as Other bucket) --
        new(31040, null, "Professional fees that fit nowhere else; a human choice, never an AI guess.",
            ["Genuinely unclassifiable professional fee"],
            ["Only deterministic rules or the user may assign this catch-all"],
            [],
            [], CharacteristicsDirection.Outflow, CharacteristicsAnalyticsTreatment.Expense, null),
        new(null, 310401, "Translation services.",
            ["Certified translation"],
            ["Charge is translation services", "Direction is outflow"],
            [],
            ["TRANSLATION"], CharacteristicsDirection.Outflow, CharacteristicsAnalyticsTreatment.Expense, 0.6),
        new(null, 310402, "Resume and career coaching.",
            ["CV review session"],
            ["Charge is career coaching", "Direction is outflow"],
            [],
            ["CAREER COACH"], CharacteristicsDirection.Outflow, CharacteristicsAnalyticsTreatment.Expense, 0.6),
        new(null, 310403, "Licensing help.",
            ["Help obtaining a licence"],
            ["Charge assists licensing", "Direction is outflow"],
            [],
            [], CharacteristicsDirection.Outflow, CharacteristicsAnalyticsTreatment.Expense, 0.5),
        new(null, 310404, "Expert consultations.",
            ["Specialist consultation"],
            ["Charge is an expert consultation", "Direction is outflow"],
            [],
            [], CharacteristicsDirection.Outflow, CharacteristicsAnalyticsTreatment.Expense, 0.5),

        // -- 31050 Banking & Account Fees --
        new(31050, null, "What the bank charges you for banking.",
            ["Quarterly account fees"],
            ["Charge is a bank or account fee", "Direction is outflow"],
            ["Loan interest belongs to Debt & Loans", "Business account fees belong to Business Expenses"],
            [], CharacteristicsDirection.Outflow, CharacteristicsAnalyticsTreatment.Expense, 0.6),
        new(null, 310501, "Account maintenance fees.",
            ["Quarterly maintenance charge"],
            ["Charge is account maintenance", "Direction is outflow"],
            [],
            ["FEE-QTR", "MAINTENANCE FEE", "QUARTERLY FEE", "ACCOUNT FEE"], CharacteristicsDirection.Outflow, CharacteristicsAnalyticsTreatment.Expense, 0.8),
        new(null, 310502, "Payment and transfer fees.",
            ["Fee on a transfer"],
            ["Charge is a payment or transfer fee", "Direction is outflow"],
            [],
            ["TRANSFER FEE"], CharacteristicsDirection.Outflow, CharacteristicsAnalyticsTreatment.Expense, 0.65),
        new(null, 310503, "ATM and currency fees.",
            ["Foreign exchange fee"],
            ["Charge is an ATM or currency fee", "Direction is outflow"],
            [],
            ["ATM FEE", "FX FEE", "CURRENCY CONVERSION"], CharacteristicsDirection.Outflow, CharacteristicsAnalyticsTreatment.Expense, 0.7),
        new(null, 310504, "Overdraft and unpaid item fees.",
            ["Unpaid direct debit fee"],
            ["Charge penalizes an overdraft or unpaid item", "Direction is outflow"],
            [],
            ["OVERDRAFT", "UNPAID FEE"], CharacteristicsDirection.Outflow, CharacteristicsAnalyticsTreatment.Expense, 0.7),
        new(null, 310505, "Card fees.",
            ["Annual card charge or card levy"],
            ["Charge is a card fee", "Direction is outflow"],
            [],
            ["CARD FEE", "GOVT STAMP DUTY"], CharacteristicsDirection.Outflow, CharacteristicsAnalyticsTreatment.Expense, 0.7),

        // -- 90010 Refunds --
        new(90010, null, "Money coming back from a purchase.",
            ["Refund from a merchant"],
            ["Inflow returns money you paid", "Direction is inflow"],
            ["Transfers between your own accounts are never refunds"],
            ["REFUND"], CharacteristicsDirection.Inflow, CharacteristicsAnalyticsTreatment.Income, 0.7),
        new(null, 900101, "Merchant refunds.",
            ["Order refunded in full"],
            ["Inflow is a merchant refund", "Direction is inflow"],
            [],
            [], CharacteristicsDirection.Inflow, CharacteristicsAnalyticsTreatment.Income, 0.5),
        new(null, 900102, "Partial refunds.",
            ["Part of an order refunded"],
            ["Inflow is a partial refund", "Direction is inflow"],
            [],
            [], CharacteristicsDirection.Inflow, CharacteristicsAnalyticsTreatment.Income, 0.5),
        new(null, 900103, "Return refunds.",
            ["Refund after returning goods"],
            ["Inflow refunds a return", "Direction is inflow"],
            [],
            [], CharacteristicsDirection.Inflow, CharacteristicsAnalyticsTreatment.Income, 0.5),
        new(null, 900104, "Deposit returns.",
            ["Security deposit returned"],
            ["Inflow returns a deposit", "Direction is inflow"],
            [],
            [], CharacteristicsDirection.Inflow, CharacteristicsAnalyticsTreatment.Income, 0.5),
        new(null, 900105, "Charge reversals.",
            ["Disputed charge reversed"],
            ["Inflow reverses a charge", "Direction is inflow"],
            [],
            ["REVERSAL"], CharacteristicsDirection.Inflow, CharacteristicsAnalyticsTreatment.Income, 0.6),

        // -- 90020 Reimbursements --
        new(90020, null, "Someone paying you back.",
            ["Expenses paid back"],
            ["Inflow repays money you spent", "Direction is inflow"],
            ["Transfers between your own accounts are never reimbursements"],
            [], CharacteristicsDirection.Inflow, CharacteristicsAnalyticsTreatment.Income, 0.5),
        new(null, 900201, "Employer reimbursements.",
            ["Work expenses paid back"],
            ["Inflow reimburses work expenses", "Direction is inflow"],
            ["Payroll salary belongs to Income"],
            [], CharacteristicsDirection.Inflow, CharacteristicsAnalyticsTreatment.Income, 0.5),
        new(null, 900202, "Shared expense repayments.",
            ["Friend paying their share of a bill"],
            ["Inflow settles a shared expense", "Direction is inflow"],
            [],
            [], CharacteristicsDirection.Inflow, CharacteristicsAnalyticsTreatment.Income, 0.5),
        new(null, 900203, "Insurance reimbursements.",
            ["Claim paid out"],
            ["Inflow settles an insurance claim", "Direction is inflow"],
            [],
            [], CharacteristicsDirection.Inflow, CharacteristicsAnalyticsTreatment.Income, 0.5),
        new(null, 900204, "Family reimbursements.",
            ["Family paying you back"],
            ["Inflow is family repaying you", "Direction is inflow"],
            [],
            [], CharacteristicsDirection.Inflow, CharacteristicsAnalyticsTreatment.Income, 0.5),
        new(null, 900205, "Benefit and grant reimbursements.",
            ["Scheme refunding a cost"],
            ["Inflow reimburses via a benefit or grant", "Direction is inflow"],
            [],
            [], CharacteristicsDirection.Inflow, CharacteristicsAnalyticsTreatment.Income, 0.5),

        // -- 90030 Credits & Adjustments --
        new(90030, null, "Credits and corrections landing in the account.",
            ["Account credit"],
            ["Inflow is a credit or adjustment", "Direction is inflow"],
            [],
            [], CharacteristicsDirection.Inflow, CharacteristicsAnalyticsTreatment.Income, 0.5),
        new(null, 900301, "Bill credits.",
            ["Provider credits your bill"],
            ["Inflow credits a billed service", "Direction is inflow"],
            [],
            [], CharacteristicsDirection.Inflow, CharacteristicsAnalyticsTreatment.Income, 0.5),
        new(null, 900302, "Promotional credits.",
            ["Signup bonus credit"],
            ["Inflow is a promotional credit", "Direction is inflow"],
            [],
            [], CharacteristicsDirection.Inflow, CharacteristicsAnalyticsTreatment.Income, 0.5),
        new(null, 900303, "Cashback credits.",
            ["Card cashback landing"],
            ["Inflow is cashback", "Direction is inflow"],
            [],
            ["CASHBACK"], CharacteristicsDirection.Inflow, CharacteristicsAnalyticsTreatment.Income, 0.65),
        new(null, 900304, "Manual balance adjustments.",
            ["Correction entry"],
            ["Only deterministic rules or the user may assign this adjustment node"],
            [],
            [], CharacteristicsDirection.Inflow, CharacteristicsAnalyticsTreatment.Income, null),

        // -- 91010 Employment Income --
        new(91010, null, "Money earned from employment.",
            ["Payroll credit"],
            ["Inflow is employment earnings", "Direction is inflow"],
            ["Payroll signals resolve deterministically to Salary"],
            [], CharacteristicsDirection.Inflow, CharacteristicsAnalyticsTreatment.Income, 0.5),
        new(null, 910102, "Bonuses.",
            ["Annual bonus payment"],
            ["Inflow is an employment bonus", "Direction is inflow"],
            [],
            [], CharacteristicsDirection.Inflow, CharacteristicsAnalyticsTreatment.Income, 0.5),
        new(null, 910103, "Overtime.",
            ["Overtime in a separate payment"],
            ["Inflow is overtime pay", "Direction is inflow"],
            [],
            [], CharacteristicsDirection.Inflow, CharacteristicsAnalyticsTreatment.Income, 0.5),
        new(null, 910104, "Commission.",
            ["Sales commission payout"],
            ["Inflow is commission", "Direction is inflow"],
            [],
            [], CharacteristicsDirection.Inflow, CharacteristicsAnalyticsTreatment.Income, 0.5),
        new(null, 910105, "Employer allowances.",
            ["Remote working allowance"],
            ["Inflow is an employer allowance", "Direction is inflow"],
            [],
            [], CharacteristicsDirection.Inflow, CharacteristicsAnalyticsTreatment.Income, 0.5),

        // -- 91020 Self-Employment & Business Income --
        new(91020, null, "Money earned working for yourself.",
            ["Client invoice paid"],
            ["Inflow is self-employment earnings", "Direction is inflow"],
            [],
            [], CharacteristicsDirection.Inflow, CharacteristicsAnalyticsTreatment.Income, 0.5),
        new(null, 910201, "Freelance income.",
            ["Freelance platform payout"],
            ["Inflow is freelance earnings", "Direction is inflow"],
            [],
            ["UPWORK", "FIVERR"], CharacteristicsDirection.Inflow, CharacteristicsAnalyticsTreatment.Income, 0.7),
        new(null, 910202, "Business revenue.",
            ["Sales revenue landing"],
            ["Inflow is business revenue", "Direction is inflow"],
            [],
            ["STRIPE PAYOUT"], CharacteristicsDirection.Inflow, CharacteristicsAnalyticsTreatment.Income, 0.6),
        new(null, 910203, "Contract work payments.",
            ["Contract milestone payment"],
            ["Inflow pays contract work", "Direction is inflow"],
            [],
            [], CharacteristicsDirection.Inflow, CharacteristicsAnalyticsTreatment.Income, 0.5),
        new(null, 910204, "Client payments.",
            ["Client settling an invoice"],
            ["Inflow is a client payment", "Direction is inflow"],
            [],
            [], CharacteristicsDirection.Inflow, CharacteristicsAnalyticsTreatment.Income, 0.5),

        // -- 91030 Investment & Finance Income --
        new(91030, null, "Money your money earned.",
            ["Investment income"],
            ["Inflow is investment earnings", "Direction is inflow"],
            ["Withdrawing your own invested capital is a transfer, not income"],
            [], CharacteristicsDirection.Inflow, CharacteristicsAnalyticsTreatment.Income, 0.5),
        new(null, 910301, "Interest earned.",
            ["Deposit interest credited"],
            ["Inflow is interest earned", "Direction is inflow"],
            ["Interest you pay on debt belongs to Debt & Loans"],
            ["INTEREST"], CharacteristicsDirection.Inflow, CharacteristicsAnalyticsTreatment.Income, 0.7),
        new(null, 910302, "Dividends.",
            ["Dividend credited"],
            ["Inflow is a dividend", "Direction is inflow"],
            [],
            ["DIVIDEND"], CharacteristicsDirection.Inflow, CharacteristicsAnalyticsTreatment.Income, 0.7),
        new(null, 910303, "Capital gain distributions.",
            ["Fund distribution"],
            ["Inflow distributes capital gains", "Direction is inflow"],
            [],
            [], CharacteristicsDirection.Inflow, CharacteristicsAnalyticsTreatment.Income, 0.5),
        new(null, 910304, "Investment payouts.",
            ["Maturity payout"],
            ["Inflow is an investment payout", "Direction is inflow"],
            ["Selling and withdrawing your own holdings is a transfer"],
            [], CharacteristicsDirection.Inflow, CharacteristicsAnalyticsTreatment.Income, 0.5),

        // -- 91040 Government & Benefit Income --
        new(91040, null, "Money from the state.",
            ["State payment landing"],
            ["Inflow is a government payment", "Direction is inflow"],
            [],
            [], CharacteristicsDirection.Inflow, CharacteristicsAnalyticsTreatment.Income, 0.5),
        new(null, 910401, "Tax refunds.",
            ["Revenue refund landing"],
            ["Inflow refunds overpaid tax", "Direction is inflow"],
            [],
            [], CharacteristicsDirection.Inflow, CharacteristicsAnalyticsTreatment.Income, 0.5),
        new(null, 910402, "Social benefits.",
            ["Weekly social welfare payment"],
            ["Inflow is a social benefit", "Direction is inflow"],
            [],
            ["SOCIAL WELFARE"], CharacteristicsDirection.Inflow, CharacteristicsAnalyticsTreatment.Income, 0.7),
        new(null, 910403, "Unemployment support.",
            ["Jobseeker's payment"],
            ["Inflow is unemployment support", "Direction is inflow"],
            [],
            ["JOBSEEKER"], CharacteristicsDirection.Inflow, CharacteristicsAnalyticsTreatment.Income, 0.7),
        new(null, 910404, "Child benefit.",
            ["Monthly child benefit"],
            ["Inflow is child benefit", "Direction is inflow"],
            [],
            ["CHILD BEN"], CharacteristicsDirection.Inflow, CharacteristicsAnalyticsTreatment.Income, 0.7),
        new(null, 910405, "Pension income.",
            ["Pension drawdown landing"],
            ["Inflow is pension income", "Direction is inflow"],
            ["Contributions into a pension belong to Savings & Investments"],
            ["STATE PENSION"], CharacteristicsDirection.Inflow, CharacteristicsAnalyticsTreatment.Income, 0.65),

        // -- 91050 Personal Inflows --
        new(91050, null, "Personal money arriving outside work and state.",
            ["Personal inflow"],
            ["Inflow is personal", "Direction is inflow"],
            ["Transfers between your own accounts are never personal inflows"],
            [], CharacteristicsDirection.Inflow, CharacteristicsAnalyticsTreatment.Income, 0.5),
        new(null, 910501, "Gifts received.",
            ["Birthday money"],
            ["Inflow is a personal gift", "Direction is inflow"],
            [],
            [], CharacteristicsDirection.Inflow, CharacteristicsAnalyticsTreatment.Income, 0.5),
        new(null, 910502, "Family support received.",
            ["Family helping out"],
            ["Inflow is family support", "Direction is inflow"],
            [],
            [], CharacteristicsDirection.Inflow, CharacteristicsAnalyticsTreatment.Income, 0.5),
        new(null, 910503, "Rental income.",
            ["Tenant's rent landing"],
            ["Inflow is rent you collect", "Direction is inflow"],
            [],
            [], CharacteristicsDirection.Inflow, CharacteristicsAnalyticsTreatment.Income, 0.5),
        new(null, 910504, "Miscellaneous income, user-assigned.",
            ["Income one-off with no better node"],
            ["Only deterministic rules or the user may assign this catch-all"],
            [],
            [], CharacteristicsDirection.Inflow, CharacteristicsAnalyticsTreatment.Income, null),
        new(null, 910505, "Gambling and lottery winnings.",
            ["Bookmaker withdrawal or lottery win"],
            ["Inflow is gambling winnings", "Direction is inflow"],
            ["Stakes and deposits belong to Entertainment's gambling"],
            [], CharacteristicsDirection.Inflow, CharacteristicsAnalyticsTreatment.Income, 0.5),
        new(null, 910506, "Maintenance and child support received.",
            ["Monthly maintenance landing"],
            ["Inflow is maintenance received", "Direction is inflow"],
            ["Maintenance you pay belongs to Family & Dependents"],
            [], CharacteristicsDirection.Inflow, CharacteristicsAnalyticsTreatment.Income, 0.5),
        new(null, 910507, "Marketplace and resale income.",
            ["Selling something secondhand"],
            ["Inflow is resale proceeds", "Direction is inflow"],
            [],
            [], CharacteristicsDirection.Inflow, CharacteristicsAnalyticsTreatment.Income, 0.5)
    ];
}
