namespace NSFinance.Shared.Taxonomy;

// Full-coverage characteristics: Personal Shopping (230), Gifts & Donations
// (240), Pets (250) - categories and subcategories.
public static partial class CategoryCharacteristicsCatalog
{
    private static readonly IReadOnlyList<CategoryCharacteristicsDefinition> ShoppingGiftsPetsDefinitions =
    [
        // -- 23010 Clothing subs --
        new(null, 230101, "Everyday clothes.",
            ["Wardrobe basics"],
            ["Purchase is everyday clothing", "Direction is outflow"],
            [],
            [], CharacteristicsDirection.Outflow, CharacteristicsAnalyticsTreatment.Expense, 0.5),
        new(null, 230102, "Formalwear.",
            ["Suit or occasion dress"],
            ["Purchase is formalwear", "Direction is outflow"],
            [],
            ["SUIT HIRE", "FORMALWEAR"], CharacteristicsDirection.Outflow, CharacteristicsAnalyticsTreatment.Expense, 0.6),
        new(null, 230103, "Workwear.",
            ["Work uniform or workwear"],
            ["Purchase is workwear", "Direction is outflow"],
            [],
            ["WORKWEAR"], CharacteristicsDirection.Outflow, CharacteristicsAnalyticsTreatment.Expense, 0.6),
        new(null, 230104, "Sportswear bought as clothing.",
            ["Trainers and gym wear"],
            ["Purchase is sportswear", "Direction is outflow"],
            ["Sports equipment belongs to Sports & Recreation"],
            ["GYMSHARK", "JD SPORTS", "LIFESTYLE SPORTS"], CharacteristicsDirection.Outflow, CharacteristicsAnalyticsTreatment.Expense, 0.7),
        new(null, 230105, "Underwear and sleepwear.",
            ["Underwear restock"],
            ["Purchase is underwear or sleepwear", "Direction is outflow"],
            [],
            [], CharacteristicsDirection.Outflow, CharacteristicsAnalyticsTreatment.Expense, 0.5),
        new(null, 230106, "Maternity wear.",
            ["Maternity clothes"],
            ["Purchase is maternity clothing", "Direction is outflow"],
            [],
            ["MATERNITY"], CharacteristicsDirection.Outflow, CharacteristicsAnalyticsTreatment.Expense, 0.6),
        new(null, 230107, "Children's clothing bought in a clothing context.",
            ["Kids' section haul"],
            ["Purchase is children's clothing", "Direction is outflow"],
            ["Family-level tracking prefers Child Essentials' Kids Clothing"],
            [], CharacteristicsDirection.Outflow, CharacteristicsAnalyticsTreatment.Expense, 0.5),

        // -- 23020 Shoes & Accessories --
        new(23020, null, "Finishing the outfit: shoes, bags, jewellery.",
            ["New shoes"],
            ["Purchase is footwear or accessories", "Direction is outflow"],
            [],
            [], CharacteristicsDirection.Outflow, CharacteristicsAnalyticsTreatment.Expense, 0.55),
        new(null, 230201, "Shoes.",
            ["Shoe shop purchase"],
            ["Purchase is footwear", "Direction is outflow"],
            [],
            ["SHOE", "FOOTLOCKER", "SKECHERS"], CharacteristicsDirection.Outflow, CharacteristicsAnalyticsTreatment.Expense, 0.6),
        new(null, 230202, "Bags.",
            ["New handbag"],
            ["Purchase is bags", "Direction is outflow"],
            ["Luggage belongs to Travel Gear"],
            [], CharacteristicsDirection.Outflow, CharacteristicsAnalyticsTreatment.Expense, 0.5),
        new(null, 230203, "Belts.",
            ["Belt purchase"],
            ["Purchase is belts", "Direction is outflow"],
            [],
            [], CharacteristicsDirection.Outflow, CharacteristicsAnalyticsTreatment.Expense, 0.5),
        new(null, 230204, "Wallets.",
            ["New wallet"],
            ["Purchase is wallets", "Direction is outflow"],
            [],
            [], CharacteristicsDirection.Outflow, CharacteristicsAnalyticsTreatment.Expense, 0.5),
        new(null, 230205, "Jewellery.",
            ["Jewellery purchase"],
            ["Purchase is jewellery", "Direction is outflow"],
            ["Investment pieces belong to Luxury & Specialty"],
            ["JEWELLER", "PANDORA"], CharacteristicsDirection.Outflow, CharacteristicsAnalyticsTreatment.Expense, 0.65),
        new(null, 230206, "Watches.",
            ["Watch purchase"],
            ["Purchase is watches", "Direction is outflow"],
            ["Smartwatches belong to Electronics"],
            [], CharacteristicsDirection.Outflow, CharacteristicsAnalyticsTreatment.Expense, 0.5),
        new(null, 230207, "Fashion sunglasses.",
            ["Sunglasses purchase"],
            ["Purchase is non-prescription sunglasses", "Direction is outflow"],
            ["Prescription lenses belong to Vision & Eye Care"],
            [], CharacteristicsDirection.Outflow, CharacteristicsAnalyticsTreatment.Expense, 0.5),

        // -- 23030 Electronics subs --
        new(null, 230301, "Phones.",
            ["New phone purchase"],
            ["Purchase is a phone", "Direction is outflow"],
            ["The plan bill belongs to Internet & Communications"],
            [], CharacteristicsDirection.Outflow, CharacteristicsAnalyticsTreatment.Expense, 0.5),
        new(null, 230302, "Tablets.",
            ["Tablet purchase"],
            ["Purchase is a tablet", "Direction is outflow"],
            [],
            [], CharacteristicsDirection.Outflow, CharacteristicsAnalyticsTreatment.Expense, 0.5),
        new(null, 230303, "Laptops.",
            ["Laptop purchase"],
            ["Purchase is a laptop", "Direction is outflow"],
            [],
            [], CharacteristicsDirection.Outflow, CharacteristicsAnalyticsTreatment.Expense, 0.5),
        new(null, 230304, "Electronics accessories: cables, chargers, cases.",
            ["Charger and case"],
            ["Purchase is electronics accessories", "Direction is outflow"],
            [],
            [], CharacteristicsDirection.Outflow, CharacteristicsAnalyticsTreatment.Expense, 0.5),
        new(null, 230305, "Smartwatches and wearables.",
            ["Fitness watch purchase"],
            ["Purchase is a wearable", "Direction is outflow"],
            [],
            ["FITBIT", "GARMIN"], CharacteristicsDirection.Outflow, CharacteristicsAnalyticsTreatment.Expense, 0.65),
        new(null, 230306, "Headphones and audio.",
            ["Headphones purchase"],
            ["Purchase is personal audio", "Direction is outflow"],
            [],
            [], CharacteristicsDirection.Outflow, CharacteristicsAnalyticsTreatment.Expense, 0.5),
        new(null, 230307, "Smart-home devices bought for yourself.",
            ["Smart speaker purchase"],
            ["Purchase is a smart-home device", "Direction is outflow"],
            ["Installed systems belong to Housing's Smart Home Installation"],
            [], CharacteristicsDirection.Outflow, CharacteristicsAnalyticsTreatment.Expense, 0.5),

        // -- 23040 Household Retail Purchases --
        new(23040, null, "General home retail: variety and household stores.",
            ["Variety store basket"],
            ["Merchant is general household retail", "Direction is outflow"],
            ["Specialist categories take precedence when identifiable"],
            ["DEALZ", "MR PRICE", "THE RANGE", "FLYING TIGER"], CharacteristicsDirection.Outflow, CharacteristicsAnalyticsTreatment.Expense, 0.65),
        new(null, 230401, "Home decor bought at general retail.",
            ["Decor from the household store"],
            ["Purchase is retail home decor", "Direction is outflow"],
            [],
            [], CharacteristicsDirection.Outflow, CharacteristicsAnalyticsTreatment.Expense, 0.5),
        new(null, 230402, "Kitchenware.",
            ["Pots and pans"],
            ["Purchase is kitchenware", "Direction is outflow"],
            [],
            ["KITCHENWARE"], CharacteristicsDirection.Outflow, CharacteristicsAnalyticsTreatment.Expense, 0.55),
        new(null, 230403, "Bedding bought at retail.",
            ["Sheets and duvet set"],
            ["Purchase is bedding", "Direction is outflow"],
            [],
            [], CharacteristicsDirection.Outflow, CharacteristicsAnalyticsTreatment.Expense, 0.5),
        new(null, 230404, "Storage goods at retail.",
            ["Storage boxes"],
            ["Purchase is storage goods", "Direction is outflow"],
            [],
            [], CharacteristicsDirection.Outflow, CharacteristicsAnalyticsTreatment.Expense, 0.5),
        new(null, 230405, "Seasonal decorations at retail.",
            ["Seasonal aisle basket"],
            ["Purchase is seasonal decor", "Direction is outflow"],
            [],
            [], CharacteristicsDirection.Outflow, CharacteristicsAnalyticsTreatment.Expense, 0.5),
        new(null, 230406, "Office supplies for personal use.",
            ["Home stationery"],
            ["Purchase is personal office supplies", "Direction is outflow"],
            ["Business supplies belong to Business Expenses"],
            [], CharacteristicsDirection.Outflow, CharacteristicsAnalyticsTreatment.Expense, 0.5),

        // -- 23050 Luxury & Specialty --
        new(23050, null, "The high end: designer, limited, boutique.",
            ["Designer purchase"],
            ["Purchase is luxury or specialty retail", "Direction is outflow"],
            [],
            ["BROWN THOMAS"], CharacteristicsDirection.Outflow, CharacteristicsAnalyticsTreatment.Expense, 0.65),
        new(null, 230501, "Designer goods.",
            ["Designer piece"],
            ["Purchase is designer goods", "Direction is outflow"],
            [],
            [], CharacteristicsDirection.Outflow, CharacteristicsAnalyticsTreatment.Expense, 0.5),
        new(null, 230502, "Premium collectibles bought at luxury retail.",
            ["Premium collectible"],
            ["Purchase is a premium collectible", "Direction is outflow"],
            ["Hobby collecting belongs to Collecting & Specialty Hobbies"],
            [], CharacteristicsDirection.Outflow, CharacteristicsAnalyticsTreatment.Expense, 0.5),
        new(null, 230503, "Boutique purchases.",
            ["Boutique find"],
            ["Purchase is from a specialty boutique", "Direction is outflow"],
            [],
            ["BOUTIQUE"], CharacteristicsDirection.Outflow, CharacteristicsAnalyticsTreatment.Expense, 0.55),
        new(null, 230504, "Limited editions.",
            ["Limited drop purchase"],
            ["Purchase is limited edition goods", "Direction is outflow"],
            [],
            [], CharacteristicsDirection.Outflow, CharacteristicsAnalyticsTreatment.Expense, 0.5),

        // -- 23060 Other Personal Shopping (real + catch-alls) --
        new(23060, null, "Shopping that fits nowhere else; a human choice, never an AI guess.",
            ["Genuinely unclassifiable retail expense"],
            ["Only deterministic rules or the user may assign this catch-all"],
            [],
            [], CharacteristicsDirection.Outflow, CharacteristicsAnalyticsTreatment.Expense, null),
        new(null, 230601, "Department stores.",
            ["Department store basket"],
            ["Merchant is a department store", "Direction is outflow"],
            [],
            ["ARNOTTS", "MARKS & SPENCER", "M&S "], CharacteristicsDirection.Outflow, CharacteristicsAnalyticsTreatment.Expense, 0.6),
        new(null, 230602, "Online marketplace purchases.",
            ["Marketplace order"],
            ["Merchant is an online marketplace", "Direction is outflow"],
            ["Identifiable sellers within the marketplace take precedence"],
            ["AMAZON", "EBAY", "ALIEXPRESS", "TEMU", "ETSY"], CharacteristicsDirection.Outflow, CharacteristicsAnalyticsTreatment.Expense, 0.65),
        new(null, 230603, "Miscellaneous retail, user-assigned.",
            ["Retail one-off with no better node"],
            ["Only deterministic rules or the user may assign this catch-all"],
            [],
            [], CharacteristicsDirection.Outflow, CharacteristicsAnalyticsTreatment.Expense, null),
        new(null, 230604, "Impulse purchases the user wants tracked as such.",
            ["Impulse buy flagged by the user"],
            ["Only deterministic rules or the user may assign this catch-all"],
            [],
            [], CharacteristicsDirection.Outflow, CharacteristicsAnalyticsTreatment.Expense, null),

        // -- 24010 Personal Gifts --
        new(24010, null, "Gifts you give people.",
            ["Birthday present"],
            ["Purchase is a personal gift", "Direction is outflow"],
            ["Charity belongs to Charitable Giving"],
            [], CharacteristicsDirection.Outflow, CharacteristicsAnalyticsTreatment.Expense, 0.5),
        new(null, 240101, "Birthday gifts.",
            ["Birthday present"],
            ["Gift marks a birthday", "Direction is outflow"],
            [],
            [], CharacteristicsDirection.Outflow, CharacteristicsAnalyticsTreatment.Expense, 0.5),
        new(null, 240102, "Wedding gifts.",
            ["Wedding present or cash gift"],
            ["Gift marks a wedding", "Direction is outflow"],
            [],
            [], CharacteristicsDirection.Outflow, CharacteristicsAnalyticsTreatment.Expense, 0.5),
        new(null, 240103, "Holiday gifts.",
            ["Christmas presents"],
            ["Gift marks a holiday", "Direction is outflow"],
            [],
            [], CharacteristicsDirection.Outflow, CharacteristicsAnalyticsTreatment.Expense, 0.5),
        new(null, 240104, "Baby shower gifts.",
            ["Baby shower present"],
            ["Gift marks a baby shower", "Direction is outflow"],
            [],
            [], CharacteristicsDirection.Outflow, CharacteristicsAnalyticsTreatment.Expense, 0.5),
        new(null, 240105, "Graduation gifts.",
            ["Graduation present"],
            ["Gift marks a graduation", "Direction is outflow"],
            [],
            [], CharacteristicsDirection.Outflow, CharacteristicsAnalyticsTreatment.Expense, 0.5),
        new(null, 240106, "Anniversary gifts.",
            ["Anniversary present"],
            ["Gift marks an anniversary", "Direction is outflow"],
            [],
            [], CharacteristicsDirection.Outflow, CharacteristicsAnalyticsTreatment.Expense, 0.5),
        new(null, 240107, "Gifts for other personal occasions.",
            ["Housewarming present"],
            ["Gift marks a personal occasion", "Direction is outflow"],
            [],
            [], CharacteristicsDirection.Outflow, CharacteristicsAnalyticsTreatment.Expense, 0.5),

        // -- 24020 Celebrations & Gift Support --
        new(24020, null, "Around the gift: cards, wrap, party support.",
            ["Cards and wrap"],
            ["Purchase supports a celebration", "Direction is outflow"],
            [],
            ["CARD FACTORY"], CharacteristicsDirection.Outflow, CharacteristicsAnalyticsTreatment.Expense, 0.6),
        new(null, 240201, "Party supplies.",
            ["Balloons and decorations"],
            ["Purchase is party supplies", "Direction is outflow"],
            [],
            [], CharacteristicsDirection.Outflow, CharacteristicsAnalyticsTreatment.Expense, 0.5),
        new(null, 240202, "Greeting cards.",
            ["Occasion card"],
            ["Purchase is greeting cards", "Direction is outflow"],
            [],
            [], CharacteristicsDirection.Outflow, CharacteristicsAnalyticsTreatment.Expense, 0.5),
        new(null, 240203, "Gift wrap.",
            ["Wrap and ribbon"],
            ["Purchase is gift wrap", "Direction is outflow"],
            [],
            [], CharacteristicsDirection.Outflow, CharacteristicsAnalyticsTreatment.Expense, 0.5),
        new(null, 240204, "Chipping into events.",
            ["Contribution to the office party"],
            ["Payment contributes to an event", "Direction is outflow"],
            [],
            [], CharacteristicsDirection.Outflow, CharacteristicsAnalyticsTreatment.Expense, 0.5),
        new(null, 240205, "Group gifts you chip into.",
            ["Share of the group present"],
            ["Payment is a share of a group gift", "Direction is outflow"],
            [],
            [], CharacteristicsDirection.Outflow, CharacteristicsAnalyticsTreatment.Expense, 0.5),

        // -- 24030 Charitable Giving --
        new(24030, null, "Giving to causes.",
            ["Monthly charity direct debit"],
            ["Payment is charitable giving", "Direction is outflow"],
            ["Church giving belongs to Religious Or Spiritual Giving"],
            ["TROCAIRE", "CONCERN", "UNICEF", "FOCUS IRELAND", "SVP"], CharacteristicsDirection.Outflow, CharacteristicsAnalyticsTreatment.Expense, 0.75),
        new(null, 240301, "Direct charitable donations.",
            ["One-off donation"],
            ["Payment is a charity donation", "Direction is outflow"],
            [],
            [], CharacteristicsDirection.Outflow, CharacteristicsAnalyticsTreatment.Expense, 0.55),
        new(null, 240302, "Crowdfunding support.",
            ["Fundraiser contribution"],
            ["Payment supports a crowdfund", "Direction is outflow"],
            [],
            ["GOFUNDME", "IDONATE"], CharacteristicsDirection.Outflow, CharacteristicsAnalyticsTreatment.Expense, 0.75),
        new(null, 240303, "Nonprofit contributions.",
            ["NGO membership contribution"],
            ["Payment supports a nonprofit", "Direction is outflow"],
            [],
            [], CharacteristicsDirection.Outflow, CharacteristicsAnalyticsTreatment.Expense, 0.5),
        new(null, 240304, "Sponsoring people in events.",
            ["Sponsoring a charity run"],
            ["Payment sponsors a charity event", "Direction is outflow"],
            [],
            [], CharacteristicsDirection.Outflow, CharacteristicsAnalyticsTreatment.Expense, 0.5),
        new(null, 240305, "Donations tied to volunteering.",
            ["Volunteer trip contribution"],
            ["Payment supports volunteering", "Direction is outflow"],
            [],
            [], CharacteristicsDirection.Outflow, CharacteristicsAnalyticsTreatment.Expense, 0.5),

        // -- 24040 Other Giving --
        new(24040, null, "Giving that fits nowhere else; a human choice, never an AI guess.",
            ["Genuinely unclassifiable giving expense"],
            ["Only deterministic rules or the user may assign this catch-all"],
            [],
            [], CharacteristicsDirection.Outflow, CharacteristicsAnalyticsTreatment.Expense, null),
        new(null, 240401, "Community support.",
            ["Local community collection"],
            ["Payment supports the community", "Direction is outflow"],
            [],
            [], CharacteristicsDirection.Outflow, CharacteristicsAnalyticsTreatment.Expense, 0.5),
        new(null, 240402, "Informal financial help to people.",
            ["Helping someone out"],
            ["Payment is informal help", "Direction is outflow"],
            ["Loan repayments belong to Family & Informal Debt"],
            [], CharacteristicsDirection.Outflow, CharacteristicsAnalyticsTreatment.Expense, 0.5),
        new(null, 240403, "Other giving, user-assigned.",
            ["Giving one-off with no better node"],
            ["Only deterministic rules or the user may assign this catch-all"],
            [],
            [], CharacteristicsDirection.Outflow, CharacteristicsAnalyticsTreatment.Expense, null),
        new(null, 240404, "Political donations.",
            ["Party or campaign donation"],
            ["Payment is a political donation", "Direction is outflow"],
            ["Charity belongs to Charitable Giving"],
            [], CharacteristicsDirection.Outflow, CharacteristicsAnalyticsTreatment.Expense, 0.6),

        // -- 25010 Pet Food & Supplies subs --
        new(null, 250101, "Pet food.",
            ["Dog food bag"],
            ["Purchase is pet food", "Direction is outflow"],
            [],
            ["PET FOOD"], CharacteristicsDirection.Outflow, CharacteristicsAnalyticsTreatment.Expense, 0.55),
        new(null, 250102, "Pet treats.",
            ["Treats top-up"],
            ["Purchase is pet treats", "Direction is outflow"],
            [],
            [], CharacteristicsDirection.Outflow, CharacteristicsAnalyticsTreatment.Expense, 0.5),
        new(null, 250103, "Litter and bedding.",
            ["Cat litter"],
            ["Purchase is litter or bedding", "Direction is outflow"],
            [],
            [], CharacteristicsDirection.Outflow, CharacteristicsAnalyticsTreatment.Expense, 0.5),
        new(null, 250104, "Pet toys.",
            ["New pet toy"],
            ["Purchase is pet toys", "Direction is outflow"],
            [],
            [], CharacteristicsDirection.Outflow, CharacteristicsAnalyticsTreatment.Expense, 0.5),
        new(null, 250105, "Pet grooming supplies.",
            ["Brush and shampoo for the dog"],
            ["Purchase is pet grooming supplies", "Direction is outflow"],
            ["Groomer visits belong to Grooming & Boarding"],
            [], CharacteristicsDirection.Outflow, CharacteristicsAnalyticsTreatment.Expense, 0.5),
        new(null, 250106, "Cages, tanks, and habitat accessories.",
            ["New aquarium kit"],
            ["Purchase is pet housing or accessories", "Direction is outflow"],
            [],
            ["AQUARIUM"], CharacteristicsDirection.Outflow, CharacteristicsAnalyticsTreatment.Expense, 0.55),

        // -- 25020 Veterinary Care --
        new(25020, null, "The vet: checkups to emergencies.",
            ["Vet visit"],
            ["Merchant is a veterinary practice", "Direction is outflow"],
            [],
            ["VETERINARY", "VETS", "VET CLINIC"], CharacteristicsDirection.Outflow, CharacteristicsAnalyticsTreatment.Expense, 0.7),
        new(null, 250201, "Routine vet checkups.",
            ["Annual checkup"],
            ["Visit is routine veterinary care", "Direction is outflow"],
            [],
            [], CharacteristicsDirection.Outflow, CharacteristicsAnalyticsTreatment.Expense, 0.5),
        new(null, 250202, "Pet vaccinations.",
            ["Booster shots"],
            ["Charge is pet vaccination", "Direction is outflow"],
            [],
            [], CharacteristicsDirection.Outflow, CharacteristicsAnalyticsTreatment.Expense, 0.5),
        new(null, 250203, "Pet medication.",
            ["Flea and worm treatment"],
            ["Purchase is pet medication", "Direction is outflow"],
            [],
            [], CharacteristicsDirection.Outflow, CharacteristicsAnalyticsTreatment.Expense, 0.5),
        new(null, 250204, "Pet surgery.",
            ["Operation for the pet"],
            ["Charge is pet surgery", "Direction is outflow"],
            [],
            [], CharacteristicsDirection.Outflow, CharacteristicsAnalyticsTreatment.Expense, 0.5),
        new(null, 250205, "Emergency vet visits.",
            ["Out-of-hours vet"],
            ["Charge is emergency veterinary care", "Direction is outflow"],
            [],
            [], CharacteristicsDirection.Outflow, CharacteristicsAnalyticsTreatment.Expense, 0.5),
        new(null, 250206, "Pet dental work.",
            ["Dental clean for the dog"],
            ["Charge is pet dental care", "Direction is outflow"],
            [],
            [], CharacteristicsDirection.Outflow, CharacteristicsAnalyticsTreatment.Expense, 0.5),

        // -- 25030 Grooming & Boarding --
        new(25030, null, "Minding and grooming the pet.",
            ["Groomer appointment"],
            ["Service grooms or minds a pet", "Direction is outflow"],
            [],
            ["PET GROOMING", "DOG GROOMING", "KENNELS", "CATTERY"], CharacteristicsDirection.Outflow, CharacteristicsAnalyticsTreatment.Expense, 0.7),
        new(null, 250301, "Pet grooming visits.",
            ["Full groom"],
            ["Service is pet grooming", "Direction is outflow"],
            [],
            [], CharacteristicsDirection.Outflow, CharacteristicsAnalyticsTreatment.Expense, 0.55),
        new(null, 250302, "Boarding: kennels and catteries.",
            ["Kennels for the week away"],
            ["Service boards the pet", "Direction is outflow"],
            [],
            [], CharacteristicsDirection.Outflow, CharacteristicsAnalyticsTreatment.Expense, 0.55),
        new(null, 250303, "Pet sitting.",
            ["Sitter for the weekend"],
            ["Service is pet sitting", "Direction is outflow"],
            [],
            ["PET SITTING"], CharacteristicsDirection.Outflow, CharacteristicsAnalyticsTreatment.Expense, 0.6),
        new(null, 250304, "Dog walking.",
            ["Weekday walker"],
            ["Service is dog walking", "Direction is outflow"],
            [],
            ["DOG WALKING"], CharacteristicsDirection.Outflow, CharacteristicsAnalyticsTreatment.Expense, 0.65),
        new(null, 250305, "Pet daycare.",
            ["Doggy daycare day"],
            ["Service is pet daycare", "Direction is outflow"],
            [],
            ["DOGGY DAYCARE"], CharacteristicsDirection.Outflow, CharacteristicsAnalyticsTreatment.Expense, 0.65),

        // -- 25040 Pet Purchase & Adoption --
        new(25040, null, "Bringing a pet home and making it official.",
            ["Adoption fee"],
            ["Charge acquires or registers a pet", "Direction is outflow"],
            [],
            [], CharacteristicsDirection.Outflow, CharacteristicsAnalyticsTreatment.Expense, 0.55),
        new(null, 250401, "Adoption fees.",
            ["Shelter adoption fee"],
            ["Charge is a pet adoption", "Direction is outflow"],
            [],
            ["ADOPTION FEE", "RESCUE"], CharacteristicsDirection.Outflow, CharacteristicsAnalyticsTreatment.Expense, 0.6),
        new(null, 250402, "Buying a pet.",
            ["Purchase from a breeder"],
            ["Charge buys a pet", "Direction is outflow"],
            [],
            [], CharacteristicsDirection.Outflow, CharacteristicsAnalyticsTreatment.Expense, 0.5),
        new(null, 250403, "Pet licensing and registration.",
            ["Dog licence"],
            ["Charge licenses a pet", "Direction is outflow"],
            [],
            ["DOG LICENCE", "DOG LICENSE"], CharacteristicsDirection.Outflow, CharacteristicsAnalyticsTreatment.Expense, 0.7),
        new(null, 250404, "Pet training classes.",
            ["Puppy classes"],
            ["Charge is pet training", "Direction is outflow"],
            [],
            ["DOG TRAINING", "PUPPY CLASS"], CharacteristicsDirection.Outflow, CharacteristicsAnalyticsTreatment.Expense, 0.65),

        // -- 25050 Other Pet Costs (real + catch-all) --
        new(25050, null, "Pet costs that fit nowhere else; a human choice, never an AI guess.",
            ["Genuinely unclassifiable pet expense"],
            ["Only deterministic rules or the user may assign this catch-all"],
            [],
            [], CharacteristicsDirection.Outflow, CharacteristicsAnalyticsTreatment.Expense, null),
        new(null, 250501, "Traveling with pets.",
            ["Pet travel carrier and fees"],
            ["Charge enables pet travel", "Direction is outflow"],
            [],
            [], CharacteristicsDirection.Outflow, CharacteristicsAnalyticsTreatment.Expense, 0.5),
        new(null, 250502, "Pet memorial costs.",
            ["Cremation for a pet"],
            ["Charge is a pet memorial", "Direction is outflow"],
            [],
            ["PET CREMATOR"], CharacteristicsDirection.Outflow, CharacteristicsAnalyticsTreatment.Expense, 0.6),
        new(null, 250503, "Other pet expense, user-assigned.",
            ["Pet one-off with no better node"],
            ["Only deterministic rules or the user may assign this catch-all"],
            [],
            [], CharacteristicsDirection.Outflow, CharacteristicsAnalyticsTreatment.Expense, null)
    ];
}
