namespace NSFinance.Shared.Taxonomy;

// Full-coverage characteristics: Education (260) and Taxes (270) -
// categories and subcategories.
public static partial class CategoryCharacteristicsCatalog
{
    private static readonly IReadOnlyList<CategoryCharacteristicsDefinition> EducationTaxesDefinitions =
    [
        // -- 26010 Tuition & Fees --
        new(26010, null, "Paying for the education itself.",
            ["Tuition instalment"],
            ["Charge is tuition or an academic fee", "Direction is outflow"],
            ["Children's creche and preschool fees belong to Family & Dependents"],
            ["TUITION"], CharacteristicsDirection.Outflow, CharacteristicsAnalyticsTreatment.Expense, 0.65),
        new(null, 260101, "School tuition.",
            ["Private school fees"],
            ["Charge is school tuition", "Direction is outflow"],
            [],
            [], CharacteristicsDirection.Outflow, CharacteristicsAnalyticsTreatment.Expense, 0.5),
        new(null, 260102, "University and college tuition.",
            ["Semester registration payment"],
            ["Charge is third-level tuition", "Direction is outflow"],
            [],
            ["UNIVERSITY"], CharacteristicsDirection.Outflow, CharacteristicsAnalyticsTreatment.Expense, 0.55),
        new(null, 260103, "Registration fees.",
            ["Course registration fee"],
            ["Charge registers enrolment", "Direction is outflow"],
            [],
            [], CharacteristicsDirection.Outflow, CharacteristicsAnalyticsTreatment.Expense, 0.5),
        new(null, 260104, "Lab fees.",
            ["Laboratory module fee"],
            ["Charge is a lab fee", "Direction is outflow"],
            [],
            [], CharacteristicsDirection.Outflow, CharacteristicsAnalyticsTreatment.Expense, 0.5),
        new(null, 260105, "Exam fees.",
            ["Exam sitting fee"],
            ["Charge is an exam fee", "Direction is outflow"],
            [],
            ["EXAM FEE"], CharacteristicsDirection.Outflow, CharacteristicsAnalyticsTreatment.Expense, 0.6),
        new(null, 260106, "Graduation fees.",
            ["Conferring ceremony fee"],
            ["Charge is a graduation fee", "Direction is outflow"],
            [],
            [], CharacteristicsDirection.Outflow, CharacteristicsAnalyticsTreatment.Expense, 0.5),

        // -- 26020 Learning Materials --
        new(26020, null, "The materials study runs on.",
            ["Textbooks and supplies"],
            ["Purchase is study materials", "Direction is outflow"],
            ["Leisure reading belongs to Entertainment's books"],
            [], CharacteristicsDirection.Outflow, CharacteristicsAnalyticsTreatment.Expense, 0.5),
        new(null, 260201, "Textbooks.",
            ["Course textbook order"],
            ["Purchase is textbooks", "Direction is outflow"],
            ["Bookshop brand signals belong to Entertainment's books"],
            ["TEXTBOOK"], CharacteristicsDirection.Outflow, CharacteristicsAnalyticsTreatment.Expense, 0.6),
        new(null, 260202, "Stationery for study.",
            ["Pens and refill pads"],
            ["Purchase is study stationery", "Direction is outflow"],
            [],
            [], CharacteristicsDirection.Outflow, CharacteristicsAnalyticsTreatment.Expense, 0.5),
        new(null, 260203, "Online courses.",
            ["Course platform purchase"],
            ["Purchase is an online course", "Direction is outflow"],
            [],
            ["UDEMY", "COURSERA", "SKILLSHARE", "EDX"], CharacteristicsDirection.Outflow, CharacteristicsAnalyticsTreatment.Expense, 0.75),
        new(null, 260204, "Software bought for study.",
            ["Student software licence"],
            ["Purchase is study software", "Direction is outflow"],
            ["General software subscriptions belong to Software & Digital Tools"],
            [], CharacteristicsDirection.Outflow, CharacteristicsAnalyticsTreatment.Expense, 0.5),
        new(null, 260205, "School uniforms.",
            ["Uniform for the school year"],
            ["Purchase is school uniforms", "Direction is outflow"],
            [],
            ["SCHOOLWEAR", "SCHOOL UNIFORM"], CharacteristicsDirection.Outflow, CharacteristicsAnalyticsTreatment.Expense, 0.65),
        new(null, 260206, "General school supplies.",
            ["Back-to-school supplies"],
            ["Purchase is school supplies", "Direction is outflow"],
            [],
            [], CharacteristicsDirection.Outflow, CharacteristicsAnalyticsTreatment.Expense, 0.5),

        // -- 26030 Lessons & Training --
        new(26030, null, "Structured learning outside formal education.",
            ["Evening class"],
            ["Charge is lessons or training", "Direction is outflow"],
            ["Children's activity classes belong to Family & Dependents"],
            [], CharacteristicsDirection.Outflow, CharacteristicsAnalyticsTreatment.Expense, 0.5),
        new(null, 260301, "Language classes.",
            ["Language app or course"],
            ["Charge is language learning", "Direction is outflow"],
            [],
            ["DUOLINGO", "BABBEL", "ROSETTA STONE"], CharacteristicsDirection.Outflow, CharacteristicsAnalyticsTreatment.Expense, 0.75),
        new(null, 260302, "Music lessons.",
            ["Weekly music lesson"],
            ["Charge is music lessons", "Direction is outflow"],
            [],
            ["MUSIC LESSON", "MUSIC SCHOOL"], CharacteristicsDirection.Outflow, CharacteristicsAnalyticsTreatment.Expense, 0.65),
        new(null, 260303, "Coding courses.",
            ["Programming bootcamp instalment"],
            ["Charge is coding education", "Direction is outflow"],
            [],
            ["CODECADEMY", "PLURALSIGHT", "BOOTCAMP"], CharacteristicsDirection.Outflow, CharacteristicsAnalyticsTreatment.Expense, 0.7),
        new(null, 260304, "Professional certifications.",
            ["Certification exam and prep"],
            ["Charge is professional certification", "Direction is outflow"],
            [],
            ["CERTIFICATION"], CharacteristicsDirection.Outflow, CharacteristicsAnalyticsTreatment.Expense, 0.6),
        new(null, 260305, "Trade training.",
            ["Trade course fee"],
            ["Charge is trade training", "Direction is outflow"],
            [],
            [], CharacteristicsDirection.Outflow, CharacteristicsAnalyticsTreatment.Expense, 0.5),

        // -- 26040 Student Living Costs --
        new(26040, null, "The costs of living as a student.",
            ["Dorm instalment"],
            ["Charge is student living costs", "Direction is outflow"],
            ["Ordinary rent belongs to Housing"],
            [], CharacteristicsDirection.Outflow, CharacteristicsAnalyticsTreatment.Expense, 0.5),
        new(null, 260401, "Dorm and student accommodation fees.",
            ["Campus accommodation payment"],
            ["Charge is student accommodation", "Direction is outflow"],
            [],
            ["STUDENT ACCOMMODATION"], CharacteristicsDirection.Outflow, CharacteristicsAnalyticsTreatment.Expense, 0.6),
        new(null, 260402, "Student meal plans.",
            ["Semester meal plan"],
            ["Charge is a student meal plan", "Direction is outflow"],
            [],
            ["MEAL PLAN"], CharacteristicsDirection.Outflow, CharacteristicsAnalyticsTreatment.Expense, 0.55),
        new(null, 260403, "Student travel.",
            ["Term-time commute costs"],
            ["Charge is student travel", "Direction is outflow"],
            ["Ordinary public transport belongs to Transportation"],
            [], CharacteristicsDirection.Outflow, CharacteristicsAnalyticsTreatment.Expense, 0.5),
        new(null, 260404, "Campus fees.",
            ["Student services levy"],
            ["Charge is a campus levy", "Direction is outflow"],
            [],
            [], CharacteristicsDirection.Outflow, CharacteristicsAnalyticsTreatment.Expense, 0.5),

        // -- 26050 Other Education (real + catch-all) --
        new(26050, null, "Education costs that fit nowhere else; a human choice, never an AI guess.",
            ["Genuinely unclassifiable education expense"],
            ["Only deterministic rules or the user may assign this catch-all"],
            [],
            [], CharacteristicsDirection.Outflow, CharacteristicsAnalyticsTreatment.Expense, null),
        new(null, 260501, "Tutoring for your own study.",
            ["Adult tutoring session"],
            ["Charge is tutoring", "Direction is outflow"],
            ["Children's grinds belong to Family & Dependents' tutoring"],
            [], CharacteristicsDirection.Outflow, CharacteristicsAnalyticsTreatment.Expense, 0.5),
        new(null, 260502, "Test prep.",
            ["Entrance exam prep course"],
            ["Charge is test preparation", "Direction is outflow"],
            [],
            [], CharacteristicsDirection.Outflow, CharacteristicsAnalyticsTreatment.Expense, 0.5),
        new(null, 260503, "Study abroad costs.",
            ["Exchange programme fee"],
            ["Charge funds study abroad", "Direction is outflow"],
            [],
            ["STUDY ABROAD", "ERASMUS"], CharacteristicsDirection.Outflow, CharacteristicsAnalyticsTreatment.Expense, 0.6),
        new(null, 260504, "Other learning expenses, user-assigned.",
            ["Learning one-off with no better node"],
            ["Only deterministic rules or the user may assign this catch-all"],
            [],
            [], CharacteristicsDirection.Outflow, CharacteristicsAnalyticsTreatment.Expense, null),

        // -- 27010 Income Taxes --
        new(27010, null, "Personal income tax paid to the tax authority.",
            ["Revenue balancing payment"],
            ["Payment settles personal income tax", "Direction is outflow"],
            ["Payroll deductions never appear as transactions; only direct payments"],
            ["REVENUE"], CharacteristicsDirection.Outflow, CharacteristicsAnalyticsTreatment.Expense, 0.7),
        new(null, 270101, "Income tax payments.",
            ["Balancing statement payment"],
            ["Payment is income tax", "Direction is outflow"],
            [],
            ["INCOME TAX"], CharacteristicsDirection.Outflow, CharacteristicsAnalyticsTreatment.Expense, 0.6),
        new(null, 270102, "Estimated and preliminary tax.",
            ["Preliminary tax for the year"],
            ["Payment is estimated tax", "Direction is outflow"],
            [],
            ["PRELIMINARY TAX"], CharacteristicsDirection.Outflow, CharacteristicsAnalyticsTreatment.Expense, 0.65),
        new(null, 270103, "Underpayment penalties.",
            ["Interest on late tax"],
            ["Charge penalizes tax underpayment", "Direction is outflow"],
            [],
            [], CharacteristicsDirection.Outflow, CharacteristicsAnalyticsTreatment.Expense, 0.5),
        new(null, 270104, "Tax settlements.",
            ["Agreed settlement instalment"],
            ["Payment settles a tax liability", "Direction is outflow"],
            [],
            [], CharacteristicsDirection.Outflow, CharacteristicsAnalyticsTreatment.Expense, 0.5),

        // -- 27020 Property & Local Taxes --
        new(27020, null, "Taxes on property and place.",
            ["Property tax bill"],
            ["Payment is property or local tax", "Direction is outflow"],
            ["Irish LPT carries deterministic signals under Housing's Local Property Tax"],
            [], CharacteristicsDirection.Outflow, CharacteristicsAnalyticsTreatment.Expense, 0.5),
        new(null, 270201, "Property tax outside the Irish LPT flow.",
            ["Foreign property tax"],
            ["Payment is property tax", "Direction is outflow"],
            ["Irish LPT belongs to Housing's Local Property Tax"],
            [], CharacteristicsDirection.Outflow, CharacteristicsAnalyticsTreatment.Expense, 0.5),
        new(null, 270202, "Local taxes and levies.",
            ["Local authority levy"],
            ["Payment is a local tax", "Direction is outflow"],
            [],
            [], CharacteristicsDirection.Outflow, CharacteristicsAnalyticsTreatment.Expense, 0.5),
        new(null, 270203, "Council tax.",
            ["UK council tax while abroad"],
            ["Payment is council tax", "Direction is outflow"],
            [],
            ["COUNCIL TAX"], CharacteristicsDirection.Outflow, CharacteristicsAnalyticsTreatment.Expense, 0.7),
        new(null, 270204, "Stamp duty and transfer taxes on property.",
            ["Stamp duty on a purchase"],
            ["Payment is stamp duty or transfer tax", "Direction is outflow"],
            ["The annual card levy belongs to Banking & Account Fees' card fees"],
            [], CharacteristicsDirection.Outflow, CharacteristicsAnalyticsTreatment.Expense, 0.5),

        // -- 27030 Vehicle & Usage Taxes --
        new(27030, null, "Taxes on owning and using vehicles.",
            ["Motor tax renewal"],
            ["Payment is a vehicle tax", "Direction is outflow"],
            ["Motor tax carries deterministic signals under Transportation"],
            [], CharacteristicsDirection.Outflow, CharacteristicsAnalyticsTreatment.Expense, 0.5),
        new(null, 270301, "Motor tax tracked under taxes.",
            ["Motor tax when tracked as tax"],
            ["Payment is motor tax", "Direction is outflow"],
            ["Motor tax signals resolve deterministically to Transportation's node"],
            [], CharacteristicsDirection.Outflow, CharacteristicsAnalyticsTreatment.Expense, 0.5),
        new(null, 270302, "Vehicle registration tax.",
            ["VRT on an import"],
            ["Payment is registration tax", "Direction is outflow"],
            [],
            ["VRT"], CharacteristicsDirection.Outflow, CharacteristicsAnalyticsTreatment.Expense, 0.6),
        new(null, 270303, "Road use taxes.",
            ["Road usage charge"],
            ["Payment is a road use tax", "Direction is outflow"],
            ["Tolls belong to Transportation"],
            [], CharacteristicsDirection.Outflow, CharacteristicsAnalyticsTreatment.Expense, 0.5),

        // -- 27040 Sales / VAT / Business Taxes --
        new(27040, null, "Consumption and business taxes paid directly.",
            ["VAT return payment"],
            ["Payment is VAT, sales, or business tax", "Direction is outflow"],
            [],
            [], CharacteristicsDirection.Outflow, CharacteristicsAnalyticsTreatment.Expense, 0.5),
        new(null, 270401, "VAT payments.",
            ["Bimonthly VAT3 payment"],
            ["Payment settles VAT", "Direction is outflow"],
            [],
            ["VAT PAYMENT", "VAT3"], CharacteristicsDirection.Outflow, CharacteristicsAnalyticsTreatment.Expense, 0.65),
        new(null, 270402, "Sales tax payments.",
            ["Foreign sales tax remittance"],
            ["Payment settles sales tax", "Direction is outflow"],
            [],
            [], CharacteristicsDirection.Outflow, CharacteristicsAnalyticsTreatment.Expense, 0.5),
        new(null, 270403, "Business tax payments.",
            ["Corporation tax instalment"],
            ["Payment settles business tax", "Direction is outflow"],
            [],
            ["CORPORATION TAX"], CharacteristicsDirection.Outflow, CharacteristicsAnalyticsTreatment.Expense, 0.6),
        new(null, 270404, "Payroll taxes remitted as an employer.",
            ["Employer payroll remittance"],
            ["Payment remits payroll taxes", "Direction is outflow"],
            [],
            [], CharacteristicsDirection.Outflow, CharacteristicsAnalyticsTreatment.Expense, 0.5),

        // -- 27050 Tax Services --
        new(27050, null, "Help with tax: software and people.",
            ["Tax return service"],
            ["Charge is tax preparation help", "Direction is outflow"],
            [],
            ["TAXBACK"], CharacteristicsDirection.Outflow, CharacteristicsAnalyticsTreatment.Expense, 0.6),
        new(null, 270501, "Tax filing software.",
            ["Filing software licence"],
            ["Charge is tax software", "Direction is outflow"],
            [],
            [], CharacteristicsDirection.Outflow, CharacteristicsAnalyticsTreatment.Expense, 0.5),
        new(null, 270502, "Accountants and tax preparers.",
            ["Return prepared by an accountant"],
            ["Charge is tax preparation", "Direction is outflow"],
            ["Business accounting belongs to Business Expenses"],
            [], CharacteristicsDirection.Outflow, CharacteristicsAnalyticsTreatment.Expense, 0.5),
        new(null, 270503, "Tax filing fees.",
            ["Late filing surcharge"],
            ["Charge is a filing fee", "Direction is outflow"],
            [],
            [], CharacteristicsDirection.Outflow, CharacteristicsAnalyticsTreatment.Expense, 0.5),
        new(null, 270504, "Audit support.",
            ["Representation during an audit"],
            ["Charge is audit support", "Direction is outflow"],
            [],
            [], CharacteristicsDirection.Outflow, CharacteristicsAnalyticsTreatment.Expense, 0.5),

        // -- 27060 Other Taxes (real + catch-all) --
        new(27060, null, "Taxes that fit nowhere else; a human choice, never an AI guess.",
            ["Genuinely unclassifiable tax charge"],
            ["Only deterministic rules or the user may assign this catch-all"],
            [],
            [], CharacteristicsDirection.Outflow, CharacteristicsAnalyticsTreatment.Expense, null),
        new(null, 270601, "Import duties.",
            ["Duty on an import"],
            ["Charge is import duty", "Direction is outflow"],
            [],
            ["IMPORT DUTY"], CharacteristicsDirection.Outflow, CharacteristicsAnalyticsTreatment.Expense, 0.6),
        new(null, 270602, "Customs charges.",
            ["Customs charge on a parcel"],
            ["Charge is customs", "Direction is outflow"],
            [],
            ["CUSTOMS"], CharacteristicsDirection.Outflow, CharacteristicsAnalyticsTreatment.Expense, 0.6),
        new(null, 270603, "Tax penalties.",
            ["Penalty for late filing"],
            ["Charge is a tax penalty", "Direction is outflow"],
            [],
            [], CharacteristicsDirection.Outflow, CharacteristicsAnalyticsTreatment.Expense, 0.5),
        new(null, 270604, "Other government tax charges, user-assigned.",
            ["Tax one-off with no better node"],
            ["Only deterministic rules or the user may assign this catch-all"],
            [],
            [], CharacteristicsDirection.Outflow, CharacteristicsAnalyticsTreatment.Expense, null)
    ];
}
