namespace NSFinance.Shared.Taxonomy;

// Full-coverage characteristics: Subscriptions (280) and Business Expenses
// (290) - categories and subcategories. Streaming and software brand signals
// moved down from the 28010/28020/29030 category definitions.
public static partial class CategoryCharacteristicsCatalog
{
    private static readonly IReadOnlyList<CategoryCharacteristicsDefinition> SubscriptionsBusinessDefinitions =
    [
        // -- 28010 Streaming & Media subs --
        new(null, 280101, "Netflix.",
            ["Monthly Netflix charge"],
            ["Merchant is Netflix", "Direction is outflow"],
            [],
            ["NETFLIX"], CharacteristicsDirection.Outflow, CharacteristicsAnalyticsTreatment.Expense, 0.85),
        new(null, 280102, "Spotify.",
            ["Monthly Spotify charge"],
            ["Merchant is Spotify", "Direction is outflow"],
            [],
            ["SPOTIFY"], CharacteristicsDirection.Outflow, CharacteristicsAnalyticsTreatment.Expense, 0.85),
        new(null, 280103, "YouTube Premium.",
            ["Monthly YouTube Premium charge"],
            ["Merchant is YouTube Premium", "Direction is outflow"],
            [],
            ["YOUTUBE PREMIUM"], CharacteristicsDirection.Outflow, CharacteristicsAnalyticsTreatment.Expense, 0.85),
        new(null, 280104, "Disney+.",
            ["Monthly Disney+ charge"],
            ["Merchant is Disney+", "Direction is outflow"],
            [],
            ["DISNEY"], CharacteristicsDirection.Outflow, CharacteristicsAnalyticsTreatment.Expense, 0.8),
        new(null, 280105, "Audible.",
            ["Monthly Audible credit"],
            ["Merchant is Audible", "Direction is outflow"],
            ["Audible brand signals resolve deterministically to Entertainment's audiobooks"],
            [], CharacteristicsDirection.Outflow, CharacteristicsAnalyticsTreatment.Expense, 0.55),
        new(null, 280106, "Other streaming services.",
            ["Any other streaming subscription"],
            ["Merchant is a streaming service without its own node", "Direction is outflow"],
            [],
            ["PRIME VIDEO", "NOW TV", "PARAMOUNT", "CRUNCHYROLL"], CharacteristicsDirection.Outflow, CharacteristicsAnalyticsTreatment.Expense, 0.75),

        // -- 28020 Software & Digital Tools subs --
        new(null, 280201, "Microsoft 365.",
            ["Annual Microsoft 365 renewal"],
            ["Merchant is Microsoft for a personal licence", "Direction is outflow"],
            [],
            ["MICROSOFT"], CharacteristicsDirection.Outflow, CharacteristicsAnalyticsTreatment.Expense, 0.7),
        new(null, 280202, "Google One.",
            ["Monthly Google One storage"],
            ["Merchant is Google One", "Direction is outflow"],
            [],
            ["GOOGLE ONE"], CharacteristicsDirection.Outflow, CharacteristicsAnalyticsTreatment.Expense, 0.8),
        new(null, 280203, "Adobe.",
            ["Monthly Creative Cloud charge"],
            ["Merchant is Adobe", "Direction is outflow"],
            [],
            ["ADOBE"], CharacteristicsDirection.Outflow, CharacteristicsAnalyticsTreatment.Expense, 0.8),
        new(null, 280204, "Cloud storage.",
            ["Personal cloud storage plan"],
            ["Charge is personal cloud storage", "Direction is outflow"],
            [],
            ["DROPBOX", "ICLOUD"], CharacteristicsDirection.Outflow, CharacteristicsAnalyticsTreatment.Expense, 0.75),
        new(null, 280205, "Antivirus.",
            ["Annual antivirus renewal"],
            ["Charge is antivirus or security software", "Direction is outflow"],
            [],
            ["NORTON", "MCAFEE", "AVAST"], CharacteristicsDirection.Outflow, CharacteristicsAnalyticsTreatment.Expense, 0.8),
        new(null, 280206, "Productivity apps.",
            ["Note-taking app plan"],
            ["Charge is a productivity app", "Direction is outflow"],
            [],
            ["NOTION", "EVERNOTE", "TODOIST"], CharacteristicsDirection.Outflow, CharacteristicsAnalyticsTreatment.Expense, 0.75),

        // -- 28030 Memberships --
        new(28030, null, "Belonging somewhere: clubs, associations, memberships.",
            ["Annual membership renewal"],
            ["Charge is a recurring membership", "Direction is outflow"],
            [],
            [], CharacteristicsDirection.Outflow, CharacteristicsAnalyticsTreatment.Expense, 0.5),
        new(null, 280301, "Gym memberships tracked under subscriptions.",
            ["Gym plan when tracked as a subscription"],
            ["Charge is a gym membership", "Direction is outflow"],
            ["Gym brand signals resolve deterministically to Personal Care's gym membership"],
            [], CharacteristicsDirection.Outflow, CharacteristicsAnalyticsTreatment.Expense, 0.5),
        new(null, 280302, "Warehouse club memberships.",
            ["Wholesale club annual fee"],
            ["Charge is a warehouse club membership", "Direction is outflow"],
            [],
            ["COSTCO"], CharacteristicsDirection.Outflow, CharacteristicsAnalyticsTreatment.Expense, 0.7),
        new(null, 280303, "Professional associations.",
            ["Professional body membership"],
            ["Charge is a professional association fee", "Direction is outflow"],
            ["Union dues have their own node"],
            [], CharacteristicsDirection.Outflow, CharacteristicsAnalyticsTreatment.Expense, 0.5),
        new(null, 280304, "Loyalty and premium memberships.",
            ["Retail premium membership"],
            ["Charge is a loyalty or premium membership", "Direction is outflow"],
            [],
            ["AMAZON PRIME"], CharacteristicsDirection.Outflow, CharacteristicsAnalyticsTreatment.Expense, 0.7),
        new(null, 280305, "Club memberships.",
            ["Social or hobby club dues"],
            ["Charge is club membership", "Direction is outflow"],
            ["Sports club fees belong to Entertainment's sports"],
            [], CharacteristicsDirection.Outflow, CharacteristicsAnalyticsTreatment.Expense, 0.5),
        new(null, 280306, "Union and trade dues.",
            ["Monthly union subscription"],
            ["Charge is union or trade dues", "Direction is outflow"],
            [],
            ["UNION DUES", "SIPTU", "FORSA"], CharacteristicsDirection.Outflow, CharacteristicsAnalyticsTreatment.Expense, 0.75),

        // -- 28040 Recurring Plans & Boxes --
        new(28040, null, "Recurring plans that deliver something regularly.",
            ["Monthly box charge"],
            ["Charge is a recurring plan or box", "Direction is outflow"],
            [],
            [], CharacteristicsDirection.Outflow, CharacteristicsAnalyticsTreatment.Expense, 0.5),
        new(null, 280401, "Meal subscriptions tracked under subscriptions.",
            ["Meal plan when tracked as a subscription"],
            ["Charge is a recurring meal plan", "Direction is outflow"],
            ["Meal-kit brand signals resolve deterministically to Food & Dining's meal services"],
            [], CharacteristicsDirection.Outflow, CharacteristicsAnalyticsTreatment.Expense, 0.5),
        new(null, 280402, "Regular delivery boxes.",
            ["Recurring delivery of essentials"],
            ["Charge is a recurring delivery", "Direction is outflow"],
            [],
            [], CharacteristicsDirection.Outflow, CharacteristicsAnalyticsTreatment.Expense, 0.5),
        new(null, 280403, "App subscriptions.",
            ["Recurring app charge"],
            ["Charge is an app subscription", "Direction is outflow"],
            ["Store-level billing like Apple's is judged by what it bundles"],
            [], CharacteristicsDirection.Outflow, CharacteristicsAnalyticsTreatment.Expense, 0.5),
        new(null, 280404, "Gaming subscriptions tracked under subscriptions.",
            ["Gaming pass when tracked as a subscription"],
            ["Charge is a gaming subscription", "Direction is outflow"],
            ["Gaming platform signals resolve deterministically to Entertainment's gaming"],
            [], CharacteristicsDirection.Outflow, CharacteristicsAnalyticsTreatment.Expense, 0.5),
        new(null, 280405, "Dating app subscriptions.",
            ["Monthly dating app premium"],
            ["Charge is a dating app subscription", "Direction is outflow"],
            [],
            ["TINDER", "BUMBLE", "HINGE"], CharacteristicsDirection.Outflow, CharacteristicsAnalyticsTreatment.Expense, 0.8),

        // -- 28050 Other Subscriptions (real + catch-all) --
        new(28050, null, "Subscriptions that fit nowhere else; a human choice, never an AI guess.",
            ["Genuinely unclassifiable subscription"],
            ["Only deterministic rules or the user may assign this catch-all"],
            [],
            [], CharacteristicsDirection.Outflow, CharacteristicsAnalyticsTreatment.Expense, null),
        new(null, 280501, "Premium news.",
            ["Newspaper digital subscription"],
            ["Charge is a news subscription", "Direction is outflow"],
            [],
            ["IRISH TIMES", "SUBSTACK", "INDEPENDENT.IE"], CharacteristicsDirection.Outflow, CharacteristicsAnalyticsTreatment.Expense, 0.75),
        new(null, 280502, "Subscription boxes.",
            ["Curated monthly box"],
            ["Charge is a subscription box", "Direction is outflow"],
            [],
            [], CharacteristicsDirection.Outflow, CharacteristicsAnalyticsTreatment.Expense, 0.5),
        new(null, 280503, "Other recurring service subscriptions, user-assigned.",
            ["Recurring one-off with no better node"],
            ["Only deterministic rules or the user may assign this catch-all"],
            [],
            [], CharacteristicsDirection.Outflow, CharacteristicsAnalyticsTreatment.Expense, null),

        // -- 29010 Office & Admin --
        new(29010, null, "Running the business's admin side.",
            ["Office admin purchase"],
            ["Purchase is business office or admin", "Direction is outflow"],
            [],
            [], CharacteristicsDirection.Outflow, CharacteristicsAnalyticsTreatment.Expense, 0.5),
        new(null, 290101, "Office supplies.",
            ["Supplies for the office"],
            ["Purchase is business office supplies", "Direction is outflow"],
            [],
            ["OFFICE SUPPLIES"], CharacteristicsDirection.Outflow, CharacteristicsAnalyticsTreatment.Expense, 0.55),
        new(null, 290102, "Printing.",
            ["Print run for the business"],
            ["Charge is business printing", "Direction is outflow"],
            [],
            ["SNAP PRINTING"], CharacteristicsDirection.Outflow, CharacteristicsAnalyticsTreatment.Expense, 0.6),
        new(null, 290103, "Business stationery.",
            ["Letterheads and envelopes"],
            ["Purchase is business stationery", "Direction is outflow"],
            [],
            [], CharacteristicsDirection.Outflow, CharacteristicsAnalyticsTreatment.Expense, 0.5),
        new(null, 290104, "Coworking space.",
            ["Monthly desk membership"],
            ["Charge is coworking space", "Direction is outflow"],
            [],
            ["WEWORK", "COWORKING"], CharacteristicsDirection.Outflow, CharacteristicsAnalyticsTreatment.Expense, 0.7),
        new(null, 290105, "Office rent.",
            ["Rent for business premises"],
            ["Charge is business premises rent", "Direction is outflow"],
            ["Home rent belongs to Housing"],
            [], CharacteristicsDirection.Outflow, CharacteristicsAnalyticsTreatment.Expense, 0.5),
        new(null, 290106, "PO box rental.",
            ["Annual PO box"],
            ["Charge is a PO box", "Direction is outflow"],
            [],
            ["PO BOX"], CharacteristicsDirection.Outflow, CharacteristicsAnalyticsTreatment.Expense, 0.6),

        // -- 29020 Home Office --
        new(29020, null, "Equipping the home office for business use.",
            ["Home office purchase"],
            ["Purchase equips a home office for work", "Direction is outflow"],
            ["Personal electronics belong to Personal Shopping"],
            [], CharacteristicsDirection.Outflow, CharacteristicsAnalyticsTreatment.Expense, 0.5),
        new(null, 290201, "Desks and chairs.",
            ["Work desk and chair"],
            ["Purchase is home-office desk or chair", "Direction is outflow"],
            [],
            [], CharacteristicsDirection.Outflow, CharacteristicsAnalyticsTreatment.Expense, 0.5),
        new(null, 290202, "Monitors and peripherals.",
            ["Monitor for work"],
            ["Purchase is work monitors or peripherals", "Direction is outflow"],
            [],
            [], CharacteristicsDirection.Outflow, CharacteristicsAnalyticsTreatment.Expense, 0.5),
        new(null, 290203, "Printers, ink, and paper.",
            ["Ink refills for work"],
            ["Purchase is work printing supplies", "Direction is outflow"],
            [],
            [], CharacteristicsDirection.Outflow, CharacteristicsAnalyticsTreatment.Expense, 0.5),
        new(null, 290204, "Workspace furnishing.",
            ["Fitting out the workspace"],
            ["Purchase furnishes the workspace", "Direction is outflow"],
            [],
            [], CharacteristicsDirection.Outflow, CharacteristicsAnalyticsTreatment.Expense, 0.5),
        new(null, 290205, "Internet and utility allocation.",
            ["Business share of home internet"],
            ["Charge is the business share of home utilities", "Direction is outflow"],
            ["Full household bills belong to Utilities"],
            [], CharacteristicsDirection.Outflow, CharacteristicsAnalyticsTreatment.Expense, 0.5),
        new(null, 290206, "Home office supplies.",
            ["Small supplies for the home office"],
            ["Purchase is home-office supplies", "Direction is outflow"],
            [],
            [], CharacteristicsDirection.Outflow, CharacteristicsAnalyticsTreatment.Expense, 0.5),

        // -- 29030 Software & Services subs --
        new(null, 290301, "Accounting software.",
            ["Monthly bookkeeping software"],
            ["Charge is accounting software", "Direction is outflow"],
            [],
            ["XERO", "QUICKBOOKS", "SAGE"], CharacteristicsDirection.Outflow, CharacteristicsAnalyticsTreatment.Expense, 0.75),
        new(null, 290302, "CRM.",
            ["Monthly CRM seat"],
            ["Charge is CRM software", "Direction is outflow"],
            [],
            ["SALESFORCE", "HUBSPOT"], CharacteristicsDirection.Outflow, CharacteristicsAnalyticsTreatment.Expense, 0.75),
        new(null, 290303, "Design tools.",
            ["Design tool seat"],
            ["Charge is design software for the business", "Direction is outflow"],
            ["General creative subscriptions belong to Software & Digital Tools"],
            ["FIGMA"], CharacteristicsDirection.Outflow, CharacteristicsAnalyticsTreatment.Expense, 0.7),
        new(null, 290304, "Cloud services.",
            ["Monthly cloud infrastructure bill"],
            ["Charge is cloud infrastructure", "Direction is outflow"],
            [],
            ["AMAZON WEB SERVICES", "AWS EMEA", "AZURE", "DIGITALOCEAN", "HETZNER"], CharacteristicsDirection.Outflow, CharacteristicsAnalyticsTreatment.Expense, 0.75),
        new(null, 290305, "Website hosting.",
            ["Monthly hosting plan"],
            ["Charge is website hosting or a site builder", "Direction is outflow"],
            [],
            ["SQUARESPACE", "WIX.COM", "HOSTING"], CharacteristicsDirection.Outflow, CharacteristicsAnalyticsTreatment.Expense, 0.7),
        new(null, 290306, "Email services.",
            ["Email marketing platform"],
            ["Charge is email services", "Direction is outflow"],
            [],
            ["MAILCHIMP"], CharacteristicsDirection.Outflow, CharacteristicsAnalyticsTreatment.Expense, 0.7),
        new(null, 290307, "Domain names.",
            ["Annual domain renewal"],
            ["Charge is domain registration", "Direction is outflow"],
            [],
            ["GODADDY", "BLACKNIGHT", "NAMECHEAP"], CharacteristicsDirection.Outflow, CharacteristicsAnalyticsTreatment.Expense, 0.75),

        // -- 29040 Marketing & Sales --
        new(29040, null, "Getting the business seen and sold.",
            ["Marketing spend"],
            ["Charge is business marketing", "Direction is outflow"],
            [],
            [], CharacteristicsDirection.Outflow, CharacteristicsAnalyticsTreatment.Expense, 0.5),
        new(null, 290401, "Advertising.",
            ["Ad platform invoice"],
            ["Charge is advertising", "Direction is outflow"],
            [],
            ["GOOGLE ADS", "META ADS"], CharacteristicsDirection.Outflow, CharacteristicsAnalyticsTreatment.Expense, 0.75),
        new(null, 290402, "Social media ads.",
            ["Boosted posts"],
            ["Charge is social media advertising", "Direction is outflow"],
            [],
            [], CharacteristicsDirection.Outflow, CharacteristicsAnalyticsTreatment.Expense, 0.5),
        new(null, 290403, "Branding.",
            ["Logo and brand work"],
            ["Charge is branding work", "Direction is outflow"],
            [],
            [], CharacteristicsDirection.Outflow, CharacteristicsAnalyticsTreatment.Expense, 0.5),
        new(null, 290404, "Business cards.",
            ["Card print order"],
            ["Charge is business cards", "Direction is outflow"],
            [],
            ["VISTAPRINT", "MOO.COM"], CharacteristicsDirection.Outflow, CharacteristicsAnalyticsTreatment.Expense, 0.7),
        new(null, 290405, "Events and trade shows.",
            ["Stand at a trade show"],
            ["Charge is business events", "Direction is outflow"],
            [],
            [], CharacteristicsDirection.Outflow, CharacteristicsAnalyticsTreatment.Expense, 0.5),
        new(null, 290406, "Client gifts.",
            ["Gift for a client"],
            ["Purchase is a client gift", "Direction is outflow"],
            ["Personal gifts belong to Gifts & Donations"],
            [], CharacteristicsDirection.Outflow, CharacteristicsAnalyticsTreatment.Expense, 0.5),
        new(null, 290407, "Lead generation.",
            ["Lead platform fee"],
            ["Charge is lead generation", "Direction is outflow"],
            [],
            [], CharacteristicsDirection.Outflow, CharacteristicsAnalyticsTreatment.Expense, 0.5),

        // -- 29050 Professional Services --
        new(29050, null, "People the business hires.",
            ["Professional service invoice"],
            ["Charge is business professional services", "Direction is outflow"],
            ["Personal legal and advice belong to Legal & Professional Fees"],
            [], CharacteristicsDirection.Outflow, CharacteristicsAnalyticsTreatment.Expense, 0.5),
        new(null, 290501, "Accountant.",
            ["Year-end accounts"],
            ["Charge is business accounting", "Direction is outflow"],
            [],
            [], CharacteristicsDirection.Outflow, CharacteristicsAnalyticsTreatment.Expense, 0.5),
        new(null, 290502, "Bookkeeper.",
            ["Monthly bookkeeping"],
            ["Charge is bookkeeping", "Direction is outflow"],
            [],
            [], CharacteristicsDirection.Outflow, CharacteristicsAnalyticsTreatment.Expense, 0.5),
        new(null, 290503, "Lawyer for the business.",
            ["Contract review"],
            ["Charge is business legal work", "Direction is outflow"],
            [],
            [], CharacteristicsDirection.Outflow, CharacteristicsAnalyticsTreatment.Expense, 0.5),
        new(null, 290504, "Consultant.",
            ["Consulting engagement"],
            ["Charge is business consulting", "Direction is outflow"],
            [],
            [], CharacteristicsDirection.Outflow, CharacteristicsAnalyticsTreatment.Expense, 0.5),
        new(null, 290505, "Virtual assistant.",
            ["VA hours"],
            ["Charge is virtual assistance", "Direction is outflow"],
            [],
            [], CharacteristicsDirection.Outflow, CharacteristicsAnalyticsTreatment.Expense, 0.5),
        new(null, 290506, "Contractor payments.",
            ["Paying a subcontractor"],
            ["Payment is to a business contractor", "Direction is outflow"],
            [],
            [], CharacteristicsDirection.Outflow, CharacteristicsAnalyticsTreatment.Expense, 0.5),

        // -- 29060 Equipment & Operations --
        new(29060, null, "The gear and upkeep the business runs on.",
            ["Equipment purchase"],
            ["Purchase is business equipment or operations", "Direction is outflow"],
            [],
            [], CharacteristicsDirection.Outflow, CharacteristicsAnalyticsTreatment.Expense, 0.5),
        new(null, 290601, "Computer equipment for the business.",
            ["Work machine upgrade"],
            ["Purchase is business computer equipment", "Direction is outflow"],
            ["Personal devices belong to Personal Shopping's electronics"],
            [], CharacteristicsDirection.Outflow, CharacteristicsAnalyticsTreatment.Expense, 0.5),
        new(null, 290602, "Camera and audio equipment.",
            ["Content production gear"],
            ["Purchase is business camera or audio gear", "Direction is outflow"],
            [],
            [], CharacteristicsDirection.Outflow, CharacteristicsAnalyticsTreatment.Expense, 0.5),
        new(null, 290603, "Office furniture.",
            ["Fitting out the office"],
            ["Purchase is business office furniture", "Direction is outflow"],
            [],
            [], CharacteristicsDirection.Outflow, CharacteristicsAnalyticsTreatment.Expense, 0.5),
        new(null, 290604, "Tools and machinery.",
            ["Trade tools for the business"],
            ["Purchase is business tools or machinery", "Direction is outflow"],
            ["Home DIY tools belong to Home & Garden"],
            [], CharacteristicsDirection.Outflow, CharacteristicsAnalyticsTreatment.Expense, 0.5),
        new(null, 290605, "Business repairs and maintenance.",
            ["Equipment repair"],
            ["Charge repairs business equipment", "Direction is outflow"],
            [],
            [], CharacteristicsDirection.Outflow, CharacteristicsAnalyticsTreatment.Expense, 0.5),
        new(null, 290606, "Shipping and postage.",
            ["Courier for a customer order"],
            ["Charge is business shipping", "Direction is outflow"],
            [],
            ["DPD", "GLS", "FASTWAY"], CharacteristicsDirection.Outflow, CharacteristicsAnalyticsTreatment.Expense, 0.6),

        // -- 29070 Travel & Client Costs --
        new(29070, null, "Being where the business needs you.",
            ["Business trip cost"],
            ["Charge is business travel or client costs", "Direction is outflow"],
            ["Personal trips belong to Travel"],
            [], CharacteristicsDirection.Outflow, CharacteristicsAnalyticsTreatment.Expense, 0.5),
        new(null, 290701, "Client meals.",
            ["Lunch with a client"],
            ["Charge is a client meal", "Direction is outflow"],
            ["Personal dining belongs to Food & Dining"],
            [], CharacteristicsDirection.Outflow, CharacteristicsAnalyticsTreatment.Expense, 0.5),
        new(null, 290702, "Business travel.",
            ["Flight to a client site"],
            ["Charge is business travel", "Direction is outflow"],
            [],
            [], CharacteristicsDirection.Outflow, CharacteristicsAnalyticsTreatment.Expense, 0.5),
        new(null, 290703, "Mileage.",
            ["Mileage claim cost"],
            ["Charge is business mileage", "Direction is outflow"],
            [],
            [], CharacteristicsDirection.Outflow, CharacteristicsAnalyticsTreatment.Expense, 0.5),
        new(null, 290704, "Conferences.",
            ["Conference ticket"],
            ["Charge is a business conference", "Direction is outflow"],
            [],
            [], CharacteristicsDirection.Outflow, CharacteristicsAnalyticsTreatment.Expense, 0.5),
        new(null, 290705, "Business lodging.",
            ["Hotel on a work trip"],
            ["Charge is business lodging", "Direction is outflow"],
            ["Holiday stays belong to Travel"],
            [], CharacteristicsDirection.Outflow, CharacteristicsAnalyticsTreatment.Expense, 0.5),
        new(null, 290706, "Taxis for business.",
            ["Taxi to a meeting"],
            ["Charge is business taxis", "Direction is outflow"],
            ["Personal rides belong to Transportation"],
            [], CharacteristicsDirection.Outflow, CharacteristicsAnalyticsTreatment.Expense, 0.5),

        // -- 29080 Taxes & Compliance --
        new(29080, null, "Keeping the business compliant.",
            ["Compliance charge"],
            ["Charge is business compliance", "Direction is outflow"],
            [],
            [], CharacteristicsDirection.Outflow, CharacteristicsAnalyticsTreatment.Expense, 0.5),
        new(null, 290801, "Business registration fees.",
            ["Annual return filing"],
            ["Charge registers or maintains the business", "Direction is outflow"],
            [],
            ["COMPANIES REGISTRATION"], CharacteristicsDirection.Outflow, CharacteristicsAnalyticsTreatment.Expense, 0.6),
        new(null, 290802, "Licenses and permits.",
            ["Trade licence renewal"],
            ["Charge is a business licence", "Direction is outflow"],
            [],
            [], CharacteristicsDirection.Outflow, CharacteristicsAnalyticsTreatment.Expense, 0.5),
        new(null, 290803, "VAT and sales tax tracked in the business.",
            ["VAT when tracked as business spend"],
            ["Charge is business VAT", "Direction is outflow"],
            ["VAT payment signals resolve deterministically to Taxes"],
            [], CharacteristicsDirection.Outflow, CharacteristicsAnalyticsTreatment.Expense, 0.5),
        new(null, 290804, "Payroll services.",
            ["Payroll provider fee"],
            ["Charge is payroll services", "Direction is outflow"],
            [],
            [], CharacteristicsDirection.Outflow, CharacteristicsAnalyticsTreatment.Expense, 0.5),
        new(null, 290805, "Business insurance.",
            ["Liability cover premium"],
            ["Charge is business insurance", "Direction is outflow"],
            ["Personal insurer brands resolve deterministically to Insurance"],
            [], CharacteristicsDirection.Outflow, CharacteristicsAnalyticsTreatment.Expense, 0.5),

        // -- 29090 Other Business Expenses (real + catch-all) --
        new(29090, null, "Business costs that fit nowhere else; a human choice, never an AI guess.",
            ["Genuinely unclassifiable business expense"],
            ["Only deterministic rules or the user may assign this catch-all"],
            [],
            [], CharacteristicsDirection.Outflow, CharacteristicsAnalyticsTreatment.Expense, null),
        new(null, 290901, "Business bank fees.",
            ["Business account charges"],
            ["Charge is business bank fees", "Direction is outflow"],
            ["Personal account fees belong to Banking & Account Fees"],
            [], CharacteristicsDirection.Outflow, CharacteristicsAnalyticsTreatment.Expense, 0.5),
        new(null, 290902, "Merchant fees.",
            ["Card processing fees"],
            ["Charge is merchant processing fees", "Direction is outflow"],
            [],
            ["MERCHANT FEE"], CharacteristicsDirection.Outflow, CharacteristicsAnalyticsTreatment.Expense, 0.55),
        new(null, 290903, "Chargebacks and refund losses.",
            ["Chargeback against the business"],
            ["Charge is a chargeback or refund loss", "Direction is outflow"],
            [],
            ["CHARGEBACK"], CharacteristicsDirection.Outflow, CharacteristicsAnalyticsTreatment.Expense, 0.55),
        new(null, 290904, "Miscellaneous business costs, user-assigned.",
            ["Business one-off with no better node"],
            ["Only deterministic rules or the user may assign this catch-all"],
            [],
            [], CharacteristicsDirection.Outflow, CharacteristicsAnalyticsTreatment.Expense, null)
    ];
}
