namespace NSFinance.Shared.Taxonomy;

// Full-coverage characteristics: Insurance (150) subcategories.
// "Other Insurance" holds real cost shapes (deductibles, co-pays) that get
// proper definitions; only the true catch-all is deterministic-only.
public static partial class CategoryCharacteristicsCatalog
{
    private static readonly IReadOnlyList<CategoryCharacteristicsDefinition> InsuranceSubcategoryDefinitions =
    [
        // -- 15010 Health Insurance --
        new(null, 150101, "The core health insurance premium.",
            ["Monthly health premium"],
            ["Charge is a health insurance premium", "Direction is outflow"],
            [],
            [], CharacteristicsDirection.Outflow, CharacteristicsAnalyticsTreatment.Expense, 0.6),
        new(null, 150102, "Dental insurance premiums.",
            ["Dental plan premium"],
            ["Charge is dental insurance", "Direction is outflow"],
            ["Dental treatment itself belongs to Dental Care"],
            ["DENTAL INSURANCE", "DECARE"], CharacteristicsDirection.Outflow, CharacteristicsAnalyticsTreatment.Expense, 0.7),
        new(null, 150103, "Vision insurance premiums.",
            ["Vision plan premium"],
            ["Charge is vision insurance", "Direction is outflow"],
            [],
            [], CharacteristicsDirection.Outflow, CharacteristicsAnalyticsTreatment.Expense, 0.55),
        new(null, 150104, "Supplemental medical policies: hospital cash, top-ups.",
            ["Hospital cash plan premium"],
            ["Charge is supplemental medical cover", "Direction is outflow"],
            [],
            ["HSF HEALTH"], CharacteristicsDirection.Outflow, CharacteristicsAnalyticsTreatment.Expense, 0.6),
        new(null, 150105, "Travel medical insurance bought separately from a trip policy.",
            ["Medical-only travel policy"],
            ["Charge is travel medical cover", "Direction is outflow"],
            ["Full travel policies belong to Travel Insurance"],
            [], CharacteristicsDirection.Outflow, CharacteristicsAnalyticsTreatment.Expense, 0.5),

        // -- 15020 Life & Disability --
        new(null, 150201, "Life insurance premiums.",
            ["Term life premium"],
            ["Charge is life insurance", "Direction is outflow"],
            ["Mortgage-linked protection belongs to Mortgage Insurance"],
            ["LIFE INSURANCE"], CharacteristicsDirection.Outflow, CharacteristicsAnalyticsTreatment.Expense, 0.6),
        new(null, 150202, "Disability insurance premiums.",
            ["Disability cover premium"],
            ["Charge is disability insurance", "Direction is outflow"],
            [],
            [], CharacteristicsDirection.Outflow, CharacteristicsAnalyticsTreatment.Expense, 0.55),
        new(null, 150203, "Income protection premiums.",
            ["Income protection direct debit"],
            ["Charge is income protection", "Direction is outflow"],
            [],
            ["INCOME PROTECTION"], CharacteristicsDirection.Outflow, CharacteristicsAnalyticsTreatment.Expense, 0.65),
        new(null, 150204, "Critical or serious illness cover.",
            ["Serious illness premium"],
            ["Charge is critical illness cover", "Direction is outflow"],
            [],
            ["SERIOUS ILLNESS"], CharacteristicsDirection.Outflow, CharacteristicsAnalyticsTreatment.Expense, 0.6),
        new(null, 150205, "Funeral or over-50s plans.",
            ["Over-50s plan premium"],
            ["Charge is funeral insurance", "Direction is outflow"],
            ["Funeral costs themselves belong to Ceremonies & Events"],
            ["FUNERAL PLAN"], CharacteristicsDirection.Outflow, CharacteristicsAnalyticsTreatment.Expense, 0.65),

        // -- 15030 Home & Property Insurance --
        new(null, 150301, "Homeowner buildings policies.",
            ["Annual buildings premium"],
            ["Charge is homeowners insurance", "Direction is outflow"],
            [],
            [], CharacteristicsDirection.Outflow, CharacteristicsAnalyticsTreatment.Expense, 0.55),
        new(null, 150302, "Renters policies.",
            ["Renter contents premium"],
            ["Charge is renters insurance", "Direction is outflow"],
            [],
            [], CharacteristicsDirection.Outflow, CharacteristicsAnalyticsTreatment.Expense, 0.55),
        new(null, 150303, "Landlord policies on let property.",
            ["Landlord policy premium"],
            ["Charge is landlord insurance", "Direction is outflow"],
            [],
            ["LANDLORD INSURANCE"], CharacteristicsDirection.Outflow, CharacteristicsAnalyticsTreatment.Expense, 0.6),
        new(null, 150304, "Contents-only policies.",
            ["Contents cover premium"],
            ["Charge is contents insurance", "Direction is outflow"],
            [],
            ["CONTENTS INSURANCE"], CharacteristicsDirection.Outflow, CharacteristicsAnalyticsTreatment.Expense, 0.6),
        new(null, 150305, "Flood-specific cover.",
            ["Flood policy premium"],
            ["Charge is flood insurance", "Direction is outflow"],
            [],
            [], CharacteristicsDirection.Outflow, CharacteristicsAnalyticsTreatment.Expense, 0.5),
        new(null, 150306, "Disaster or catastrophe cover.",
            ["Catastrophe rider premium"],
            ["Charge is disaster cover", "Direction is outflow"],
            [],
            [], CharacteristicsDirection.Outflow, CharacteristicsAnalyticsTreatment.Expense, 0.5),

        // -- 15040 Vehicle Insurance (150401 Car Insurance already defined) --
        new(null, 150402, "Motorbike policies.",
            ["Motorcycle premium"],
            ["Charge is motorcycle insurance", "Direction is outflow"],
            [],
            ["MOTORCYCLE INSURANCE", "BIKE INSURANCE"], CharacteristicsDirection.Outflow, CharacteristicsAnalyticsTreatment.Expense, 0.6),
        new(null, 150403, "Commercial vehicle policies.",
            ["Van policy premium"],
            ["Charge is commercial vehicle insurance", "Direction is outflow"],
            [],
            ["VAN INSURANCE"], CharacteristicsDirection.Outflow, CharacteristicsAnalyticsTreatment.Expense, 0.55),
        new(null, 150404, "Standalone breakdown cover sold as insurance.",
            ["Breakdown add-on premium"],
            ["Charge is breakdown cover sold with insurance", "Direction is outflow"],
            ["Motoring-club memberships belong to Breakdown / Roadside Assistance"],
            [], CharacteristicsDirection.Outflow, CharacteristicsAnalyticsTreatment.Expense, 0.5),
        new(null, 150405, "Windscreen cover add-ons.",
            ["Windscreen cover line"],
            ["Charge is windscreen cover", "Direction is outflow"],
            [],
            [], CharacteristicsDirection.Outflow, CharacteristicsAnalyticsTreatment.Expense, 0.5),

        // -- 15050 Travel & Event Insurance --
        new(null, 150501, "Trip travel insurance.",
            ["Single or multi-trip policy"],
            ["Charge is travel insurance", "Direction is outflow"],
            [],
            ["TRAVEL INSURANCE"], CharacteristicsDirection.Outflow, CharacteristicsAnalyticsTreatment.Expense, 0.65),
        new(null, 150502, "Flight-specific insurance at checkout.",
            ["Flight cover add-on"],
            ["Charge is flight insurance", "Direction is outflow"],
            [],
            [], CharacteristicsDirection.Outflow, CharacteristicsAnalyticsTreatment.Expense, 0.5),
        new(null, 150503, "Event insurance.",
            ["Event liability cover"],
            ["Charge insures an event", "Direction is outflow"],
            [],
            [], CharacteristicsDirection.Outflow, CharacteristicsAnalyticsTreatment.Expense, 0.5),
        new(null, 150504, "Wedding insurance.",
            ["Wedding policy premium"],
            ["Charge is wedding insurance", "Direction is outflow"],
            [],
            ["WEDDING INSURANCE"], CharacteristicsDirection.Outflow, CharacteristicsAnalyticsTreatment.Expense, 0.6),
        new(null, 150505, "Ticket protection at checkout.",
            ["Ticket refund protection"],
            ["Charge is ticket protection", "Direction is outflow"],
            [],
            [], CharacteristicsDirection.Outflow, CharacteristicsAnalyticsTreatment.Expense, 0.5),

        // -- 15060 Pet & Other Insurance (150601 via category def signals) --
        new(null, 150601, "Pet policies.",
            ["Dog policy premium"],
            ["Charge is pet insurance", "Direction is outflow"],
            [],
            [], CharacteristicsDirection.Outflow, CharacteristicsAnalyticsTreatment.Expense, 0.55),
        new(null, 150602, "Gadget and device cover.",
            ["Phone insurance premium"],
            ["Charge is device insurance", "Direction is outflow"],
            [],
            ["GADGET INSURANCE", "PHONE INSURANCE"], CharacteristicsDirection.Outflow, CharacteristicsAnalyticsTreatment.Expense, 0.6),
        new(null, 150603, "Identity theft protection subscriptions.",
            ["ID protection plan"],
            ["Charge is identity protection", "Direction is outflow"],
            [],
            [], CharacteristicsDirection.Outflow, CharacteristicsAnalyticsTreatment.Expense, 0.5),
        new(null, 150604, "Legal protection policies.",
            ["Legal expenses cover"],
            ["Charge is legal protection insurance", "Direction is outflow"],
            [],
            [], CharacteristicsDirection.Outflow, CharacteristicsAnalyticsTreatment.Expense, 0.5),

        // -- 15070 Other Insurance (real cost shapes + catch-all) --
        new(15070, null, "Insurance costs that fit nowhere else; a human choice, never an AI guess.",
            ["Genuinely unclassifiable insurance expense"],
            ["Only deterministic rules or the user may assign this catch-all"],
            [],
            [], CharacteristicsDirection.Outflow, CharacteristicsAnalyticsTreatment.Expense, null),
        new(null, 150701, "Insurance deductibles and excesses you pay on a claim.",
            ["Policy excess on a claim"],
            ["Payment is a claim excess", "Direction is outflow"],
            [],
            [], CharacteristicsDirection.Outflow, CharacteristicsAnalyticsTreatment.Expense, 0.5),
        new(null, 150702, "Insurance co-pays.",
            ["Co-pay under a policy"],
            ["Payment is an insurance co-pay", "Direction is outflow"],
            [],
            [], CharacteristicsDirection.Outflow, CharacteristicsAnalyticsTreatment.Expense, 0.5),
        new(null, 150703, "Other insurance costs, user-assigned.",
            ["Insurance one-off with no better node"],
            ["Only deterministic rules or the user may assign this catch-all"],
            [],
            [], CharacteristicsDirection.Outflow, CharacteristicsAnalyticsTreatment.Expense, null)
    ];
}
