namespace NSFinance.Shared.Taxonomy;

// Full-coverage characteristics: Transportation (120) subcategories.
public static partial class CategoryCharacteristicsCatalog
{
    private static readonly IReadOnlyList<CategoryCharacteristicsDefinition> TransportationSubcategoryDefinitions =
    [
        // -- 12010 Public Transport (120108 Taxi already defined in core) --
        new(null, 120101, "Bus fares: city and local buses.",
            ["Single or daily bus fare"],
            ["Fare is a bus journey", "Direction is outflow"],
            ["Intercity coaches belong to Long-Distance Transport"],
            ["DUBLIN BUS", "BUS EIREANN", "GO-AHEAD"], CharacteristicsDirection.Outflow, CharacteristicsAnalyticsTreatment.Expense, 0.75),
        new(null, 120102, "Train fares: commuter and DART.",
            ["DART or commuter ticket"],
            ["Fare is a commuter rail journey", "Direction is outflow"],
            ["Intercity rail belongs to Long-Distance Transport"],
            ["IRISH RAIL", "IARNROD EIREANN"], CharacteristicsDirection.Outflow, CharacteristicsAnalyticsTreatment.Expense, 0.75),
        new(null, 120103, "Tram fares: Luas and equivalents.",
            ["Luas ticket"],
            ["Fare is a tram or light-rail journey", "Direction is outflow"],
            [],
            ["LUAS"], CharacteristicsDirection.Outflow, CharacteristicsAnalyticsTreatment.Expense, 0.8),
        new(null, 120104, "Metro and subway fares abroad.",
            ["Metro ticket on a city break"],
            ["Fare is a metro or subway journey", "Direction is outflow"],
            [],
            [], CharacteristicsDirection.Outflow, CharacteristicsAnalyticsTreatment.Expense, 0.6),
        new(null, 120105, "Commuter ferry fares.",
            ["Short ferry hop"],
            ["Fare is a local ferry crossing", "Direction is outflow"],
            ["Car-and-passenger sailings belong to Long-Distance Transport"],
            [], CharacteristicsDirection.Outflow, CharacteristicsAnalyticsTreatment.Expense, 0.55),
        new(null, 120106, "Transit passes and top-ups: Leap card and equivalents.",
            ["Leap card top-up"],
            ["Payment loads or buys a transit pass", "Direction is outflow"],
            [],
            ["LEAP CARD", "LEAPCARD", "LEAP"], CharacteristicsDirection.Outflow, CharacteristicsAnalyticsTreatment.Expense, 0.75),
        new(null, 120107, "Park & Ride: combined parking and transit.",
            ["Park & Ride day fee"],
            ["Charge is a park-and-ride facility", "Direction is outflow"],
            [],
            ["PARK & RIDE", "PARK AND RIDE"], CharacteristicsDirection.Outflow, CharacteristicsAnalyticsTreatment.Expense, 0.7),

        // -- 12020 Fuel & Charging --
        new(null, 120201, "Petrol fills.",
            ["Petrol fill-up"],
            ["Purchase is petrol", "Direction is outflow"],
            ["Shop items at the till belong to Fuel Station Convenience Purchases"],
            [], CharacteristicsDirection.Outflow, CharacteristicsAnalyticsTreatment.Expense, 0.6),
        new(null, 120202, "Diesel fills.",
            ["Diesel fill-up"],
            ["Purchase is diesel", "Direction is outflow"],
            [],
            [], CharacteristicsDirection.Outflow, CharacteristicsAnalyticsTreatment.Expense, 0.6),
        new(null, 120203, "EV charging: public networks and pay-per-charge.",
            ["Public charge point session"],
            ["Purchase is electric vehicle charging", "Direction is outflow"],
            ["Home electricity belongs to Electricity"],
            ["ESB ECARS", "IONITY", "EASYGO"], CharacteristicsDirection.Outflow, CharacteristicsAnalyticsTreatment.Expense, 0.75),
        new(null, 120204, "AdBlue and vehicle fluids at the pump.",
            ["AdBlue top-up"],
            ["Purchase is AdBlue or fluids", "Direction is outflow"],
            [],
            ["ADBLUE"], CharacteristicsDirection.Outflow, CharacteristicsAnalyticsTreatment.Expense, 0.7),
        new(null, 120205, "The shop at the fuel station: snacks and sundries with the fill.",
            ["Coffee and a snack at the till"],
            ["Purchase is fuel-station shop goods rather than fuel", "Direction is outflow"],
            ["Fuel itself belongs to the fuel subcategories"],
            [], CharacteristicsDirection.Outflow, CharacteristicsAnalyticsTreatment.Expense, 0.5),

        // -- 12030 Car Ownership --
        new(null, 120301, "Car loan repayments identified as such.",
            ["Monthly car finance payment"],
            ["Payment services a car loan", "Direction is outflow"],
            ["Loan interest analytics live with Debt & Loans; this node records the spend view"],
            [], CharacteristicsDirection.Outflow, CharacteristicsAnalyticsTreatment.Expense, 0.6),
        new(null, 120302, "Car lease or PCP payments.",
            ["Monthly lease instalment"],
            ["Payment is a vehicle lease or PCP", "Direction is outflow"],
            [],
            [], CharacteristicsDirection.Outflow, CharacteristicsAnalyticsTreatment.Expense, 0.6),
        new(null, 120303, "Registering a vehicle: first registration, plates.",
            ["Registration plates made up"],
            ["Charge registers the vehicle", "Direction is outflow"],
            [],
            [], CharacteristicsDirection.Outflow, CharacteristicsAnalyticsTreatment.Expense, 0.6),
        new(null, 120304, "Motor tax.",
            ["Annual motor tax"],
            ["Charge is motor tax", "Direction is outflow"],
            [],
            [], CharacteristicsDirection.Outflow, CharacteristicsAnalyticsTreatment.Expense, 0.7),
        new(null, 120305, "The NCT or MOT test fee.",
            ["NCT booking fee"],
            ["Charge is the vehicle inspection test", "Direction is outflow"],
            ["Repairs to pass belong to Car Maintenance"],
            [], CharacteristicsDirection.Outflow, CharacteristicsAnalyticsTreatment.Expense, 0.7),
        new(null, 120306, "Residential or workplace parking permits.",
            ["Annual residents' parking permit"],
            ["Charge is a parking permit", "Direction is outflow"],
            ["Pay-per-use parking belongs to Parking & Tolls"],
            ["PARKING PERMIT"], CharacteristicsDirection.Outflow, CharacteristicsAnalyticsTreatment.Expense, 0.7),
        new(null, 120307, "Toll tags and devices: tag rental and account fees.",
            ["Toll tag monthly fee"],
            ["Charge is a toll tag or device fee", "Direction is outflow"],
            ["Per-trip tolls belong to Tolls"],
            ["TOLLTAG", "TOLL TAG"], CharacteristicsDirection.Outflow, CharacteristicsAnalyticsTreatment.Expense, 0.7),

        // -- 12040 Car Maintenance & Repairs --
        new(null, 120401, "Scheduled servicing.",
            ["Annual service"],
            ["Work is a routine service", "Direction is outflow"],
            [],
            [], CharacteristicsDirection.Outflow, CharacteristicsAnalyticsTreatment.Expense, 0.6),
        new(null, 120402, "Tyres: supply and fitting.",
            ["Two new tyres fitted"],
            ["Purchase is tyres", "Direction is outflow"],
            [],
            ["TYRE", "TYRES"], CharacteristicsDirection.Outflow, CharacteristicsAnalyticsTreatment.Expense, 0.7),
        new(null, 120403, "Brakes: pads, discs, work.",
            ["Brake pads replaced"],
            ["Work is brake repair", "Direction is outflow"],
            [],
            [], CharacteristicsDirection.Outflow, CharacteristicsAnalyticsTreatment.Expense, 0.6),
        new(null, 120404, "Oil changes outside a full service.",
            ["Quick oil change"],
            ["Work is an oil change", "Direction is outflow"],
            [],
            [], CharacteristicsDirection.Outflow, CharacteristicsAnalyticsTreatment.Expense, 0.55),
        new(null, 120405, "Car battery replacement.",
            ["New battery fitted"],
            ["Purchase replaces the vehicle battery", "Direction is outflow"],
            [],
            [], CharacteristicsDirection.Outflow, CharacteristicsAnalyticsTreatment.Expense, 0.55),
        new(null, 120406, "Bodywork: dents, resprays, panels.",
            ["Dent repair and respray"],
            ["Work is body repair", "Direction is outflow"],
            [],
            ["BODYWORKS", "CRASH REPAIR"], CharacteristicsDirection.Outflow, CharacteristicsAnalyticsTreatment.Expense, 0.65),
        new(null, 120407, "Windscreens and glass.",
            ["Chip repair or windscreen replacement"],
            ["Work is vehicle glass", "Direction is outflow"],
            [],
            ["AUTOGLASS", "WINDSCREEN"], CharacteristicsDirection.Outflow, CharacteristicsAnalyticsTreatment.Expense, 0.75),
        new(null, 120408, "Breakdown and roadside assistance: memberships and call-outs.",
            ["AA membership renewal", "Tow after a breakdown"],
            ["Charge is breakdown cover or roadside assistance", "Direction is outflow"],
            [],
            ["AA IRELAND", "AA MEMBERSHIP", "ROADSIDE"], CharacteristicsDirection.Outflow, CharacteristicsAnalyticsTreatment.Expense, 0.7),
        new(null, 120409, "Parts and accessories you buy: wipers, mats, bulbs.",
            ["Wiper blades and mats"],
            ["Goods are vehicle parts or accessories", "Direction is outflow"],
            [],
            ["MICKS GARAGE", "AGRI PARTS"], CharacteristicsDirection.Outflow, CharacteristicsAnalyticsTreatment.Expense, 0.6),
        new(null, 120410, "Car washing and valeting.",
            ["Drive-through wash", "Full valet"],
            ["Service washes or valets the car", "Direction is outflow"],
            [],
            ["CAR WASH", "CARWASH", "VALET"], CharacteristicsDirection.Outflow, CharacteristicsAnalyticsTreatment.Expense, 0.7),

        // -- 12050 Parking & Tolls --
        new(null, 120501, "Street parking: meters and apps for on-street spots.",
            ["Hour of on-street parking"],
            ["Charge is on-street parking", "Direction is outflow"],
            [],
            [], CharacteristicsDirection.Outflow, CharacteristicsAnalyticsTreatment.Expense, 0.6),
        new(null, 120502, "Car parks: multi-storey and surface garages.",
            ["Shopping-centre car park"],
            ["Charge is an off-street car park", "Direction is outflow"],
            [],
            [], CharacteristicsDirection.Outflow, CharacteristicsAnalyticsTreatment.Expense, 0.6),
        new(null, 120503, "Per-trip road tolls.",
            ["M50 toll payment"],
            ["Charge is a road toll", "Direction is outflow"],
            ["Tag account fees belong to Toll Tags / Devices"],
            [], CharacteristicsDirection.Outflow, CharacteristicsAnalyticsTreatment.Expense, 0.65),
        new(null, 120504, "Congestion and clean-air zone charges abroad.",
            ["City congestion charge on a trip"],
            ["Charge is a congestion or zone fee", "Direction is outflow"],
            [],
            ["CONGESTION CHARGE"], CharacteristicsDirection.Outflow, CharacteristicsAnalyticsTreatment.Expense, 0.7),
        new(null, 120505, "Traffic and parking fines.",
            ["Fixed-charge parking fine"],
            ["Charge is a traffic or parking penalty", "Direction is outflow"],
            [],
            ["FIXED CHARGE NOTICE"], CharacteristicsDirection.Outflow, CharacteristicsAnalyticsTreatment.Expense, 0.65),
        new(null, 120506, "Clamping and towing release fees.",
            ["Clamp release payment"],
            ["Charge releases a clamped or towed vehicle", "Direction is outflow"],
            [],
            ["CLAMPING"], CharacteristicsDirection.Outflow, CharacteristicsAnalyticsTreatment.Expense, 0.7),

        // -- 12060 Cycling & Micro-Mobility --
        new(null, 120601, "Buying a bike.",
            ["New bike purchase"],
            ["Purchase is a bicycle", "Direction is outflow"],
            [],
            [], CharacteristicsDirection.Outflow, CharacteristicsAnalyticsTreatment.Expense, 0.6),
        new(null, 120602, "Bike repairs and servicing.",
            ["Puncture fix and tune-up"],
            ["Service repairs a bicycle", "Direction is outflow"],
            [],
            ["BIKE REPAIR", "CYCLE REPAIR"], CharacteristicsDirection.Outflow, CharacteristicsAnalyticsTreatment.Expense, 0.65),
        new(null, 120603, "Bike accessories: lights, locks, panniers.",
            ["Lights and a lock"],
            ["Goods are bicycle accessories", "Direction is outflow"],
            ["Helmets belong to Helmet / Safety Gear"],
            [], CharacteristicsDirection.Outflow, CharacteristicsAnalyticsTreatment.Expense, 0.55),
        new(null, 120604, "Shared bike schemes.",
            ["Bike-share ride or subscription"],
            ["Charge is a shared-bike scheme", "Direction is outflow"],
            [],
            [], CharacteristicsDirection.Outflow, CharacteristicsAnalyticsTreatment.Expense, 0.6),
        new(null, 120605, "Shared e-scooter rides.",
            ["E-scooter ride"],
            ["Charge is a scooter-share ride", "Direction is outflow"],
            [],
            [], CharacteristicsDirection.Outflow, CharacteristicsAnalyticsTreatment.Expense, 0.6),
        new(null, 120606, "Owning a scooter: purchase and repairs.",
            ["E-scooter purchase"],
            ["Purchase or repair is a personal scooter", "Direction is outflow"],
            [],
            [], CharacteristicsDirection.Outflow, CharacteristicsAnalyticsTreatment.Expense, 0.55),
        new(null, 120607, "Helmets and safety gear.",
            ["New helmet"],
            ["Goods are cycling safety gear", "Direction is outflow"],
            [],
            [], CharacteristicsDirection.Outflow, CharacteristicsAnalyticsTreatment.Expense, 0.55),

        // -- 12070 Driving & Licensing --
        new(null, 120701, "Driving lessons.",
            ["Lesson block booking"],
            ["Charge is driving tuition", "Direction is outflow"],
            [],
            [], CharacteristicsDirection.Outflow, CharacteristicsAnalyticsTreatment.Expense, 0.65),
        new(null, 120702, "Theory test fees.",
            ["Theory test booking"],
            ["Charge is the theory test", "Direction is outflow"],
            [],
            ["THEORY TEST"], CharacteristicsDirection.Outflow, CharacteristicsAnalyticsTreatment.Expense, 0.7),
        new(null, 120703, "Driving test fees.",
            ["Driving test booking"],
            ["Charge is the driving test", "Direction is outflow"],
            [],
            [], CharacteristicsDirection.Outflow, CharacteristicsAnalyticsTreatment.Expense, 0.65),
        new(null, 120704, "Learner permit fees.",
            ["Learner permit application"],
            ["Charge is a learner permit", "Direction is outflow"],
            [],
            ["LEARNER PERMIT"], CharacteristicsDirection.Outflow, CharacteristicsAnalyticsTreatment.Expense, 0.7),
        new(null, 120705, "Licence renewals.",
            ["Ten-year licence renewal"],
            ["Charge renews a driving licence", "Direction is outflow"],
            [],
            [], CharacteristicsDirection.Outflow, CharacteristicsAnalyticsTreatment.Expense, 0.65),
        new(null, 120706, "Driving school materials: logbooks, apps, mock tests.",
            ["Theory app purchase"],
            ["Goods support learning to drive", "Direction is outflow"],
            [],
            [], CharacteristicsDirection.Outflow, CharacteristicsAnalyticsTreatment.Expense, 0.55),
        new(null, 120707, "Vehicle licensing admin: replacement documents, admin fees.",
            ["Replacement licence fee"],
            ["Charge is licensing administration", "Direction is outflow"],
            [],
            [], CharacteristicsDirection.Outflow, CharacteristicsAnalyticsTreatment.Expense, 0.55),

        // -- 12080 Long-Distance Transport (120801 Flights already defined) --
        new(null, 120802, "Intercity rail journeys.",
            ["Dublin-Cork train"],
            ["Journey is intercity rail", "Direction is outflow"],
            ["Commuter rail belongs to Public Transport"],
            [], CharacteristicsDirection.Outflow, CharacteristicsAnalyticsTreatment.Expense, 0.6),
        new(null, 120803, "Intercity coaches.",
            ["Intercity coach ticket"],
            ["Journey is an intercity coach", "Direction is outflow"],
            [],
            [], CharacteristicsDirection.Outflow, CharacteristicsAnalyticsTreatment.Expense, 0.6),
        new(null, 120804, "Car rental on trips.",
            ["Hire car for the week"],
            ["Charge is car rental", "Direction is outflow"],
            ["Moving-van hire belongs to Moving & Temporary Housing"],
            ["HERTZ", "ENTERPRISE RENT", "SIXT", "EUROPCAR"], CharacteristicsDirection.Outflow, CharacteristicsAnalyticsTreatment.Expense, 0.75),
        new(null, 120805, "Airport transfers: shuttles and dedicated services.",
            ["Airport shuttle bus"],
            ["Journey is an airport transfer", "Direction is outflow"],
            [],
            [], CharacteristicsDirection.Outflow, CharacteristicsAnalyticsTreatment.Expense, 0.55),
        new(null, 120806, "Airline baggage fees.",
            ["Checked bag fee"],
            ["Charge is baggage", "Direction is outflow"],
            [],
            [], CharacteristicsDirection.Outflow, CharacteristicsAnalyticsTreatment.Expense, 0.55),
        new(null, 120807, "Seat selection and travel add-ons.",
            ["Seat selection fee"],
            ["Charge is a travel add-on", "Direction is outflow"],
            [],
            [], CharacteristicsDirection.Outflow, CharacteristicsAnalyticsTreatment.Expense, 0.5),

        // -- 12090 Other Transportation (deterministic-only catch-alls) --
        new(12090, null, "Transport costs that fit nowhere else; a human choice, never an AI guess.",
            ["Genuinely unclassifiable transport expense"],
            ["Only deterministic rules or the user may assign this catch-all"],
            [],
            [], CharacteristicsDirection.Outflow, CharacteristicsAnalyticsTreatment.Expense, null),
        new(null, 120901, "Miscellaneous transport, user-assigned.",
            ["One-off with no better node"],
            ["Only deterministic rules or the user may assign this catch-all"],
            [],
            [], CharacteristicsDirection.Outflow, CharacteristicsAnalyticsTreatment.Expense, null),
        new(null, 120902, "Unclassified transport, user-assigned.",
            ["Awaiting proper classification"],
            ["Only deterministic rules or the user may assign this catch-all"],
            [],
            [], CharacteristicsDirection.Outflow, CharacteristicsAnalyticsTreatment.Expense, null)
    ];
}
