namespace NSFinance.Shared.Taxonomy;

// Full-coverage characteristics: Food & Dining (130) subcategories.
// "Other Food & Dining" holds real activities (tips, delivery fees, vending)
// that get proper definitions; only the true catch-all is deterministic-only.
public static partial class CategoryCharacteristicsCatalog
{
    private static readonly IReadOnlyList<CategoryCharacteristicsDefinition> FoodDiningSubcategoryDefinitions =
    [
        // -- 13010 Groceries --
        new(null, 130101, "The supermarket run proper.",
            ["Weekly shop at a supermarket"],
            ["Merchant is a full supermarket", "Direction is outflow"],
            [],
            [], CharacteristicsDirection.Outflow, CharacteristicsAnalyticsTreatment.Expense, 0.6),
        new(null, 130102, "Convenience store top-ups.",
            ["Milk and bread from the corner shop"],
            ["Merchant is a convenience store", "Direction is outflow"],
            [],
            ["DAYBREAK", "GALA", "MACE", "COSTCUTTER", "LONDIS"], CharacteristicsDirection.Outflow, CharacteristicsAnalyticsTreatment.Expense, 0.7),
        new(null, 130103, "Greengrocers and fresh produce.",
            ["Fruit and veg stall"],
            ["Merchant sells fresh produce", "Direction is outflow"],
            [],
            ["GREENGROCER"], CharacteristicsDirection.Outflow, CharacteristicsAnalyticsTreatment.Expense, 0.6),
        new(null, 130104, "Butchers and fishmongers.",
            ["Butcher counter shop"],
            ["Merchant is a butcher or fishmonger", "Direction is outflow"],
            [],
            ["BUTCHER", "FISHMONGER"], CharacteristicsDirection.Outflow, CharacteristicsAnalyticsTreatment.Expense, 0.7),
        new(null, 130105, "Dairy and eggs bought from specialty sellers.",
            ["Farm-gate eggs and milk"],
            ["Purchase is dairy or eggs from a specialty seller", "Direction is outflow"],
            ["Supermarket dairy stays in Supermarket"],
            [], CharacteristicsDirection.Outflow, CharacteristicsAnalyticsTreatment.Expense, 0.5),
        new(null, 130106, "Bakeries: bread and pastries to take home.",
            ["Sourdough from the bakery"],
            ["Merchant is a bakery selling take-home goods", "Direction is outflow"],
            ["Cafe pastries eaten in belong to Coffee Shops"],
            ["BAKERY"], CharacteristicsDirection.Outflow, CharacteristicsAnalyticsTreatment.Expense, 0.6),
        new(null, 130107, "Frozen food specialists.",
            ["Frozen-food shop visit"],
            ["Merchant specializes in frozen food", "Direction is outflow"],
            [],
            ["ICELAND"], CharacteristicsDirection.Outflow, CharacteristicsAnalyticsTreatment.Expense, 0.7),
        new(null, 130108, "Pantry staples from specialty or bulk sellers.",
            ["Bulk pantry order"],
            ["Purchase is shelf-stable staples from a specialty seller", "Direction is outflow"],
            [],
            [], CharacteristicsDirection.Outflow, CharacteristicsAnalyticsTreatment.Expense, 0.5),
        new(null, 130109, "Snack purchases identified as such.",
            ["Snack run"],
            ["Purchase is snacks", "Direction is outflow"],
            [],
            [], CharacteristicsDirection.Outflow, CharacteristicsAnalyticsTreatment.Expense, 0.5),
        new(null, 130110, "Beverages for home: soft drinks, juices, water.",
            ["Case of sparkling water"],
            ["Purchase is non-alcoholic beverages for home", "Direction is outflow"],
            ["Off-licence alcohol follows the off-licence profile"],
            [], CharacteristicsDirection.Outflow, CharacteristicsAnalyticsTreatment.Expense, 0.5),
        new(null, 130111, "Mixed baskets: groceries plus household goods in one till.",
            ["Big shop with cleaning products included"],
            ["Basket mixes food and household goods", "Direction is outflow"],
            [],
            [], CharacteristicsDirection.Outflow, CharacteristicsAnalyticsTreatment.Expense, 0.5),

        // -- 13020 Dining Out --
        new(null, 130201, "Sit-down restaurants.",
            ["Dinner out"],
            ["Merchant is a restaurant", "Direction is outflow"],
            [],
            ["RESTAURANT", "BISTRO", "EATERY"], CharacteristicsDirection.Outflow, CharacteristicsAnalyticsTreatment.Expense, 0.65),
        new(null, 130202, "Cafes serving food-first menus.",
            ["Brunch at a cafe"],
            ["Merchant is a food-first cafe", "Direction is outflow"],
            ["Coffee-first chains belong to Coffee Shops"],
            [], CharacteristicsDirection.Outflow, CharacteristicsAnalyticsTreatment.Expense, 0.55),
        new(null, 130203, "Fast food counters.",
            ["Burger meal"],
            ["Merchant is fast food", "Direction is outflow"],
            [],
            ["BURGER KING", "KFC", "SUBWAY", "FIVE GUYS"], CharacteristicsDirection.Outflow, CharacteristicsAnalyticsTreatment.Expense, 0.75),
        new(null, 130204, "Takeaway collected yourself.",
            ["Friday chipper collection"],
            ["Meal is takeaway collected in person", "Direction is outflow"],
            [],
            ["TAKEAWAY", "CHIPPER"], CharacteristicsDirection.Outflow, CharacteristicsAnalyticsTreatment.Expense, 0.6),
        new(null, 130205, "Delivered restaurant food.",
            ["Delivery order night"],
            ["Meal is delivered", "Direction is outflow"],
            [],
            [], CharacteristicsDirection.Outflow, CharacteristicsAnalyticsTreatment.Expense, 0.55),
        new(null, 130206, "Food courts and market stalls.",
            ["Food-hall lunch"],
            ["Meal is from a food court or stall", "Direction is outflow"],
            [],
            ["FOOD COURT", "FOOD HALL"], CharacteristicsDirection.Outflow, CharacteristicsAnalyticsTreatment.Expense, 0.6),
        new(null, 130207, "Fine dining occasions.",
            ["Tasting-menu dinner"],
            ["Meal is fine dining", "Direction is outflow"],
            [],
            [], CharacteristicsDirection.Outflow, CharacteristicsAnalyticsTreatment.Expense, 0.5),
        new(null, 130208, "Workday lunches.",
            ["Lunch near the office"],
            ["Meal is a workday lunch pattern", "Direction is outflow"],
            [],
            [], CharacteristicsDirection.Outflow, CharacteristicsAnalyticsTreatment.Expense, 0.5),

        // -- 13030 Drinks & Social Food (130301 Coffee Shops already defined) --
        new(null, 130302, "Tea rooms and juice bars.",
            ["Juice bar smoothie"],
            ["Merchant is a tea room or juice bar", "Direction is outflow"],
            [],
            ["JUICE BAR"], CharacteristicsDirection.Outflow, CharacteristicsAnalyticsTreatment.Expense, 0.6),
        new(null, 130303, "Drinks at pubs and bars.",
            ["Round of pints"],
            ["Purchase is alcohol at a licensed venue", "Direction is outflow"],
            ["Off-licence purchases for home follow the grocery profile"],
            [], CharacteristicsDirection.Outflow, CharacteristicsAnalyticsTreatment.Expense, 0.55),
        new(null, 130304, "Cocktail bars.",
            ["Cocktails out"],
            ["Merchant is a cocktail bar", "Direction is outflow"],
            [],
            ["COCKTAIL"], CharacteristicsDirection.Outflow, CharacteristicsAnalyticsTreatment.Expense, 0.6),
        new(null, 130305, "Food and drink inside nightlife venues.",
            ["Late-night venue food"],
            ["Purchase is inside a nightlife venue", "Direction is outflow"],
            [],
            ["NIGHTCLUB"], CharacteristicsDirection.Outflow, CharacteristicsAnalyticsTreatment.Expense, 0.55),
        new(null, 130306, "Happy hour and drinks promotions.",
            ["Happy-hour round"],
            ["Purchase is discounted venue drinks", "Direction is outflow"],
            [],
            [], CharacteristicsDirection.Outflow, CharacteristicsAnalyticsTreatment.Expense, 0.5),
        new(null, 130307, "Club entry bundled with drinks.",
            ["Entry with drink tokens"],
            ["Charge bundles entry and drinks", "Direction is outflow"],
            ["Pure event tickets belong to Events & Outings"],
            [], CharacteristicsDirection.Outflow, CharacteristicsAnalyticsTreatment.Expense, 0.5),

        // -- 13040 Special Dietary Spending --
        new(null, 130401, "Vegan and vegetarian specialty food.",
            ["Vegan specialty order"],
            ["Merchant or product line is plant-based specialty", "Direction is outflow"],
            [],
            [], CharacteristicsDirection.Outflow, CharacteristicsAnalyticsTreatment.Expense, 0.55),
        new(null, 130402, "Gluten-free specialty food.",
            ["Coeliac-friendly shop"],
            ["Product line is gluten-free specialty", "Direction is outflow"],
            [],
            ["GLUTEN FREE"], CharacteristicsDirection.Outflow, CharacteristicsAnalyticsTreatment.Expense, 0.6),
        new(null, 130403, "Organic specialty food.",
            ["Organic farm shop"],
            ["Merchant specializes in organic food", "Direction is outflow"],
            [],
            ["ORGANIC"], CharacteristicsDirection.Outflow, CharacteristicsAnalyticsTreatment.Expense, 0.55),
        new(null, 130404, "Sports nutrition and protein products.",
            ["Protein powder order"],
            ["Product is sports nutrition", "Direction is outflow"],
            [],
            [], CharacteristicsDirection.Outflow, CharacteristicsAnalyticsTreatment.Expense, 0.55),
        new(null, 130405, "Baby food and formula.",
            ["Formula and pouches"],
            ["Product is baby food or formula", "Direction is outflow"],
            [],
            [], CharacteristicsDirection.Outflow, CharacteristicsAnalyticsTreatment.Expense, 0.55),
        new(null, 130406, "Medically required diet foods.",
            ["Prescribed dietary product"],
            ["Product is a medical-diet food", "Direction is outflow"],
            [],
            [], CharacteristicsDirection.Outflow, CharacteristicsAnalyticsTreatment.Expense, 0.5),

        // -- 13050 Meal Services --
        new(null, 130501, "Meal-kit boxes.",
            ["Weekly recipe box"],
            ["Service delivers meal kits", "Direction is outflow"],
            [],
            [], CharacteristicsDirection.Outflow, CharacteristicsAnalyticsTreatment.Expense, 0.6),
        new(null, 130502, "Prepared-meal subscriptions.",
            ["Ready-meal plan delivery"],
            ["Service delivers prepared meals on a plan", "Direction is outflow"],
            [],
            [], CharacteristicsDirection.Outflow, CharacteristicsAnalyticsTreatment.Expense, 0.6),
        new(null, 130503, "Office catering you pay for.",
            ["Team lunch catering"],
            ["Purchase caters a workplace", "Direction is outflow"],
            [],
            [], CharacteristicsDirection.Outflow, CharacteristicsAnalyticsTreatment.Expense, 0.5),
        new(null, 130504, "Personal chefs and event catering.",
            ["Caterer for a party"],
            ["Service is private catering", "Direction is outflow"],
            [],
            ["CATERING"], CharacteristicsDirection.Outflow, CharacteristicsAnalyticsTreatment.Expense, 0.6),
        new(null, 130505, "Group food orders you fronted.",
            ["Office group order on your card"],
            ["Purchase is a group order you paid", "Direction is outflow"],
            ["Repayments arriving are Reimbursements"],
            [], CharacteristicsDirection.Outflow, CharacteristicsAnalyticsTreatment.Expense, 0.5),

        // -- 13070 Tobacco & Nicotine --
        new(null, 130701, "Cigarettes and rolling tobacco.",
            ["Pack of cigarettes"],
            ["Product is cigarettes or tobacco", "Direction is outflow"],
            [],
            [], CharacteristicsDirection.Outflow, CharacteristicsAnalyticsTreatment.Expense, 0.6),
        new(null, 130702, "Vapes and e-liquids.",
            ["Vape shop refill"],
            ["Product is vaping gear or e-liquid", "Direction is outflow"],
            [],
            [], CharacteristicsDirection.Outflow, CharacteristicsAnalyticsTreatment.Expense, 0.6),
        new(null, 130703, "Nicotine alternatives: patches, gum, pouches.",
            ["Nicotine gum"],
            ["Product is a nicotine alternative", "Direction is outflow"],
            ["Pharmacy-bought cessation products may follow the pharmacy profile"],
            [], CharacteristicsDirection.Outflow, CharacteristicsAnalyticsTreatment.Expense, 0.55),

        // -- 13060 Other Food & Dining (real activities + one catch-all) --
        new(null, 130601, "Tips and gratuities paid separately.",
            ["Card tip after the meal"],
            ["Payment is a tip", "Direction is outflow"],
            [],
            [], CharacteristicsDirection.Outflow, CharacteristicsAnalyticsTreatment.Expense, 0.5),
        new(null, 130602, "Delivery platform fees charged separately.",
            ["Delivery fee line"],
            ["Charge is a food-delivery fee", "Direction is outflow"],
            [],
            [], CharacteristicsDirection.Outflow, CharacteristicsAnalyticsTreatment.Expense, 0.5),
        new(null, 130603, "Corkage and service charges.",
            ["Corkage on a bottle"],
            ["Charge is corkage or service", "Direction is outflow"],
            [],
            [], CharacteristicsDirection.Outflow, CharacteristicsAnalyticsTreatment.Expense, 0.5),
        new(null, 130604, "Vending machines.",
            ["Vending machine snack"],
            ["Purchase is from a vending machine", "Direction is outflow"],
            [],
            ["VENDING"], CharacteristicsDirection.Outflow, CharacteristicsAnalyticsTreatment.Expense, 0.65),
        new(null, 130605, "Other food expense, user-assigned.",
            ["Food one-off with no better node"],
            ["Only deterministic rules or the user may assign this catch-all"],
            [],
            [], CharacteristicsDirection.Outflow, CharacteristicsAnalyticsTreatment.Expense, null)
    ];
}
