namespace NSFinance.Shared.Taxonomy;

// Full-coverage characteristics: Housing (100) subcategories. Every node in
// the domain is defined; category-level definitions live in the core file.
// Signals appear only where a brand or phrase is subcategory-specific and
// not already owned by a parent definition. Null-floor entries are
// user-pick-only: the AI may label but never infer them.
public static partial class CategoryCharacteristicsCatalog
{
    private static readonly IReadOnlyList<CategoryCharacteristicsDefinition> HousingSubcategoryDefinitions =
    [
        // -- 10010 Rent & Mortgage (100101 Rent already defined in core) --
        new(
            TaxonomyCategoryId: null,
            TaxonomySubcategoryId: 100102,
            Description: "The part of a mortgage payment that repays what you borrowed.",
            UseCases: ["Split mortgage statement, principal portion"],
            InclusionRules: ["Payment reduces the mortgage balance", "Direction is outflow"],
            ExclusionRules: ["Interest belongs to Mortgage Interest", "Combined payments stay at the Rent & Mortgage category level"],
            MerchantSignals: [],
            DirectionExpectation: CharacteristicsDirection.Outflow,
            AnalyticsTreatment: CharacteristicsAnalyticsTreatment.Expense,
            ConfidenceFloor: 0.7),
        new(
            TaxonomyCategoryId: null,
            TaxonomySubcategoryId: 100103,
            Description: "The cost-of-borrowing part of a mortgage payment.",
            UseCases: ["Split mortgage statement, interest portion"],
            InclusionRules: ["Charge is mortgage interest", "Direction is outflow"],
            ExclusionRules: ["Principal belongs to Mortgage Principal"],
            MerchantSignals: [],
            DirectionExpectation: CharacteristicsDirection.Outflow,
            AnalyticsTreatment: CharacteristicsAnalyticsTreatment.Expense,
            ConfidenceFloor: 0.7),
        new(
            TaxonomyCategoryId: null,
            TaxonomySubcategoryId: 100104,
            Description: "Insurance required by or protecting the mortgage itself.",
            UseCases: ["Mortgage protection premium billed with the loan"],
            InclusionRules: ["Premium exists because of the mortgage", "Direction is outflow"],
            ExclusionRules: ["Standalone life policies belong to Life & Disability"],
            MerchantSignals: [],
            DirectionExpectation: CharacteristicsDirection.Outflow,
            AnalyticsTreatment: CharacteristicsAnalyticsTreatment.Expense,
            ConfidenceFloor: 0.65),
        new(
            TaxonomyCategoryId: null,
            TaxonomySubcategoryId: 100105,
            Description: "Ground rent and leasehold service charges on the home.",
            UseCases: ["Annual ground rent demand"],
            InclusionRules: ["Charge is ground rent or leasehold-related", "Direction is outflow"],
            ExclusionRules: ["Management-company fees belong to Property Taxes & Fees"],
            MerchantSignals: ["GROUND RENT"],
            DirectionExpectation: CharacteristicsDirection.Outflow,
            AnalyticsTreatment: CharacteristicsAnalyticsTreatment.Expense,
            ConfidenceFloor: 0.7),
        new(
            TaxonomyCategoryId: null,
            TaxonomySubcategoryId: 100106,
            Description: "A deposit paid to secure a rented home; usually recoverable at the end.",
            UseCases: ["First-month-plus-deposit payment to a landlord or agency"],
            InclusionRules: ["Payment is a tenancy deposit", "Direction is outflow"],
            ExclusionRules: ["Ordinary monthly rent follows the Rent definition"],
            MerchantSignals: [],
            DirectionExpectation: CharacteristicsDirection.Outflow,
            AnalyticsTreatment: CharacteristicsAnalyticsTreatment.Expense,
            ConfidenceFloor: 0.65),
        new(
            TaxonomyCategoryId: null,
            TaxonomySubcategoryId: 100107,
            Description: "Payments to housing associations and approved housing bodies.",
            UseCases: ["Housing association weekly or monthly charge"],
            InclusionRules: ["Payee is a housing association", "Direction is outflow"],
            ExclusionRules: [],
            MerchantSignals: ["HOUSING ASSOC"],
            DirectionExpectation: CharacteristicsDirection.Outflow,
            AnalyticsTreatment: CharacteristicsAnalyticsTreatment.Expense,
            ConfidenceFloor: 0.7),
        new(
            TaxonomyCategoryId: null,
            TaxonomySubcategoryId: 100108,
            Description: "Paying your share of a shared house: digs, room rent, house kitty.",
            UseCases: ["Monthly room payment to the leaseholder", "House-share kitty contribution"],
            InclusionRules: ["Payment is your share of shared accommodation", "Direction is outflow"],
            ExclusionRules: ["Payments to a landlord under your own tenancy follow the Rent definition"],
            MerchantSignals: [],
            DirectionExpectation: CharacteristicsDirection.Outflow,
            AnalyticsTreatment: CharacteristicsAnalyticsTreatment.Expense,
            ConfidenceFloor: 0.6),

        // -- 10020 Property Taxes & Fees --
        new(
            TaxonomyCategoryId: null,
            TaxonomySubcategoryId: 100201,
            Description: "Property taxes other than the Irish LPT: foreign or historic property tax bills.",
            UseCases: ["Property tax on a holiday home abroad"],
            InclusionRules: ["Charge is a property tax", "Direction is outflow"],
            ExclusionRules: ["Irish LPT belongs to Local Property Tax"],
            MerchantSignals: [],
            DirectionExpectation: CharacteristicsDirection.Outflow,
            AnalyticsTreatment: CharacteristicsAnalyticsTreatment.Expense,
            ConfidenceFloor: 0.65),
        new(
            TaxonomyCategoryId: null,
            TaxonomySubcategoryId: 100202,
            Description: "Local Property Tax paid to Revenue, or council tax abroad.",
            UseCases: ["Annual LPT single payment", "Phased LPT direct debit"],
            InclusionRules: ["Charge is LPT or a council-tax equivalent", "Direction is outflow"],
            ExclusionRules: [],
            MerchantSignals: [],
            DirectionExpectation: CharacteristicsDirection.Outflow,
            AnalyticsTreatment: CharacteristicsAnalyticsTreatment.Expense,
            ConfidenceFloor: 0.7),
        new(
            TaxonomyCategoryId: null,
            TaxonomySubcategoryId: 100203,
            Description: "Owners' association and shared-estate charges.",
            UseCases: ["Annual owners' management company subscription"],
            InclusionRules: ["Charge comes from an owners' association", "Direction is outflow"],
            ExclusionRules: ["Building operational management belongs to Building Management Fees"],
            MerchantSignals: [],
            DirectionExpectation: CharacteristicsDirection.Outflow,
            AnalyticsTreatment: CharacteristicsAnalyticsTreatment.Expense,
            ConfidenceFloor: 0.6),
        new(
            TaxonomyCategoryId: null,
            TaxonomySubcategoryId: 100204,
            Description: "Managing agent and building-operations charges for apartments.",
            UseCases: ["Apartment block management fee"],
            InclusionRules: ["Charge is from a managing agent for the building", "Direction is outflow"],
            ExclusionRules: [],
            MerchantSignals: ["MGMT FEE", "MANAGEMENT FEE"],
            DirectionExpectation: CharacteristicsDirection.Outflow,
            AnalyticsTreatment: CharacteristicsAnalyticsTreatment.Expense,
            ConfidenceFloor: 0.65),
        new(
            TaxonomyCategoryId: null,
            TaxonomySubcategoryId: 100205,
            Description: "Land Registry and property registration charges.",
            UseCases: ["Land registry fee during a purchase"],
            InclusionRules: ["Charge registers property or land rights", "Direction is outflow"],
            ExclusionRules: ["Solicitor fees belong to Legal Services"],
            MerchantSignals: ["LAND REGISTRY", "TAILTE"],
            DirectionExpectation: CharacteristicsDirection.Outflow,
            AnalyticsTreatment: CharacteristicsAnalyticsTreatment.Expense,
            ConfidenceFloor: 0.7),
        new(
            TaxonomyCategoryId: null,
            TaxonomySubcategoryId: 100206,
            Description: "Permits, certificates, and inspections the home needs.",
            UseCases: ["Planning permission fee", "BER assessment"],
            InclusionRules: ["Charge is a housing permit, certificate, or inspection", "Direction is outflow"],
            ExclusionRules: [],
            MerchantSignals: ["BER CERT"],
            DirectionExpectation: CharacteristicsDirection.Outflow,
            AnalyticsTreatment: CharacteristicsAnalyticsTreatment.Expense,
            ConfidenceFloor: 0.65),

        // -- 10030 Home Maintenance & Repairs --
        new(
            TaxonomyCategoryId: null,
            TaxonomySubcategoryId: 100301,
            Description: "General repair work that keeps the house functioning.",
            UseCases: ["Odd-job repair visit"],
            InclusionRules: ["Work restores something broken in the home", "Direction is outflow"],
            ExclusionRules: ["Specialist trades below take precedence when identifiable"],
            MerchantSignals: [],
            DirectionExpectation: CharacteristicsDirection.Outflow,
            AnalyticsTreatment: CharacteristicsAnalyticsTreatment.Expense,
            ConfidenceFloor: 0.6),
        new(
            TaxonomyCategoryId: null,
            TaxonomySubcategoryId: 100302,
            Description: "Plumbers: leaks, taps, pipes, cylinders.",
            UseCases: ["Plumber call-out for a leak"],
            InclusionRules: ["Trade is plumbing", "Direction is outflow"],
            ExclusionRules: ["Boiler servicing belongs to Gas & Heating"],
            MerchantSignals: ["PLUMBING", "PLUMBER"],
            DirectionExpectation: CharacteristicsDirection.Outflow,
            AnalyticsTreatment: CharacteristicsAnalyticsTreatment.Expense,
            ConfidenceFloor: 0.7),
        new(
            TaxonomyCategoryId: null,
            TaxonomySubcategoryId: 100303,
            Description: "Electricians: sockets, boards, wiring, certs.",
            UseCases: ["Electrician rewiring a socket"],
            InclusionRules: ["Trade is electrical", "Direction is outflow"],
            ExclusionRules: ["Electricity bills belong to Electricity"],
            MerchantSignals: ["ELECTRICAL SERVICES", "ELECTRICIAN"],
            DirectionExpectation: CharacteristicsDirection.Outflow,
            AnalyticsTreatment: CharacteristicsAnalyticsTreatment.Expense,
            ConfidenceFloor: 0.7),
        new(
            TaxonomyCategoryId: null,
            TaxonomySubcategoryId: 100304,
            Description: "Roofers: slates, flat roofs, gutters attached to roof work.",
            UseCases: ["Storm damage roof repair"],
            InclusionRules: ["Trade is roofing", "Direction is outflow"],
            ExclusionRules: [],
            MerchantSignals: ["ROOFING"],
            DirectionExpectation: CharacteristicsDirection.Outflow,
            AnalyticsTreatment: CharacteristicsAnalyticsTreatment.Expense,
            ConfidenceFloor: 0.7),
        new(
            TaxonomyCategoryId: null,
            TaxonomySubcategoryId: 100305,
            Description: "Fixing appliances: washing machines, ovens, dryers.",
            UseCases: ["Washing machine engineer visit"],
            InclusionRules: ["Service repairs a household appliance", "Direction is outflow"],
            ExclusionRules: ["Replacing the appliance belongs to Furniture & Appliances"],
            MerchantSignals: ["APPLIANCE REPAIR"],
            DirectionExpectation: CharacteristicsDirection.Outflow,
            AnalyticsTreatment: CharacteristicsAnalyticsTreatment.Expense,
            ConfidenceFloor: 0.65),
        new(
            TaxonomyCategoryId: null,
            TaxonomySubcategoryId: 100306,
            Description: "Locksmiths: lockouts, lock changes, keys stuck.",
            UseCases: ["Emergency lockout call-out"],
            InclusionRules: ["Trade is locksmithing", "Direction is outflow"],
            ExclusionRules: ["Simple key cutting belongs to Security & Home Services"],
            MerchantSignals: ["LOCKSMITH"],
            DirectionExpectation: CharacteristicsDirection.Outflow,
            AnalyticsTreatment: CharacteristicsAnalyticsTreatment.Expense,
            ConfidenceFloor: 0.75),
        new(
            TaxonomyCategoryId: null,
            TaxonomySubcategoryId: 100307,
            Description: "Pest controllers: mice, wasps, treatments.",
            UseCases: ["Wasp nest removal"],
            InclusionRules: ["Service is professional pest control", "Direction is outflow"],
            ExclusionRules: ["DIY traps and sprays belong to Home Supplies"],
            MerchantSignals: ["PEST CONTROL", "RENTOKIL"],
            DirectionExpectation: CharacteristicsDirection.Outflow,
            AnalyticsTreatment: CharacteristicsAnalyticsTreatment.Expense,
            ConfidenceFloor: 0.75),
        new(
            TaxonomyCategoryId: null,
            TaxonomySubcategoryId: 100308,
            Description: "Handyman services: small jobs across trades.",
            UseCases: ["Shelf hanging and small fixes visit"],
            InclusionRules: ["Provider is a general handyman", "Direction is outflow"],
            ExclusionRules: [],
            MerchantSignals: ["HANDYMAN"],
            DirectionExpectation: CharacteristicsDirection.Outflow,
            AnalyticsTreatment: CharacteristicsAnalyticsTreatment.Expense,
            ConfidenceFloor: 0.7),
        new(
            TaxonomyCategoryId: null,
            TaxonomySubcategoryId: 100309,
            Description: "Paid home cleaning: regular cleaners and deep cleans.",
            UseCases: ["Fortnightly cleaner", "One-off deep clean"],
            InclusionRules: ["Service cleans the home", "Direction is outflow"],
            ExclusionRules: ["Cleaning products belong to Home Supplies"],
            MerchantSignals: ["CLEANING SERVICES"],
            DirectionExpectation: CharacteristicsDirection.Outflow,
            AnalyticsTreatment: CharacteristicsAnalyticsTreatment.Expense,
            ConfidenceFloor: 0.7),
        new(
            TaxonomyCategoryId: null,
            TaxonomySubcategoryId: 100310,
            Description: "Emergency call-outs at emergency prices.",
            UseCases: ["Burst pipe at midnight"],
            InclusionRules: ["Work was urgent and unscheduled", "Direction is outflow"],
            ExclusionRules: ["Planned work belongs to the relevant trade subcategory"],
            MerchantSignals: [],
            DirectionExpectation: CharacteristicsDirection.Outflow,
            AnalyticsTreatment: CharacteristicsAnalyticsTreatment.Expense,
            ConfidenceFloor: 0.55),

        // -- 10040 Home Improvements & Renovation --
        new(
            TaxonomyCategoryId: null,
            TaxonomySubcategoryId: 100401,
            Description: "Professional painting and decorating.",
            UseCases: ["Painter for two rooms"],
            InclusionRules: ["Service is painting or decorating", "Direction is outflow"],
            ExclusionRules: ["Paint you buy yourself belongs to DIY Supplies"],
            MerchantSignals: ["PAINTING & DECORATING"],
            DirectionExpectation: CharacteristicsDirection.Outflow,
            AnalyticsTreatment: CharacteristicsAnalyticsTreatment.Expense,
            ConfidenceFloor: 0.7),
        new(
            TaxonomyCategoryId: null,
            TaxonomySubcategoryId: 100402,
            Description: "New floors: fitting timber, laminate, tile, carpet.",
            UseCases: ["Laminate floor supply and fit"],
            InclusionRules: ["Work installs flooring", "Direction is outflow"],
            ExclusionRules: ["Rugs belong to Furniture & Appliances"],
            MerchantSignals: ["FLOORING"],
            DirectionExpectation: CharacteristicsDirection.Outflow,
            AnalyticsTreatment: CharacteristicsAnalyticsTreatment.Expense,
            ConfidenceFloor: 0.7),
        new(
            TaxonomyCategoryId: null,
            TaxonomySubcategoryId: 100403,
            Description: "Kitchen renovation: units, counters, fit-out.",
            UseCases: ["New kitchen supply and fit"],
            InclusionRules: ["Project renovates the kitchen", "Direction is outflow"],
            ExclusionRules: ["Standalone appliances belong to Furniture & Appliances"],
            MerchantSignals: ["KITCHENS"],
            DirectionExpectation: CharacteristicsDirection.Outflow,
            AnalyticsTreatment: CharacteristicsAnalyticsTreatment.Expense,
            ConfidenceFloor: 0.65),
        new(
            TaxonomyCategoryId: null,
            TaxonomySubcategoryId: 100404,
            Description: "Bathroom renovation: suites, tiling, showers.",
            UseCases: ["Bathroom refit"],
            InclusionRules: ["Project renovates the bathroom", "Direction is outflow"],
            ExclusionRules: [],
            MerchantSignals: ["BATHROOMS"],
            DirectionExpectation: CharacteristicsDirection.Outflow,
            AnalyticsTreatment: CharacteristicsAnalyticsTreatment.Expense,
            ConfidenceFloor: 0.65),
        new(
            TaxonomyCategoryId: null,
            TaxonomySubcategoryId: 100405,
            Description: "Carpentry and joinery: wardrobes, stairs, built-ins.",
            UseCases: ["Fitted wardrobe build"],
            InclusionRules: ["Trade is carpentry or joinery", "Direction is outflow"],
            ExclusionRules: [],
            MerchantSignals: ["CARPENTRY", "JOINERY"],
            DirectionExpectation: CharacteristicsDirection.Outflow,
            AnalyticsTreatment: CharacteristicsAnalyticsTreatment.Expense,
            ConfidenceFloor: 0.7),
        new(
            TaxonomyCategoryId: null,
            TaxonomySubcategoryId: 100406,
            Description: "Windows and doors: replacement and glazing.",
            UseCases: ["Double glazing replacement"],
            InclusionRules: ["Work supplies or fits windows or doors", "Direction is outflow"],
            ExclusionRules: [],
            MerchantSignals: ["WINDOWS & DOORS", "GLAZING"],
            DirectionExpectation: CharacteristicsDirection.Outflow,
            AnalyticsTreatment: CharacteristicsAnalyticsTreatment.Expense,
            ConfidenceFloor: 0.7),
        new(
            TaxonomyCategoryId: null,
            TaxonomySubcategoryId: 100407,
            Description: "Insulation: attic, cavity, external wrap.",
            UseCases: ["Attic insulation top-up"],
            InclusionRules: ["Work insulates the home", "Direction is outflow"],
            ExclusionRules: [],
            MerchantSignals: ["INSULATION"],
            DirectionExpectation: CharacteristicsDirection.Outflow,
            AnalyticsTreatment: CharacteristicsAnalyticsTreatment.Expense,
            ConfidenceFloor: 0.7),
        new(
            TaxonomyCategoryId: null,
            TaxonomySubcategoryId: 100408,
            Description: "Smart-home installation: hubs, heating controls, wiring them in.",
            UseCases: ["Smart thermostat supply and install"],
            InclusionRules: ["Work installs smart-home equipment", "Direction is outflow"],
            ExclusionRules: ["Self-installed gadgets belong to Electronics"],
            MerchantSignals: [],
            DirectionExpectation: CharacteristicsDirection.Outflow,
            AnalyticsTreatment: CharacteristicsAnalyticsTreatment.Expense,
            ConfidenceFloor: 0.6),
        new(
            TaxonomyCategoryId: null,
            TaxonomySubcategoryId: 100409,
            Description: "Accessibility upgrades: ramps, rails, stairlifts.",
            UseCases: ["Stairlift installation"],
            InclusionRules: ["Work adapts the home for accessibility", "Direction is outflow"],
            ExclusionRules: ["Personal mobility aids belong to Medical Equipment"],
            MerchantSignals: ["STAIRLIFT"],
            DirectionExpectation: CharacteristicsDirection.Outflow,
            AnalyticsTreatment: CharacteristicsAnalyticsTreatment.Expense,
            ConfidenceFloor: 0.65),
        new(
            TaxonomyCategoryId: null,
            TaxonomySubcategoryId: 100410,
            Description: "The builder's bill: contractor and labour costs on projects.",
            UseCases: ["Stage payment to a contractor"],
            InclusionRules: ["Payment is project labour rather than a specific trade", "Direction is outflow"],
            ExclusionRules: ["Identifiable single trades belong to their subcategories"],
            MerchantSignals: ["CONTRACTORS", "CONSTRUCTION"],
            DirectionExpectation: CharacteristicsDirection.Outflow,
            AnalyticsTreatment: CharacteristicsAnalyticsTreatment.Expense,
            ConfidenceFloor: 0.6),

        // -- 10050 Furniture & Appliances --
        new(
            TaxonomyCategoryId: null,
            TaxonomySubcategoryId: 100501,
            Description: "Furniture proper: sofas, tables, beds, shelving.",
            UseCases: ["New sofa"],
            InclusionRules: ["Item is furniture", "Direction is outflow"],
            ExclusionRules: [],
            MerchantSignals: ["FURNITURE"],
            DirectionExpectation: CharacteristicsDirection.Outflow,
            AnalyticsTreatment: CharacteristicsAnalyticsTreatment.Expense,
            ConfidenceFloor: 0.65),
        new(
            TaxonomyCategoryId: null,
            TaxonomySubcategoryId: 100502,
            Description: "Mattresses and bedding sets.",
            UseCases: ["Mattress replacement"],
            InclusionRules: ["Item is a mattress or bedding", "Direction is outflow"],
            ExclusionRules: [],
            MerchantSignals: ["MATTRESS", "EMMA SLEEP"],
            DirectionExpectation: CharacteristicsDirection.Outflow,
            AnalyticsTreatment: CharacteristicsAnalyticsTreatment.Expense,
            ConfidenceFloor: 0.7),
        new(
            TaxonomyCategoryId: null,
            TaxonomySubcategoryId: 100503,
            Description: "Large appliances: washers, fridges, cookers.",
            UseCases: ["New washing machine"],
            InclusionRules: ["Item is a large household appliance", "Direction is outflow"],
            ExclusionRules: ["Consumer electronics belong to Electronics"],
            MerchantSignals: [],
            DirectionExpectation: CharacteristicsDirection.Outflow,
            AnalyticsTreatment: CharacteristicsAnalyticsTreatment.Expense,
            ConfidenceFloor: 0.6),
        new(
            TaxonomyCategoryId: null,
            TaxonomySubcategoryId: 100504,
            Description: "Small appliances: kettles, toasters, air fryers, vacuums.",
            UseCases: ["Air fryer purchase"],
            InclusionRules: ["Item is a small household appliance", "Direction is outflow"],
            ExclusionRules: [],
            MerchantSignals: [],
            DirectionExpectation: CharacteristicsDirection.Outflow,
            AnalyticsTreatment: CharacteristicsAnalyticsTreatment.Expense,
            ConfidenceFloor: 0.6),
        new(
            TaxonomyCategoryId: null,
            TaxonomySubcategoryId: 100505,
            Description: "Home-office furniture: desks, chairs, monitor arms.",
            UseCases: ["Ergonomic chair for the home office"],
            InclusionRules: ["Furniture serves the home workspace", "Direction is outflow"],
            ExclusionRules: ["Business-claimed purchases belong to Business Expenses"],
            MerchantSignals: [],
            DirectionExpectation: CharacteristicsDirection.Outflow,
            AnalyticsTreatment: CharacteristicsAnalyticsTreatment.Expense,
            ConfidenceFloor: 0.6),
        new(
            TaxonomyCategoryId: null,
            TaxonomySubcategoryId: 100506,
            Description: "Furnishing accents bought with the furniture: lamps, mirrors.",
            UseCases: ["Floor lamp with the new suite"],
            InclusionRules: ["Item furnishes rather than decorates", "Direction is outflow"],
            ExclusionRules: ["Pure decor belongs to Home Décor & Furnishings"],
            MerchantSignals: [],
            DirectionExpectation: CharacteristicsDirection.Outflow,
            AnalyticsTreatment: CharacteristicsAnalyticsTreatment.Expense,
            ConfidenceFloor: 0.55),
        new(
            TaxonomyCategoryId: null,
            TaxonomySubcategoryId: 100507,
            Description: "Curtains and blinds, made-to-measure or ready-made.",
            UseCases: ["Blackout blinds fitted"],
            InclusionRules: ["Item is window dressing", "Direction is outflow"],
            ExclusionRules: [],
            MerchantSignals: ["BLINDS", "CURTAINS"],
            DirectionExpectation: CharacteristicsDirection.Outflow,
            AnalyticsTreatment: CharacteristicsAnalyticsTreatment.Expense,
            ConfidenceFloor: 0.7),
        new(
            TaxonomyCategoryId: null,
            TaxonomySubcategoryId: 100508,
            Description: "Rugs and carpets bought as items.",
            UseCases: ["Living-room rug"],
            InclusionRules: ["Item is a rug or carpet", "Direction is outflow"],
            ExclusionRules: ["Fitted carpet installation belongs to Flooring"],
            MerchantSignals: ["RUGS", "CARPET"],
            DirectionExpectation: CharacteristicsDirection.Outflow,
            AnalyticsTreatment: CharacteristicsAnalyticsTreatment.Expense,
            ConfidenceFloor: 0.65),

        // -- 10060 Moving & Temporary Housing --
        new(
            TaxonomyCategoryId: null,
            TaxonomySubcategoryId: 100601,
            Description: "Professional movers.",
            UseCases: ["Moving company for the house move"],
            InclusionRules: ["Service moves your belongings", "Direction is outflow"],
            ExclusionRules: ["Self-drive vans belong to Van Rental"],
            MerchantSignals: ["REMOVALS", "MOVING COMPANY"],
            DirectionExpectation: CharacteristicsDirection.Outflow,
            AnalyticsTreatment: CharacteristicsAnalyticsTreatment.Expense,
            ConfidenceFloor: 0.7),
        new(
            TaxonomyCategoryId: null,
            TaxonomySubcategoryId: 100602,
            Description: "Van hire for a move.",
            UseCases: ["Self-drive van for moving day"],
            InclusionRules: ["Rental serves a move", "Direction is outflow"],
            ExclusionRules: ["Holiday car hire belongs to Travel"],
            MerchantSignals: ["VAN HIRE", "VAN RENTAL"],
            DirectionExpectation: CharacteristicsDirection.Outflow,
            AnalyticsTreatment: CharacteristicsAnalyticsTreatment.Expense,
            ConfidenceFloor: 0.7),
        new(
            TaxonomyCategoryId: null,
            TaxonomySubcategoryId: 100603,
            Description: "Boxes, tape, bubble wrap.",
            UseCases: ["Packing materials run"],
            InclusionRules: ["Goods are packing supplies", "Direction is outflow"],
            ExclusionRules: [],
            MerchantSignals: [],
            DirectionExpectation: CharacteristicsDirection.Outflow,
            AnalyticsTreatment: CharacteristicsAnalyticsTreatment.Expense,
            ConfidenceFloor: 0.55),
        new(
            TaxonomyCategoryId: null,
            TaxonomySubcategoryId: 100604,
            Description: "Self-storage unit rent.",
            UseCases: ["Monthly storage unit"],
            InclusionRules: ["Charge rents storage space", "Direction is outflow"],
            ExclusionRules: [],
            MerchantSignals: ["SELF STORAGE", "STORAGE UNIT", "NESTA"],
            DirectionExpectation: CharacteristicsDirection.Outflow,
            AnalyticsTreatment: CharacteristicsAnalyticsTreatment.Expense,
            ConfidenceFloor: 0.75),
        new(
            TaxonomyCategoryId: null,
            TaxonomySubcategoryId: 100605,
            Description: "A roof between roofs: short stays because of a move.",
            UseCases: ["Two weeks in a B&B between homes"],
            InclusionRules: ["Stay bridges a housing gap rather than a holiday", "Direction is outflow"],
            ExclusionRules: ["Holiday stays belong to Travel Lodging"],
            MerchantSignals: [],
            DirectionExpectation: CharacteristicsDirection.Outflow,
            AnalyticsTreatment: CharacteristicsAnalyticsTreatment.Expense,
            ConfidenceFloor: 0.55),
        new(
            TaxonomyCategoryId: null,
            TaxonomySubcategoryId: 100606,
            Description: "Getting the new place livable: first-fill costs after moving in.",
            UseCases: ["Move-in day essentials haul"],
            InclusionRules: ["Purchases set up the new home shortly after a move", "Direction is outflow"],
            ExclusionRules: ["Furniture belongs to Furniture & Appliances"],
            MerchantSignals: [],
            DirectionExpectation: CharacteristicsDirection.Outflow,
            AnalyticsTreatment: CharacteristicsAnalyticsTreatment.Expense,
            ConfidenceFloor: 0.5),

        // -- 10070 Security & Home Services --
        new(
            TaxonomyCategoryId: null,
            TaxonomySubcategoryId: 100701,
            Description: "Buying and installing a home alarm system.",
            UseCases: ["Alarm system supply and fit"],
            InclusionRules: ["Purchase is a home security system", "Direction is outflow"],
            ExclusionRules: ["Ongoing monitoring belongs to Monitoring Fees"],
            MerchantSignals: [],
            DirectionExpectation: CharacteristicsDirection.Outflow,
            AnalyticsTreatment: CharacteristicsAnalyticsTreatment.Expense,
            ConfidenceFloor: 0.6),
        new(
            TaxonomyCategoryId: null,
            TaxonomySubcategoryId: 100702,
            Description: "Monthly alarm monitoring subscriptions.",
            UseCases: ["Monitored alarm direct debit"],
            InclusionRules: ["Charge is recurring security monitoring", "Direction is outflow"],
            ExclusionRules: [],
            MerchantSignals: [],
            DirectionExpectation: CharacteristicsDirection.Outflow,
            AnalyticsTreatment: CharacteristicsAnalyticsTreatment.Expense,
            ConfidenceFloor: 0.6),
        new(
            TaxonomyCategoryId: null,
            TaxonomySubcategoryId: 100703,
            Description: "Cameras: CCTV, doorbell cams.",
            UseCases: ["Video doorbell purchase"],
            InclusionRules: ["Item is home camera equipment", "Direction is outflow"],
            ExclusionRules: ["Ring/Nest subscriptions belong to Software & Digital Tools"],
            MerchantSignals: ["CCTV"],
            DirectionExpectation: CharacteristicsDirection.Outflow,
            AnalyticsTreatment: CharacteristicsAnalyticsTreatment.Expense,
            ConfidenceFloor: 0.65),
        new(
            TaxonomyCategoryId: null,
            TaxonomySubcategoryId: 100704,
            Description: "Servicing the alarm.",
            UseCases: ["Annual alarm service visit"],
            InclusionRules: ["Service maintains the alarm system", "Direction is outflow"],
            ExclusionRules: [],
            MerchantSignals: ["ALARM SERVICE"],
            DirectionExpectation: CharacteristicsDirection.Outflow,
            AnalyticsTreatment: CharacteristicsAnalyticsTreatment.Expense,
            ConfidenceFloor: 0.65),
        new(
            TaxonomyCategoryId: null,
            TaxonomySubcategoryId: 100705,
            Description: "Key cutting at the counter.",
            UseCases: ["Spare keys cut"],
            InclusionRules: ["Purchase is key cutting", "Direction is outflow"],
            ExclusionRules: ["Lockouts belong to Locksmith"],
            MerchantSignals: ["KEY CUTTING", "TIMPSON"],
            DirectionExpectation: CharacteristicsDirection.Outflow,
            AnalyticsTreatment: CharacteristicsAnalyticsTreatment.Expense,
            ConfidenceFloor: 0.7),
        new(
            TaxonomyCategoryId: null,
            TaxonomySubcategoryId: 100706,
            Description: "Concierge and building services billed to the resident.",
            UseCases: ["Building concierge charge"],
            InclusionRules: ["Charge is a residential building service", "Direction is outflow"],
            ExclusionRules: ["Management fees belong to Property Taxes & Fees"],
            MerchantSignals: [],
            DirectionExpectation: CharacteristicsDirection.Outflow,
            AnalyticsTreatment: CharacteristicsAnalyticsTreatment.Expense,
            ConfidenceFloor: 0.5),

        // -- 10080 Other Housing (deterministic-only: honest catch-alls the
        // AI may label but never infer) --
        new(
            TaxonomyCategoryId: 10080,
            TaxonomySubcategoryId: null,
            Description: "Housing costs that fit nowhere else; a human choice, never an AI guess.",
            UseCases: ["Genuinely unclassifiable housing expense"],
            InclusionRules: ["Only deterministic rules or the user may assign this catch-all"],
            ExclusionRules: ["Anything matching a specific housing definition belongs there"],
            MerchantSignals: [],
            DirectionExpectation: CharacteristicsDirection.Outflow,
            AnalyticsTreatment: CharacteristicsAnalyticsTreatment.Expense,
            ConfidenceFloor: null),
        new(
            TaxonomyCategoryId: null,
            TaxonomySubcategoryId: 100801,
            Description: "Miscellaneous housing spend, user-assigned.",
            UseCases: ["Housing one-off with no better node"],
            InclusionRules: ["Only deterministic rules or the user may assign this catch-all"],
            ExclusionRules: [],
            MerchantSignals: [],
            DirectionExpectation: CharacteristicsDirection.Outflow,
            AnalyticsTreatment: CharacteristicsAnalyticsTreatment.Expense,
            ConfidenceFloor: null),
        new(
            TaxonomyCategoryId: null,
            TaxonomySubcategoryId: 100802,
            Description: "Housing-related fines and penalties: late estate fees, breach charges.",
            UseCases: ["Late fee on a management charge"],
            InclusionRules: ["Charge is punitive and housing-related", "Direction is outflow"],
            ExclusionRules: ["Utility late fees belong to Utility Setup & Service Fees"],
            MerchantSignals: [],
            DirectionExpectation: CharacteristicsDirection.Outflow,
            AnalyticsTreatment: CharacteristicsAnalyticsTreatment.Expense,
            ConfidenceFloor: 0.6),
        new(
            TaxonomyCategoryId: null,
            TaxonomySubcategoryId: 100803,
            Description: "Unclassified housing expense, user-assigned.",
            UseCases: ["Awaiting proper classification"],
            InclusionRules: ["Only deterministic rules or the user may assign this catch-all"],
            ExclusionRules: [],
            MerchantSignals: [],
            DirectionExpectation: CharacteristicsDirection.Outflow,
            AnalyticsTreatment: CharacteristicsAnalyticsTreatment.Expense,
            ConfidenceFloor: null)
    ];
}
