namespace NSFinance.Shared.Taxonomy;

// Full-coverage characteristics: Debt & Loans (170), Savings & Investments
// (180), Transfers (920). Semantics here carry the money-truth rules: debt
// interest and fees are expenses; repayments to linked own liabilities are
// the transfer engine's territory (the 920 nodes, deterministic-only);
// contributions to own savings and investments are neutral movements that
// still require movement evidence before the policy engine neutralizes them.
public static partial class CategoryCharacteristicsCatalog
{
    private static readonly IReadOnlyList<CategoryCharacteristicsDefinition> DebtSavingsTransfersDefinitions =
    [
        // -- 17010 Credit Cards --
        new(17010, null, "Servicing credit cards: payments, interest, card fees.",
            ["Monthly card payment", "Interest charged"],
            ["Charge relates to a credit card you hold", "Direction is outflow"],
            ["Verified transfers to a linked own card are decided deterministically by the transfer engine"],
            [], CharacteristicsDirection.Outflow, CharacteristicsAnalyticsTreatment.Expense, 0.55),
        new(null, 170101, "Paying the credit card bill when the card is not linked.",
            ["Card bill payment"],
            ["Payment reduces a credit card balance", "Direction is outflow"],
            ["Linked own-card payments are decided deterministically as Credit Card Payment Transfer"],
            [], CharacteristicsDirection.Outflow, CharacteristicsAnalyticsTreatment.Expense, 0.5),
        new(null, 170102, "Credit card interest.",
            ["Interest line on the statement"],
            ["Charge is credit card interest", "Direction is outflow"],
            [],
            [], CharacteristicsDirection.Outflow, CharacteristicsAnalyticsTreatment.Expense, 0.55),
        new(null, 170103, "Late fees on cards.",
            ["Late payment fee"],
            ["Charge is a card late fee", "Direction is outflow"],
            [],
            [], CharacteristicsDirection.Outflow, CharacteristicsAnalyticsTreatment.Expense, 0.55),
        new(null, 170104, "Cash advance fees.",
            ["Fee for a card cash advance"],
            ["Charge is a cash advance fee", "Direction is outflow"],
            [],
            ["CASH ADVANCE"], CharacteristicsDirection.Outflow, CharacteristicsAnalyticsTreatment.Expense, 0.55),
        new(null, 170105, "Balance transfer fees.",
            ["Fee on a balance transfer"],
            ["Charge is a balance transfer fee", "Direction is outflow"],
            [],
            [], CharacteristicsDirection.Outflow, CharacteristicsAnalyticsTreatment.Expense, 0.5),

        // -- 17020 Personal Loans --
        new(17020, null, "Personal borrowing: repayments and their costs.",
            ["Monthly loan repayment"],
            ["Charge services a personal loan", "Direction is outflow"],
            [],
            [], CharacteristicsDirection.Outflow, CharacteristicsAnalyticsTreatment.Expense, 0.55),
        new(null, 170201, "Personal loan repayments.",
            ["Loan direct debit"],
            ["Payment repays a personal loan", "Direction is outflow"],
            [],
            [], CharacteristicsDirection.Outflow, CharacteristicsAnalyticsTreatment.Expense, 0.5),
        new(null, 170202, "Personal loan interest identified separately.",
            ["Interest portion of a loan"],
            ["Charge is loan interest", "Direction is outflow"],
            [],
            [], CharacteristicsDirection.Outflow, CharacteristicsAnalyticsTreatment.Expense, 0.5),
        new(null, 170203, "Payday and short-term high-cost loans.",
            ["Payday loan repayment"],
            ["Payment services a payday loan", "Direction is outflow"],
            [],
            ["PAYDAY"], CharacteristicsDirection.Outflow, CharacteristicsAnalyticsTreatment.Expense, 0.6),
        new(null, 170204, "Buy-now-pay-later instalments.",
            ["BNPL instalment"],
            ["Payment is a BNPL instalment", "Direction is outflow"],
            [],
            ["KLARNA", "CLEARPAY", "HUMM"], CharacteristicsDirection.Outflow, CharacteristicsAnalyticsTreatment.Expense, 0.75),
        new(null, 170205, "Retail instalment plans.",
            ["Store instalment payment"],
            ["Payment is a retail instalment plan", "Direction is outflow"],
            [],
            [], CharacteristicsDirection.Outflow, CharacteristicsAnalyticsTreatment.Expense, 0.5),

        // -- 17030 Student Loans --
        new(17030, null, "Student borrowing: repayments and servicing.",
            ["Student loan repayment"],
            ["Charge services study debt", "Direction is outflow"],
            [],
            [], CharacteristicsDirection.Outflow, CharacteristicsAnalyticsTreatment.Expense, 0.55),
        new(null, 170301, "Student loan repayments.",
            ["Monthly student loan payment"],
            ["Payment repays a student loan", "Direction is outflow"],
            [],
            ["STUDENT LOAN"], CharacteristicsDirection.Outflow, CharacteristicsAnalyticsTreatment.Expense, 0.6),
        new(null, 170302, "Student loan interest.",
            ["Interest on study debt"],
            ["Charge is student loan interest", "Direction is outflow"],
            [],
            [], CharacteristicsDirection.Outflow, CharacteristicsAnalyticsTreatment.Expense, 0.5),
        new(null, 170303, "Tuition financing plans.",
            ["Tuition instalment plan payment"],
            ["Payment finances tuition", "Direction is outflow"],
            ["Direct tuition belongs to Education"],
            [], CharacteristicsDirection.Outflow, CharacteristicsAnalyticsTreatment.Expense, 0.5),
        new(null, 170304, "Loan servicing fees on study debt.",
            ["Servicing fee"],
            ["Charge is a loan servicing fee", "Direction is outflow"],
            [],
            [], CharacteristicsDirection.Outflow, CharacteristicsAnalyticsTreatment.Expense, 0.5),

        // -- 17040 Auto & Vehicle Loans --
        new(17040, null, "Vehicle finance: repayments and interest.",
            ["Car finance direct debit"],
            ["Charge services vehicle finance", "Direction is outflow"],
            ["Lease payments belong to Transportation's Lease Payment"],
            [], CharacteristicsDirection.Outflow, CharacteristicsAnalyticsTreatment.Expense, 0.55),
        new(null, 170401, "Car loan payments.",
            ["Car loan instalment"],
            ["Payment repays a car loan", "Direction is outflow"],
            [],
            [], CharacteristicsDirection.Outflow, CharacteristicsAnalyticsTreatment.Expense, 0.5),
        new(null, 170402, "Motorcycle loan payments.",
            ["Bike loan instalment"],
            ["Payment repays a motorcycle loan", "Direction is outflow"],
            [],
            [], CharacteristicsDirection.Outflow, CharacteristicsAnalyticsTreatment.Expense, 0.5),
        new(null, 170403, "Vehicle loan interest.",
            ["Interest on vehicle finance"],
            ["Charge is vehicle loan interest", "Direction is outflow"],
            [],
            [], CharacteristicsDirection.Outflow, CharacteristicsAnalyticsTreatment.Expense, 0.5),

        // -- 17050 Mortgage & Property Debt --
        new(17050, null, "Property debt beyond the monthly mortgage: equity products, refinancing.",
            ["Home equity loan payment"],
            ["Charge services property debt", "Direction is outflow"],
            ["The regular mortgage payment belongs to Housing's Rent & Mortgage"],
            [], CharacteristicsDirection.Outflow, CharacteristicsAnalyticsTreatment.Expense, 0.5),
        new(null, 170501, "Mortgage principal viewed as debt service.",
            ["Principal portion recorded against the debt"],
            ["Payment reduces mortgage principal", "Direction is outflow"],
            ["Everyday categorization prefers Housing's Mortgage Principal"],
            [], CharacteristicsDirection.Outflow, CharacteristicsAnalyticsTreatment.Expense, 0.5),
        new(null, 170502, "Mortgage interest viewed as debt service.",
            ["Interest portion recorded against the debt"],
            ["Charge is mortgage interest", "Direction is outflow"],
            ["Everyday categorization prefers Housing's Mortgage Interest"],
            [], CharacteristicsDirection.Outflow, CharacteristicsAnalyticsTreatment.Expense, 0.5),
        new(null, 170503, "Refinancing fees.",
            ["Switching fee on remortgage"],
            ["Charge is a refinancing fee", "Direction is outflow"],
            [],
            [], CharacteristicsDirection.Outflow, CharacteristicsAnalyticsTreatment.Expense, 0.5),
        new(null, 170504, "Home equity loan payments.",
            ["Equity loan instalment"],
            ["Payment services a home equity loan", "Direction is outflow"],
            [],
            [], CharacteristicsDirection.Outflow, CharacteristicsAnalyticsTreatment.Expense, 0.5),
        new(null, 170505, "Home equity line payments.",
            ["Credit line repayment"],
            ["Payment services a home equity line", "Direction is outflow"],
            [],
            [], CharacteristicsDirection.Outflow, CharacteristicsAnalyticsTreatment.Expense, 0.5),

        // -- 17060 Family & Informal Debt --
        new(17060, null, "Paying back people: family and friend loans.",
            ["Repaying a family loan"],
            ["Payment repays informal borrowing", "Direction is outflow"],
            ["Gifts belong to Gifts & Donations; shared-cost settlements are reference-lane decisions"],
            [], CharacteristicsDirection.Outflow, CharacteristicsAnalyticsTreatment.Expense, 0.5),
        new(null, 170601, "Repaying family.",
            ["Monthly payment back to a parent"],
            ["Payment repays a family loan", "Direction is outflow"],
            [],
            [], CharacteristicsDirection.Outflow, CharacteristicsAnalyticsTreatment.Expense, 0.5),
        new(null, 170602, "Repaying friends.",
            ["Paying a friend back"],
            ["Payment repays a friend", "Direction is outflow"],
            [],
            [], CharacteristicsDirection.Outflow, CharacteristicsAnalyticsTreatment.Expense, 0.5),
        new(null, 170603, "Costs on informal borrowing.",
            ["Agreed interest to family"],
            ["Charge is a cost of informal borrowing", "Direction is outflow"],
            [],
            [], CharacteristicsDirection.Outflow, CharacteristicsAnalyticsTreatment.Expense, 0.5),

        // -- 17070 Collections & Penalties --
        new(17070, null, "When debt goes wrong: collections, settlements, court orders.",
            ["Collection agency payment"],
            ["Payment services collected or penalized debt", "Direction is outflow"],
            [],
            ["CABOT"], CharacteristicsDirection.Outflow, CharacteristicsAnalyticsTreatment.Expense, 0.55),
        new(null, 170701, "Payments to debt collectors.",
            ["Agency instalment"],
            ["Payment goes to a debt collector", "Direction is outflow"],
            [],
            [], CharacteristicsDirection.Outflow, CharacteristicsAnalyticsTreatment.Expense, 0.5),
        new(null, 170702, "Debt settlements.",
            ["Settlement lump sum"],
            ["Payment settles a debt", "Direction is outflow"],
            [],
            [], CharacteristicsDirection.Outflow, CharacteristicsAnalyticsTreatment.Expense, 0.5),
        new(null, 170703, "Arrears repayments.",
            ["Arrears plan instalment"],
            ["Payment clears arrears", "Direction is outflow"],
            ["Utility arrears belong to their utility"],
            [], CharacteristicsDirection.Outflow, CharacteristicsAnalyticsTreatment.Expense, 0.5),
        new(null, 170704, "Court-ordered debt payments.",
            ["Instalment order payment"],
            ["Payment is court-ordered debt", "Direction is outflow"],
            [],
            [], CharacteristicsDirection.Outflow, CharacteristicsAnalyticsTreatment.Expense, 0.5),

        // -- 17080 Other Debt & Loans (real activities + catch-all) --
        new(null, 170801, "Debt consolidation payments when the target is not linked.",
            ["Consolidation loan payment"],
            ["Payment services a consolidation loan", "Direction is outflow"],
            ["Linked consolidations are decided deterministically as Debt Consolidation Transfer"],
            [], CharacteristicsDirection.Outflow, CharacteristicsAnalyticsTreatment.Expense, 0.5),
        new(null, 170802, "Loan application fees.",
            ["Application fee"],
            ["Charge is a loan application fee", "Direction is outflow"],
            [],
            [], CharacteristicsDirection.Outflow, CharacteristicsAnalyticsTreatment.Expense, 0.5),
        new(null, 170803, "Other loan costs, user-assigned.",
            ["Loan one-off with no better node"],
            ["Only deterministic rules or the user may assign this catch-all"],
            [],
            [], CharacteristicsDirection.Outflow, CharacteristicsAnalyticsTreatment.Expense, null),

        // -- 18010 Cash Savings (180102 pair already defined) --
        new(18010, null, "Putting money aside in cash form.",
            ["Standing order to savings"],
            ["Movement funds own cash savings", "Direction is outflow",
             "Movement evidence (own-name reference, savings keyword, or linked pairing) is required before neutralization"],
            ["Third-party payees are not savings"],
            [], CharacteristicsDirection.Outflow, CharacteristicsAnalyticsTreatment.NeutralTransfer, 0.75),
        new(null, 180101, "Emergency fund contributions.",
            ["Emergency fund top-up"],
            ["Movement funds an emergency fund", "Direction is outflow",
             "Movement evidence is required before neutralization"],
            [],
            ["EMERGENCY FUND"], CharacteristicsDirection.Outflow, CharacteristicsAnalyticsTreatment.NeutralTransfer, 0.75),
        new(null, 180103, "Sinking fund contributions.",
            ["Sinking fund transfer"],
            ["Movement funds a named sinking fund", "Direction is outflow",
             "Movement evidence is required before neutralization"],
            [],
            ["SINKING FUND"], CharacteristicsDirection.Outflow, CharacteristicsAnalyticsTreatment.NeutralTransfer, 0.75),
        new(null, 180104, "Holiday savings.",
            ["Holiday fund transfer"],
            ["Movement funds holiday savings", "Direction is outflow",
             "Movement evidence is required before neutralization"],
            [],
            ["HOLIDAY FUND"], CharacteristicsDirection.Outflow, CharacteristicsAnalyticsTreatment.NeutralTransfer, 0.75),
        new(null, 180105, "Deposit savings for a home.",
            ["House deposit fund transfer"],
            ["Movement funds a house deposit", "Direction is outflow",
             "Movement evidence is required before neutralization"],
            [],
            ["HOUSE FUND", "DEPOSIT FUND"], CharacteristicsDirection.Outflow, CharacteristicsAnalyticsTreatment.NeutralTransfer, 0.75),

        // -- 18020 Retirement --
        new(18020, null, "Funding retirement: pensions and retirement accounts.",
            ["Monthly pension contribution"],
            ["Movement funds retirement savings", "Direction is outflow",
             "Movement evidence is required before neutralization"],
            ["Retirement account fees belong to Retirement Fees"],
            ["PENSION"], CharacteristicsDirection.Outflow, CharacteristicsAnalyticsTreatment.NeutralTransfer, 0.7),
        new(null, 180201, "Pension contributions.",
            ["PRSA contribution"],
            ["Movement is a pension contribution", "Direction is outflow",
             "Movement evidence is required before neutralization"],
            [],
            ["PRSA"], CharacteristicsDirection.Outflow, CharacteristicsAnalyticsTreatment.NeutralTransfer, 0.7),
        new(null, 180202, "Retirement account contributions.",
            ["Retirement account lodgement"],
            ["Movement funds a retirement account", "Direction is outflow",
             "Movement evidence is required before neutralization"],
            [],
            [], CharacteristicsDirection.Outflow, CharacteristicsAnalyticsTreatment.NeutralTransfer, 0.65),
        new(null, 180203, "Topping up to capture an employer match.",
            ["AVC top-up"],
            ["Movement is a matched retirement top-up", "Direction is outflow",
             "Movement evidence is required before neutralization"],
            [],
            ["AVC "], CharacteristicsDirection.Outflow, CharacteristicsAnalyticsTreatment.NeutralTransfer, 0.65),
        new(null, 180204, "Retirement account fees.",
            ["Pension management fee"],
            ["Charge is a retirement account fee", "Direction is outflow"],
            [],
            [], CharacteristicsDirection.Outflow, CharacteristicsAnalyticsTreatment.Expense, 0.5),

        // -- 18030 Brokerage & Investing --
        new(18030, null, "Moving money into investments.",
            ["Brokerage deposit"],
            ["Movement funds an investment account or buys assets", "Direction is outflow",
             "Movement evidence is required before neutralization"],
            ["Platform and trading fees belong to Investment Costs"],
            ["DEGIRO", "TRADING 212", "ETORO", "INTERACTIVE BROKERS"], CharacteristicsDirection.Outflow, CharacteristicsAnalyticsTreatment.NeutralTransfer, 0.75),
        new(null, 180301, "Brokerage account contributions.",
            ["Deposit to the broker"],
            ["Movement funds a brokerage account", "Direction is outflow",
             "Movement evidence is required before neutralization"],
            [],
            [], CharacteristicsDirection.Outflow, CharacteristicsAnalyticsTreatment.NeutralTransfer, 0.65),
        new(null, 180302, "ETF purchases.",
            ["Monthly ETF buy"],
            ["Purchase is an ETF", "Direction is outflow",
             "Movement evidence is required before neutralization"],
            [],
            [], CharacteristicsDirection.Outflow, CharacteristicsAnalyticsTreatment.NeutralTransfer, 0.6),
        new(null, 180303, "Stock purchases.",
            ["Share purchase"],
            ["Purchase is company stock", "Direction is outflow",
             "Movement evidence is required before neutralization"],
            [],
            [], CharacteristicsDirection.Outflow, CharacteristicsAnalyticsTreatment.NeutralTransfer, 0.6),
        new(null, 180304, "Mutual fund purchases.",
            ["Fund units purchase"],
            ["Purchase is a mutual fund", "Direction is outflow",
             "Movement evidence is required before neutralization"],
            [],
            [], CharacteristicsDirection.Outflow, CharacteristicsAnalyticsTreatment.NeutralTransfer, 0.6),
        new(null, 180305, "Bond purchases.",
            ["State savings or bond purchase"],
            ["Purchase is bonds", "Direction is outflow",
             "Movement evidence is required before neutralization"],
            [],
            ["STATE SAVINGS"], CharacteristicsDirection.Outflow, CharacteristicsAnalyticsTreatment.NeutralTransfer, 0.7),
        new(null, 180306, "Crypto purchases.",
            ["Exchange deposit or coin buy"],
            ["Purchase is cryptocurrency", "Direction is outflow",
             "Movement evidence is required before neutralization"],
            [],
            ["COINBASE", "BINANCE", "KRAKEN"], CharacteristicsDirection.Outflow, CharacteristicsAnalyticsTreatment.NeutralTransfer, 0.75),
        new(null, 180307, "Robo-advisor contributions.",
            ["Automated portfolio deposit"],
            ["Movement funds a robo-advisor", "Direction is outflow",
             "Movement evidence is required before neutralization"],
            [],
            [], CharacteristicsDirection.Outflow, CharacteristicsAnalyticsTreatment.NeutralTransfer, 0.6),

        // -- 18040 Investment Costs --
        new(18040, null, "The costs of investing: fees at every layer.",
            ["Platform fee charge"],
            ["Charge is an investing cost", "Direction is outflow"],
            [],
            [], CharacteristicsDirection.Outflow, CharacteristicsAnalyticsTreatment.Expense, 0.55),
        new(null, 180401, "Per-trade fees.",
            ["Trade commission"],
            ["Charge is a trading fee", "Direction is outflow"],
            [],
            [], CharacteristicsDirection.Outflow, CharacteristicsAnalyticsTreatment.Expense, 0.5),
        new(null, 180402, "Platform fees.",
            ["Quarterly platform charge"],
            ["Charge is a platform fee", "Direction is outflow"],
            [],
            [], CharacteristicsDirection.Outflow, CharacteristicsAnalyticsTreatment.Expense, 0.5),
        new(null, 180403, "Custody fees.",
            ["Custody charge"],
            ["Charge is a custody fee", "Direction is outflow"],
            [],
            [], CharacteristicsDirection.Outflow, CharacteristicsAnalyticsTreatment.Expense, 0.5),
        new(null, 180404, "Advisory fees.",
            ["Adviser retainer"],
            ["Charge is investment advice", "Direction is outflow"],
            [],
            [], CharacteristicsDirection.Outflow, CharacteristicsAnalyticsTreatment.Expense, 0.5),
        new(null, 180405, "Fund management fees charged to cash.",
            ["Management fee debit"],
            ["Charge is fund management", "Direction is outflow"],
            [],
            [], CharacteristicsDirection.Outflow, CharacteristicsAnalyticsTreatment.Expense, 0.5),

        // -- 18050 Education & Future Funds --
        new(18050, null, "Saving for someone's future: college and child funds.",
            ["College fund transfer"],
            ["Movement funds education or future savings", "Direction is outflow",
             "Movement evidence is required before neutralization"],
            [],
            ["COLLEGE FUND"], CharacteristicsDirection.Outflow, CharacteristicsAnalyticsTreatment.NeutralTransfer, 0.7),
        new(null, 180501, "College savings.",
            ["College fund contribution"],
            ["Movement funds college savings", "Direction is outflow",
             "Movement evidence is required before neutralization"],
            [],
            [], CharacteristicsDirection.Outflow, CharacteristicsAnalyticsTreatment.NeutralTransfer, 0.65),
        new(null, 180502, "Child savings accounts.",
            ["Child account lodgement"],
            ["Movement funds a child's savings", "Direction is outflow",
             "Movement evidence is required before neutralization"],
            [],
            [], CharacteristicsDirection.Outflow, CharacteristicsAnalyticsTreatment.NeutralTransfer, 0.65),
        new(null, 180503, "Trust fund contributions.",
            ["Trust contribution"],
            ["Movement funds a trust", "Direction is outflow",
             "Movement evidence is required before neutralization"],
            [],
            [], CharacteristicsDirection.Outflow, CharacteristicsAnalyticsTreatment.NeutralTransfer, 0.6),

        // -- 18060 Other Savings & Investments --
        new(null, 180601, "Gold and precious metals as investment.",
            ["Bullion purchase"],
            ["Purchase is investment metals", "Direction is outflow",
             "Movement evidence is required before neutralization"],
            [],
            ["BULLION"], CharacteristicsDirection.Outflow, CharacteristicsAnalyticsTreatment.NeutralTransfer, 0.65),
        new(null, 180602, "Collectibles bought as investment.",
            ["Investment-grade collectible"],
            ["Purchase is an investment collectible", "Direction is outflow",
             "Movement evidence is required before neutralization"],
            ["Hobby collecting belongs to Collecting & Specialty Hobbies"],
            [], CharacteristicsDirection.Outflow, CharacteristicsAnalyticsTreatment.NeutralTransfer, 0.55),
        new(null, 180603, "Taxes on investments paid from cash.",
            ["Exit tax payment"],
            ["Charge is investment tax", "Direction is outflow"],
            ["General taxes belong to the Taxes domain"],
            [], CharacteristicsDirection.Outflow, CharacteristicsAnalyticsTreatment.Expense, 0.5),
        new(null, 180604, "Other investment transfers, user-assigned.",
            ["Investment movement with no better node"],
            ["Only deterministic rules or the user may assign this catch-all"],
            [],
            [], CharacteristicsDirection.Outflow, CharacteristicsAnalyticsTreatment.NeutralTransfer, null),

        // -- 920 Transfers: all deterministic-only (the transfer engine and
        // linked-account pairing decide; the AI may label but never infer) --
        new(null, 920101, "Movement between your own linked bank accounts.",
            ["Own-account transfer"],
            ["Decided deterministically by verified linked-account pairing"],
            [],
            [], CharacteristicsDirection.Either, CharacteristicsAnalyticsTreatment.NeutralTransfer, null),
        new(null, 920105, "Currency conversion between your own balances.",
            ["FX conversion between own balances"],
            ["Decided deterministically by the transfer engine"],
            [],
            [], CharacteristicsDirection.Either, CharacteristicsAnalyticsTreatment.NeutralTransfer, null),
        new(null, 920106, "Other internal money movement.",
            ["Internal movement with no better node"],
            ["Decided deterministically by the transfer engine or assigned by the user"],
            [],
            [], CharacteristicsDirection.Either, CharacteristicsAnalyticsTreatment.NeutralTransfer, null),
        new(92020, null, "Transfers that service your own liabilities.",
            ["Payment to a linked credit card"],
            ["Decided deterministically by verified liability pairing"],
            [],
            [], CharacteristicsDirection.Either, CharacteristicsAnalyticsTreatment.NeutralTransfer, null),
        new(null, 920201, "Verified payments to your own credit card.",
            ["Linked card payment"],
            ["Decided deterministically by verified card pairing"],
            [],
            [], CharacteristicsDirection.Either, CharacteristicsAnalyticsTreatment.NeutralTransfer, null),
        new(null, 920202, "Verified transfers to your own loan accounts.",
            ["Linked loan payment"],
            ["Decided deterministically by verified loan pairing"],
            [],
            [], CharacteristicsDirection.Either, CharacteristicsAnalyticsTreatment.NeutralTransfer, null),
        new(null, 920203, "Verified debt consolidation transfers.",
            ["Linked consolidation movement"],
            ["Decided deterministically by verified pairing"],
            [],
            [], CharacteristicsDirection.Either, CharacteristicsAnalyticsTreatment.NeutralTransfer, null),
        new(92030, null, "Cash crossing the ledger boundary.",
            ["ATM withdrawal"],
            ["Decided deterministically by the transfer engine"],
            [],
            [], CharacteristicsDirection.Either, CharacteristicsAnalyticsTreatment.NeutralTransfer, null),
        new(null, 920301, "Cash withdrawals.",
            ["ATM withdrawal"],
            ["Decided deterministically from ATM and withdrawal markers"],
            [],
            [], CharacteristicsDirection.Outflow, CharacteristicsAnalyticsTreatment.NeutralTransfer, null),
        new(null, 920302, "Cash deposits.",
            ["Lodgement at the branch or post office"],
            ["Decided deterministically from lodgement markers"],
            [],
            [], CharacteristicsDirection.Inflow, CharacteristicsAnalyticsTreatment.NeutralTransfer, null)
    ];
}
