namespace NSFinance.Shared.Taxonomy;

// Full-coverage characteristics: Entertainment & Hobbies (210) and Travel
// (220) - categories and subcategories, including the new Gambling &
// Betting category born of the 2026-07-22 completeness audit.
public static partial class CategoryCharacteristicsCatalog
{
    private static readonly IReadOnlyList<CategoryCharacteristicsDefinition> EntertainmentTravelDefinitions =
    [
        // -- 21010 Events & Outings (210101 Cinema already defined) --
        new(21010, null, "Going out: shows, matches, days out.",
            ["Concert tickets", "Museum visit"],
            ["Charge is an event or outing", "Direction is outflow"],
            [],
            ["TICKETMASTER", "EVENTBRITE"], CharacteristicsDirection.Outflow, CharacteristicsAnalyticsTreatment.Expense, 0.7),
        new(null, 210102, "Concert and gig tickets.",
            ["Gig tickets"],
            ["Charge is live music", "Direction is outflow"],
            [],
            [], CharacteristicsDirection.Outflow, CharacteristicsAnalyticsTreatment.Expense, 0.55),
        new(null, 210103, "Theatre tickets.",
            ["Play or musical tickets"],
            ["Charge is theatre", "Direction is outflow"],
            [],
            ["THEATRE", "GAIETY", "BORD GAIS ENERGY THEATRE"], CharacteristicsDirection.Outflow, CharacteristicsAnalyticsTreatment.Expense, 0.6),
        new(null, 210104, "Museums and galleries.",
            ["Exhibition entry"],
            ["Charge is a museum or gallery", "Direction is outflow"],
            [],
            ["MUSEUM", "GALLERY"], CharacteristicsDirection.Outflow, CharacteristicsAnalyticsTreatment.Expense, 0.6),
        new(null, 210105, "Theme and amusement parks.",
            ["Theme park day"],
            ["Charge is a theme park", "Direction is outflow"],
            [],
            ["TAYTO PARK", "EMERALD PARK"], CharacteristicsDirection.Outflow, CharacteristicsAnalyticsTreatment.Expense, 0.7),
        new(null, 210106, "Festivals.",
            ["Festival weekend ticket"],
            ["Charge is a festival", "Direction is outflow"],
            [],
            ["FESTIVAL"], CharacteristicsDirection.Outflow, CharacteristicsAnalyticsTreatment.Expense, 0.6),
        new(null, 210107, "Sports event tickets.",
            ["Match tickets"],
            ["Charge is attending sport", "Direction is outflow"],
            ["Playing sport belongs to Sports & Recreation"],
            [], CharacteristicsDirection.Outflow, CharacteristicsAnalyticsTreatment.Expense, 0.55),

        // -- 21020 Gaming subs (category already defined) --
        new(null, 210201, "Buying video games.",
            ["New game purchase"],
            ["Purchase is a video game", "Direction is outflow"],
            [],
            ["CDKEYS", "GOG.COM"], CharacteristicsDirection.Outflow, CharacteristicsAnalyticsTreatment.Expense, 0.65),
        new(null, 210202, "In-game purchases and game-content payments.",
            ["Season pass or in-game currency"],
            ["Purchase is in-game content", "Direction is outflow"],
            [],
            ["G2G.COM"], CharacteristicsDirection.Outflow, CharacteristicsAnalyticsTreatment.Expense, 0.6),
        new(null, 210203, "Consoles.",
            ["Console purchase"],
            ["Purchase is a games console", "Direction is outflow"],
            ["General electronics belong to Electronics"],
            [], CharacteristicsDirection.Outflow, CharacteristicsAnalyticsTreatment.Expense, 0.55),
        new(null, 210204, "Gaming accessories: controllers, headsets.",
            ["New controller"],
            ["Purchase is gaming accessories", "Direction is outflow"],
            [],
            [], CharacteristicsDirection.Outflow, CharacteristicsAnalyticsTreatment.Expense, 0.5),
        new(null, 210205, "Online gaming subscriptions.",
            ["Online play subscription"],
            ["Charge is an online gaming subscription", "Direction is outflow"],
            ["Game-platform storefront purchases belong to Video Games"],
            ["XBOX GAME PASS", "PLAYSTATION PLUS", "NINTENDO ONLINE"], CharacteristicsDirection.Outflow, CharacteristicsAnalyticsTreatment.Expense, 0.7),

        // -- 21030 Arts & Crafts --
        new(21030, null, "Making things: art, craft, and maker supplies.",
            ["Art supplies haul"],
            ["Purchase is arts or crafts materials", "Direction is outflow"],
            [],
            [], CharacteristicsDirection.Outflow, CharacteristicsAnalyticsTreatment.Expense, 0.6),
        new(null, 210301, "Art supplies.",
            ["Paints and brushes"],
            ["Purchase is art supplies", "Direction is outflow"],
            [],
            ["ART SUPPLIES", "EASON ART"], CharacteristicsDirection.Outflow, CharacteristicsAnalyticsTreatment.Expense, 0.6),
        new(null, 210302, "Craft supplies.",
            ["Craft shop visit"],
            ["Purchase is craft supplies", "Direction is outflow"],
            [],
            ["CRAFT"], CharacteristicsDirection.Outflow, CharacteristicsAnalyticsTreatment.Expense, 0.55),
        new(null, 210303, "Sewing and knitting.",
            ["Wool and needles"],
            ["Purchase is sewing or knitting supplies", "Direction is outflow"],
            [],
            ["WOOL SHOP", "FABRIC"], CharacteristicsDirection.Outflow, CharacteristicsAnalyticsTreatment.Expense, 0.6),
        new(null, 210304, "Photography as a hobby: film, prints, minor kit.",
            ["Film developing"],
            ["Purchase serves hobby photography", "Direction is outflow"],
            ["Cameras belong to Electronics"],
            [], CharacteristicsDirection.Outflow, CharacteristicsAnalyticsTreatment.Expense, 0.5),
        new(null, 210305, "Pottery and ceramics.",
            ["Pottery class materials"],
            ["Purchase is pottery or ceramics", "Direction is outflow"],
            [],
            ["POTTERY"], CharacteristicsDirection.Outflow, CharacteristicsAnalyticsTreatment.Expense, 0.6),
        new(null, 210306, "DIY hobby kits.",
            ["Model kit purchase"],
            ["Purchase is a hobby kit", "Direction is outflow"],
            [],
            [], CharacteristicsDirection.Outflow, CharacteristicsAnalyticsTreatment.Expense, 0.5),

        // -- 21040 Sports & Recreation --
        new(21040, null, "Playing and training: gear, clubs, active recreation.",
            ["Club registration", "New boots"],
            ["Charge is playing sport or active recreation", "Direction is outflow"],
            ["Watching sport belongs to Events & Outings"],
            [], CharacteristicsDirection.Outflow, CharacteristicsAnalyticsTreatment.Expense, 0.55),
        new(null, 210401, "Sports equipment.",
            ["New hurley and helmet"],
            ["Purchase is sports equipment", "Direction is outflow"],
            [],
            ["ELVERYS", "INTERSPORT", "DECATHLON"], CharacteristicsDirection.Outflow, CharacteristicsAnalyticsTreatment.Expense, 0.7),
        new(null, 210402, "Club fees: GAA, soccer, rugby memberships.",
            ["Annual club membership"],
            ["Charge is a sports club fee", "Direction is outflow"],
            [],
            ["GAA CLUB", "CLG "], CharacteristicsDirection.Outflow, CharacteristicsAnalyticsTreatment.Expense, 0.6),
        new(null, 210403, "Outdoor gear.",
            ["Hiking boots and rain gear"],
            ["Purchase is outdoor equipment", "Direction is outflow"],
            [],
            ["GREAT OUTDOORS", "REGATTA"], CharacteristicsDirection.Outflow, CharacteristicsAnalyticsTreatment.Expense, 0.65),
        new(null, 210404, "Camping gear.",
            ["Tent and sleeping bags"],
            ["Purchase is camping equipment", "Direction is outflow"],
            ["Campsite fees belong to Travel's Camping Fees"],
            ["CAMPING"], CharacteristicsDirection.Outflow, CharacteristicsAnalyticsTreatment.Expense, 0.6),
        new(null, 210405, "Fishing and hunting: gear and permits.",
            ["Fishing licence and tackle"],
            ["Purchase serves fishing or hunting", "Direction is outflow"],
            [],
            ["ANGLING", "TACKLE"], CharacteristicsDirection.Outflow, CharacteristicsAnalyticsTreatment.Expense, 0.65),
        new(null, 210406, "Climbing: walls, gear.",
            ["Climbing wall entry"],
            ["Charge is climbing", "Direction is outflow"],
            [],
            ["CLIMBING"], CharacteristicsDirection.Outflow, CharacteristicsAnalyticsTreatment.Expense, 0.65),
        new(null, 210407, "Swimming: pool entry and swim fees.",
            ["Pool session"],
            ["Charge is swimming", "Direction is outflow"],
            [],
            ["SWIMMING POOL", "LEISURE CENTRE"], CharacteristicsDirection.Outflow, CharacteristicsAnalyticsTreatment.Expense, 0.65),

        // -- 21050 Media & Leisure (210507 Adult Content included) --
        new(21050, null, "Quieter leisure: reading, music, personal media.",
            ["Bookshop visit"],
            ["Purchase is personal media or leisure goods", "Direction is outflow"],
            [],
            [], CharacteristicsDirection.Outflow, CharacteristicsAnalyticsTreatment.Expense, 0.55),
        new(null, 210501, "Physical books.",
            ["New paperback"],
            ["Purchase is books", "Direction is outflow"],
            [],
            ["EASON", "DUBRAY", "WATERSTONES"], CharacteristicsDirection.Outflow, CharacteristicsAnalyticsTreatment.Expense, 0.7),
        new(null, 210502, "eBooks and audiobooks.",
            ["Audiobook credit"],
            ["Purchase is digital books", "Direction is outflow"],
            [],
            ["AUDIBLE", "KINDLE"], CharacteristicsDirection.Outflow, CharacteristicsAnalyticsTreatment.Expense, 0.7),
        new(null, 210503, "Magazines.",
            ["Magazine subscription"],
            ["Purchase is magazines", "Direction is outflow"],
            [],
            [], CharacteristicsDirection.Outflow, CharacteristicsAnalyticsTreatment.Expense, 0.5),
        new(null, 210504, "Buying music.",
            ["Album purchase"],
            ["Purchase is music", "Direction is outflow"],
            ["Streaming belongs to Streaming & Media"],
            ["BANDCAMP"], CharacteristicsDirection.Outflow, CharacteristicsAnalyticsTreatment.Expense, 0.6),
        new(null, 210505, "Musical instruments.",
            ["Guitar purchase"],
            ["Purchase is an instrument", "Direction is outflow"],
            [],
            ["MUSIC SHOP", "THOMANN"], CharacteristicsDirection.Outflow, CharacteristicsAnalyticsTreatment.Expense, 0.65),
        new(null, 210506, "Instrument lessons for yourself.",
            ["Guitar lessons"],
            ["Charge is instrument tuition", "Direction is outflow"],
            ["Children's lessons belong to Family's Music Lessons"],
            [], CharacteristicsDirection.Outflow, CharacteristicsAnalyticsTreatment.Expense, 0.55),
        new(null, 210507, "Adult content and services.",
            ["Content subscription"],
            ["Purchase is adult content", "Direction is outflow"],
            [],
            ["ONLYFANS"], CharacteristicsDirection.Outflow, CharacteristicsAnalyticsTreatment.Expense, 0.75),

        // -- 21060 Collecting & Specialty Hobbies --
        new(21060, null, "Collecting: cards, comics, memorabilia, models.",
            ["Trading card box"],
            ["Purchase is collecting or specialty hobby goods", "Direction is outflow"],
            ["Investment-grade pieces belong to Collectibles as Investment"],
            [], CharacteristicsDirection.Outflow, CharacteristicsAnalyticsTreatment.Expense, 0.55),
        new(null, 210601, "Trading cards.",
            ["Booster box"],
            ["Purchase is trading cards", "Direction is outflow"],
            [],
            ["TRADING CARD"], CharacteristicsDirection.Outflow, CharacteristicsAnalyticsTreatment.Expense, 0.6),
        new(null, 210602, "Comics.",
            ["Comic shop visit"],
            ["Purchase is comics", "Direction is outflow"],
            [],
            ["COMICS"], CharacteristicsDirection.Outflow, CharacteristicsAnalyticsTreatment.Expense, 0.6),
        new(null, 210603, "Memorabilia.",
            ["Signed memorabilia"],
            ["Purchase is memorabilia", "Direction is outflow"],
            [],
            ["MEMORABILIA"], CharacteristicsDirection.Outflow, CharacteristicsAnalyticsTreatment.Expense, 0.6),
        new(null, 210604, "Model building.",
            ["Scale model kit"],
            ["Purchase is model building", "Direction is outflow"],
            [],
            [], CharacteristicsDirection.Outflow, CharacteristicsAnalyticsTreatment.Expense, 0.5),
        new(null, 210605, "General collectibles.",
            ["Collectible figure"],
            ["Purchase is collectibles", "Direction is outflow"],
            [],
            [], CharacteristicsDirection.Outflow, CharacteristicsAnalyticsTreatment.Expense, 0.5),

        // -- 21080 Gambling & Betting --
        new(21080, null, "Games of chance: betting, lottery, casino play.",
            ["Bookmaker deposit", "Lotto ticket"],
            ["Merchant is a gambling operator", "Direction is outflow"],
            ["Winnings arriving are Gambling & Lottery Winnings income"],
            [], CharacteristicsDirection.Outflow, CharacteristicsAnalyticsTreatment.Expense, 0.75),
        new(null, 210801, "Sports betting.",
            ["Bookmaker stake or deposit"],
            ["Merchant is a bookmaker", "Direction is outflow"],
            [],
            ["PADDY POWER", "BOYLESPORTS", "BET365", "LADBROKES", "BETFAIR"], CharacteristicsDirection.Outflow, CharacteristicsAnalyticsTreatment.Expense, 0.8),
        new(null, 210802, "Lottery and scratch cards.",
            ["Lotto ticket", "Scratch card"],
            ["Purchase is lottery products", "Direction is outflow"],
            [],
            ["NATIONAL LOTTERY", "LOTTERY", "LOTTO"], CharacteristicsDirection.Outflow, CharacteristicsAnalyticsTreatment.Expense, 0.75),
        new(null, 210803, "Casino and online casino play.",
            ["Casino deposit"],
            ["Merchant is a casino", "Direction is outflow"],
            [],
            ["CASINO", "POKERSTARS"], CharacteristicsDirection.Outflow, CharacteristicsAnalyticsTreatment.Expense, 0.75),
        new(null, 210804, "Bingo and raffles.",
            ["Bingo night entry"],
            ["Purchase is bingo or raffle entries", "Direction is outflow"],
            ["Charity raffles may belong to Charitable Giving when clearly donations"],
            ["BINGO"], CharacteristicsDirection.Outflow, CharacteristicsAnalyticsTreatment.Expense, 0.7),

        // -- 21070 Other Entertainment & Hobbies (real + catch-all) --
        new(21070, null, "Entertainment that fits nowhere else; a human choice, never an AI guess.",
            ["Genuinely unclassifiable entertainment expense"],
            ["Only deterministic rules or the user may assign this catch-all"],
            [],
            [], CharacteristicsDirection.Outflow, CharacteristicsAnalyticsTreatment.Expense, null),
        new(null, 210701, "Hobby classes for adults.",
            ["Evening pottery class"],
            ["Charge is a hobby class", "Direction is outflow"],
            [],
            [], CharacteristicsDirection.Outflow, CharacteristicsAnalyticsTreatment.Expense, 0.5),
        new(null, 210702, "Workshops.",
            ["Weekend workshop"],
            ["Charge is a hobby workshop", "Direction is outflow"],
            [],
            [], CharacteristicsDirection.Outflow, CharacteristicsAnalyticsTreatment.Expense, 0.5),
        new(null, 210703, "Other leisure spending, user-assigned.",
            ["Leisure one-off with no better node"],
            ["Only deterministic rules or the user may assign this catch-all"],
            [],
            [], CharacteristicsDirection.Outflow, CharacteristicsAnalyticsTreatment.Expense, null),

        // -- 220 Travel: categories + subs --
        new(22010, null, "Getting there: transport booked for trips.",
            ["Holiday flights"],
            ["Charge is trip transport", "Direction is outflow"],
            ["Everyday transport belongs to Transportation"],
            [], CharacteristicsDirection.Outflow, CharacteristicsAnalyticsTreatment.Expense, 0.55),
        new(null, 220101, "Trip flights recorded under travel.",
            ["Return flights for the holiday"],
            ["Flight exists for a trip", "Direction is outflow"],
            ["Everyday flight bookings follow the Flights subcategory in Transportation"],
            [], CharacteristicsDirection.Outflow, CharacteristicsAnalyticsTreatment.Expense, 0.5),
        new(null, 220102, "Trains on trips.",
            ["Intercity train abroad"],
            ["Rail journey exists for a trip", "Direction is outflow"],
            [],
            [], CharacteristicsDirection.Outflow, CharacteristicsAnalyticsTreatment.Expense, 0.5),
        new(null, 220103, "Buses on trips.",
            ["Coach leg of the trip"],
            ["Bus journey exists for a trip", "Direction is outflow"],
            [],
            [], CharacteristicsDirection.Outflow, CharacteristicsAnalyticsTreatment.Expense, 0.5),
        new(null, 220104, "Car rental on trips.",
            ["Hire car abroad"],
            ["Rental exists for a trip", "Direction is outflow"],
            ["Domestic hire follows Transportation's Car Rental"],
            [], CharacteristicsDirection.Outflow, CharacteristicsAnalyticsTreatment.Expense, 0.5),
        new(null, 220105, "Ferries on trips.",
            ["Ferry crossing on holiday"],
            ["Ferry exists for a trip", "Direction is outflow"],
            [],
            [], CharacteristicsDirection.Outflow, CharacteristicsAnalyticsTreatment.Expense, 0.5),
        new(null, 220106, "Airport transfers on trips.",
            ["Hotel shuttle abroad"],
            ["Transfer exists for a trip", "Direction is outflow"],
            [],
            [], CharacteristicsDirection.Outflow, CharacteristicsAnalyticsTreatment.Expense, 0.5),
        new(null, 220107, "Baggage fees on trips.",
            ["Bag fee on the return leg"],
            ["Charge is trip baggage", "Direction is outflow"],
            [],
            [], CharacteristicsDirection.Outflow, CharacteristicsAnalyticsTreatment.Expense, 0.5),
        new(22020, null, "Sleeping there: hotels to campsites.",
            ["Hotel booking"],
            ["Charge is trip accommodation", "Direction is outflow"],
            [],
            ["HOTELS.COM", "AIRBNB"], CharacteristicsDirection.Outflow, CharacteristicsAnalyticsTreatment.Expense, 0.7),
        new(null, 220201, "Hotels.",
            ["Two-night hotel stay"],
            ["Stay is a hotel", "Direction is outflow"],
            [],
            ["HOTEL"], CharacteristicsDirection.Outflow, CharacteristicsAnalyticsTreatment.Expense, 0.6),
        new(null, 220202, "Hostels.",
            ["Hostel bed"],
            ["Stay is a hostel", "Direction is outflow"],
            [],
            ["HOSTEL"], CharacteristicsDirection.Outflow, CharacteristicsAnalyticsTreatment.Expense, 0.65),
        new(null, 220203, "Vacation rentals.",
            ["Holiday apartment rental"],
            ["Stay is a vacation rental", "Direction is outflow"],
            [],
            ["VRBO"], CharacteristicsDirection.Outflow, CharacteristicsAnalyticsTreatment.Expense, 0.6),
        new(null, 220204, "Campsite fees.",
            ["Campsite pitch"],
            ["Stay is camping", "Direction is outflow"],
            [],
            ["CAMPSITE"], CharacteristicsDirection.Outflow, CharacteristicsAnalyticsTreatment.Expense, 0.65),
        new(null, 220205, "Resort fees.",
            ["Resort charge on checkout"],
            ["Charge is a resort fee", "Direction is outflow"],
            [],
            [], CharacteristicsDirection.Outflow, CharacteristicsAnalyticsTreatment.Expense, 0.5),
        new(null, 220206, "Accommodation deposits.",
            ["Booking deposit"],
            ["Charge is an accommodation deposit", "Direction is outflow"],
            [],
            [], CharacteristicsDirection.Outflow, CharacteristicsAnalyticsTreatment.Expense, 0.5),
        new(22030, null, "Spending while away: eating and getting around locally.",
            ["Dinner on holiday"],
            ["Spend happens during a trip", "Direction is outflow"],
            [],
            [], CharacteristicsDirection.Outflow, CharacteristicsAnalyticsTreatment.Expense, 0.5),
        new(null, 220301, "Restaurants while traveling.",
            ["Holiday dinner out"],
            ["Meal happens on a trip", "Direction is outflow"],
            [],
            [], CharacteristicsDirection.Outflow, CharacteristicsAnalyticsTreatment.Expense, 0.5),
        new(null, 220302, "Snacks while traveling.",
            ["Airport snacks"],
            ["Snack happens on a trip", "Direction is outflow"],
            [],
            [], CharacteristicsDirection.Outflow, CharacteristicsAnalyticsTreatment.Expense, 0.5),
        new(null, 220303, "Local transport at the destination.",
            ["Metro tickets abroad"],
            ["Fare is local transport on a trip", "Direction is outflow"],
            [],
            [], CharacteristicsDirection.Outflow, CharacteristicsAnalyticsTreatment.Expense, 0.5),
        new(null, 220304, "Tips while traveling.",
            ["Guide tip"],
            ["Payment is a trip tip", "Direction is outflow"],
            [],
            [], CharacteristicsDirection.Outflow, CharacteristicsAnalyticsTreatment.Expense, 0.5),
        new(null, 220305, "Currency exchange fees on trips.",
            ["Bureau de change margin"],
            ["Charge is currency exchange", "Direction is outflow"],
            ["Card FX fees belong to Banking & Account Fees"],
            ["BUREAU DE CHANGE"], CharacteristicsDirection.Outflow, CharacteristicsAnalyticsTreatment.Expense, 0.6),
        new(22040, null, "Making the trip possible: documents, bookings, add-ons.",
            ["Visa application"],
            ["Charge plans or enables a trip", "Direction is outflow"],
            [],
            [], CharacteristicsDirection.Outflow, CharacteristicsAnalyticsTreatment.Expense, 0.55),
        new(null, 220401, "Passports.",
            ["Passport renewal"],
            ["Charge is a passport", "Direction is outflow"],
            [],
            ["PASSPORT"], CharacteristicsDirection.Outflow, CharacteristicsAnalyticsTreatment.Expense, 0.7),
        new(null, 220402, "Visas.",
            ["Tourist visa fee"],
            ["Charge is a visa", "Direction is outflow"],
            [],
            ["EVISA", "VISA APPLICATION"], CharacteristicsDirection.Outflow, CharacteristicsAnalyticsTreatment.Expense, 0.65),
        new(null, 220403, "Travel insurance bought with the trip.",
            ["Policy for the trip"],
            ["Charge is trip insurance", "Direction is outflow"],
            ["Standalone policies follow Insurance's Travel Insurance"],
            [], CharacteristicsDirection.Outflow, CharacteristicsAnalyticsTreatment.Expense, 0.5),
        new(null, 220404, "Tour bookings.",
            ["Day tour booking"],
            ["Charge is a tour", "Direction is outflow"],
            [],
            ["GETYOURGUIDE", "VIATOR"], CharacteristicsDirection.Outflow, CharacteristicsAnalyticsTreatment.Expense, 0.7),
        new(null, 220405, "Attraction tickets.",
            ["Attraction entry abroad"],
            ["Charge is an attraction", "Direction is outflow"],
            [],
            [], CharacteristicsDirection.Outflow, CharacteristicsAnalyticsTreatment.Expense, 0.5),
        new(null, 220406, "Travel SIMs and roaming.",
            ["Holiday eSIM"],
            ["Charge is travel connectivity", "Direction is outflow"],
            [],
            ["AIRALO", "ESIM"], CharacteristicsDirection.Outflow, CharacteristicsAnalyticsTreatment.Expense, 0.7),
        new(22050, null, "Travel for work you pay for yourself.",
            ["Conference trip costs"],
            ["Travel exists for work", "Direction is outflow"],
            ["Reimbursements arriving are Reimbursements income"],
            [], CharacteristicsDirection.Outflow, CharacteristicsAnalyticsTreatment.Expense, 0.5),
        new(null, 220501, "Work flights.",
            ["Flight to the client site"],
            ["Flight exists for work", "Direction is outflow"],
            [],
            [], CharacteristicsDirection.Outflow, CharacteristicsAnalyticsTreatment.Expense, 0.5),
        new(null, 220502, "Work lodging.",
            ["Hotel for the work trip"],
            ["Stay exists for work", "Direction is outflow"],
            [],
            [], CharacteristicsDirection.Outflow, CharacteristicsAnalyticsTreatment.Expense, 0.5),
        new(null, 220503, "Work meals awaiting reimbursement.",
            ["Client dinner to expense"],
            ["Meal is pending reimbursement", "Direction is outflow"],
            [],
            [], CharacteristicsDirection.Outflow, CharacteristicsAnalyticsTreatment.Expense, 0.5),
        new(null, 220504, "Conference travel.",
            ["Conference registration travel"],
            ["Travel exists for a conference", "Direction is outflow"],
            [],
            [], CharacteristicsDirection.Outflow, CharacteristicsAnalyticsTreatment.Expense, 0.5),
        new(null, 220505, "Mileage costs on work travel.",
            ["Fuel attributed to work driving"],
            ["Cost is work mileage", "Direction is outflow"],
            [],
            [], CharacteristicsDirection.Outflow, CharacteristicsAnalyticsTreatment.Expense, 0.5),

        // -- 22060 Other Travel (real + catch-all) --
        new(22060, null, "Travel costs that fit nowhere else; a human choice, never an AI guess.",
            ["Genuinely unclassifiable travel expense"],
            ["Only deterministic rules or the user may assign this catch-all"],
            [],
            [], CharacteristicsDirection.Outflow, CharacteristicsAnalyticsTreatment.Expense, null),
        new(null, 220601, "Souvenirs.",
            ["Souvenir shop"],
            ["Purchase is souvenirs", "Direction is outflow"],
            [],
            ["SOUVENIR"], CharacteristicsDirection.Outflow, CharacteristicsAnalyticsTreatment.Expense, 0.6),
        new(null, 220602, "Travel gear: luggage, adapters.",
            ["New suitcase"],
            ["Purchase is travel gear", "Direction is outflow"],
            [],
            ["LUGGAGE"], CharacteristicsDirection.Outflow, CharacteristicsAnalyticsTreatment.Expense, 0.6),
        new(null, 220603, "Laundry on trips.",
            ["Hotel laundry"],
            ["Charge is trip laundry", "Direction is outflow"],
            [],
            [], CharacteristicsDirection.Outflow, CharacteristicsAnalyticsTreatment.Expense, 0.5),
        new(null, 220604, "Other trip costs, user-assigned.",
            ["Trip one-off with no better node"],
            ["Only deterministic rules or the user may assign this catch-all"],
            [],
            [], CharacteristicsDirection.Outflow, CharacteristicsAnalyticsTreatment.Expense, null)
    ];
}
