namespace NSFinance.Shared.Taxonomy;

// Full-coverage characteristics: Home & Garden (110) subcategories.
public static partial class CategoryCharacteristicsCatalog
{
    private static readonly IReadOnlyList<CategoryCharacteristicsDefinition> HomeGardenSubcategoryDefinitions =
    [
        // -- 11010 Home Supplies & Consumables --
        new(null, 110101, "Cleaning products: sprays, cloths, mops, detergents for surfaces.",
            ["Cleaning products top-up"],
            ["Goods are household cleaning products", "Direction is outflow"],
            ["Laundry detergent belongs to Laundry Supplies"],
            [], CharacteristicsDirection.Outflow, CharacteristicsAnalyticsTreatment.Expense, 0.6),
        new(null, 110102, "Paper products: kitchen roll, toilet paper, tissues.",
            ["Toilet roll multipack"],
            ["Goods are household paper products", "Direction is outflow"],
            [],
            [], CharacteristicsDirection.Outflow, CharacteristicsAnalyticsTreatment.Expense, 0.55),
        new(null, 110103, "Laundry: detergent, softener, stain removers.",
            ["Laundry detergent refill"],
            ["Goods are laundry consumables", "Direction is outflow"],
            ["Dry cleaning services belong to Clothing Care"],
            [], CharacteristicsDirection.Outflow, CharacteristicsAnalyticsTreatment.Expense, 0.55),
        new(null, 110104, "Kitchen consumables: foil, cling film, baking paper, bags.",
            ["Foil and freezer bags"],
            ["Goods are kitchen consumables", "Direction is outflow"],
            ["Food itself belongs to Groceries"],
            [], CharacteristicsDirection.Outflow, CharacteristicsAnalyticsTreatment.Expense, 0.55),
        new(null, 110105, "Storage and organization: boxes, baskets, organizers.",
            ["Under-bed storage boxes"],
            ["Goods organize the home", "Direction is outflow"],
            [],
            [], CharacteristicsDirection.Outflow, CharacteristicsAnalyticsTreatment.Expense, 0.55),
        new(null, 110106, "Bulbs and batteries.",
            ["Bulb and battery run"],
            ["Goods are light bulbs or batteries", "Direction is outflow"],
            ["Fitted light fixtures belong to DIY Supplies"],
            [], CharacteristicsDirection.Outflow, CharacteristicsAnalyticsTreatment.Expense, 0.55),
        new(null, 110107, "Home safety: smoke alarms, CO monitors, extinguishers, first-aid kits.",
            ["Smoke alarm replacement"],
            ["Goods are home safety equipment", "Direction is outflow"],
            [],
            ["SMOKE ALARM"], CharacteristicsDirection.Outflow, CharacteristicsAnalyticsTreatment.Expense, 0.6),
        new(null, 110108, "DIY pest control goods: traps, sprays, repellents.",
            ["Mouse traps and spray"],
            ["Goods are pest-control products", "Direction is outflow"],
            ["Professional treatment belongs to Pest Control Services"],
            [], CharacteristicsDirection.Outflow, CharacteristicsAnalyticsTreatment.Expense, 0.6),

        // -- 11020 Home Décor & Furnishings --
        new(null, 110201, "Artwork: prints, frames, canvases.",
            ["Framed print for the hall"],
            ["Item is wall art", "Direction is outflow"],
            [],
            [], CharacteristicsDirection.Outflow, CharacteristicsAnalyticsTreatment.Expense, 0.55),
        new(null, 110202, "Decorative items: vases, ornaments, trays.",
            ["Ornament for the shelf"],
            ["Item is decorative", "Direction is outflow"],
            [],
            [], CharacteristicsDirection.Outflow, CharacteristicsAnalyticsTreatment.Expense, 0.5),
        new(null, 110203, "Candles and home fragrance.",
            ["Scented candle"],
            ["Item is a candle or home fragrance", "Direction is outflow"],
            [],
            ["YANKEE CANDLE"], CharacteristicsDirection.Outflow, CharacteristicsAnalyticsTreatment.Expense, 0.65),
        new(null, 110204, "Seasonal decorations: Christmas, Halloween, occasions.",
            ["Christmas decorations haul"],
            ["Item decorates for a season or holiday", "Direction is outflow"],
            [],
            ["CHRISTMAS SHOP"], CharacteristicsDirection.Outflow, CharacteristicsAnalyticsTreatment.Expense, 0.6),
        new(null, 110205, "Wall fixtures: shelves-as-decor, hooks, mirrors on walls.",
            ["Wall mirror purchase"],
            ["Item is a decorative wall fixture", "Direction is outflow"],
            [],
            [], CharacteristicsDirection.Outflow, CharacteristicsAnalyticsTreatment.Expense, 0.5),
        new(null, 110206, "Soft furnishings: cushions, throws, covers.",
            ["Cushions and a throw"],
            ["Item is a soft furnishing", "Direction is outflow"],
            ["Bedding sets belong to Mattresses & Bedding"],
            [], CharacteristicsDirection.Outflow, CharacteristicsAnalyticsTreatment.Expense, 0.55),
        new(null, 110207, "Decorative lighting: fairy lights, lamps chosen for look.",
            ["String lights for the shelf"],
            ["Item is decorative lighting", "Direction is outflow"],
            ["Fitted fixtures belong to DIY Supplies"],
            [], CharacteristicsDirection.Outflow, CharacteristicsAnalyticsTreatment.Expense, 0.5),

        // -- 11030 DIY & Improvement Supplies --
        new(null, 110301, "Paint and painting supplies bought yourself.",
            ["Paint and rollers for a room"],
            ["Goods are paint or painting supplies", "Direction is outflow"],
            ["Hiring a painter belongs to Painting & Decorating"],
            ["DULUX"], CharacteristicsDirection.Outflow, CharacteristicsAnalyticsTreatment.Expense, 0.65),
        new(null, 110302, "General hardware: fittings, brackets, ironmongery.",
            ["Bits and pieces from the hardware aisle"],
            ["Goods are general hardware", "Direction is outflow"],
            [],
            [], CharacteristicsDirection.Outflow, CharacteristicsAnalyticsTreatment.Expense, 0.55),
        new(null, 110303, "Power tools: drills, sanders, saws.",
            ["Cordless drill purchase"],
            ["Item is a power tool", "Direction is outflow"],
            [],
            ["DEWALT", "MAKITA"], CharacteristicsDirection.Outflow, CharacteristicsAnalyticsTreatment.Expense, 0.65),
        new(null, 110304, "Building materials: timber, plaster, cement, sheeting.",
            ["Timber and plasterboard"],
            ["Goods are building materials", "Direction is outflow"],
            [],
            [], CharacteristicsDirection.Outflow, CharacteristicsAnalyticsTreatment.Expense, 0.55),
        new(null, 110305, "Light fittings you install: fixtures, spots, pendants.",
            ["Pendant light fitting"],
            ["Item is a light fixture for installation", "Direction is outflow"],
            ["Decorative lamps belong to Home Décor"],
            [], CharacteristicsDirection.Outflow, CharacteristicsAnalyticsTreatment.Expense, 0.55),
        new(null, 110306, "Bathroom fixtures: taps, showers, sanitary ware bought as goods.",
            ["New tap set"],
            ["Item is a bathroom fixture", "Direction is outflow"],
            ["Fitted renovation belongs to Bathroom Renovation"],
            [], CharacteristicsDirection.Outflow, CharacteristicsAnalyticsTreatment.Expense, 0.55),
        new(null, 110307, "Kitchen fixtures: sinks, taps, handles bought as goods.",
            ["Kitchen tap replacement part"],
            ["Item is a kitchen fixture", "Direction is outflow"],
            ["Fitted renovation belongs to Kitchen Renovation"],
            [], CharacteristicsDirection.Outflow, CharacteristicsAnalyticsTreatment.Expense, 0.55),
        new(null, 110308, "Adhesives and sealants: glue, silicone, filler.",
            ["Silicone and filler"],
            ["Goods are adhesives or sealants", "Direction is outflow"],
            [],
            [], CharacteristicsDirection.Outflow, CharacteristicsAnalyticsTreatment.Expense, 0.55),
        new(null, 110309, "Fasteners and fixings: screws, plugs, nails.",
            ["Box of screws and wall plugs"],
            ["Goods are fasteners or fixings", "Direction is outflow"],
            [],
            [], CharacteristicsDirection.Outflow, CharacteristicsAnalyticsTreatment.Expense, 0.55),

        // -- 11040 Garden & Outdoor --
        new(null, 110401, "Plants: bedding, shrubs, houseplants.",
            ["Bedding plants tray"],
            ["Goods are live plants", "Direction is outflow"],
            [],
            [], CharacteristicsDirection.Outflow, CharacteristicsAnalyticsTreatment.Expense, 0.6),
        new(null, 110402, "Soil and compost.",
            ["Compost bags"],
            ["Goods are soil, compost, or growing media", "Direction is outflow"],
            [],
            [], CharacteristicsDirection.Outflow, CharacteristicsAnalyticsTreatment.Expense, 0.6),
        new(null, 110403, "Seeds and bulbs for growing.",
            ["Vegetable seed packets"],
            ["Goods are seeds or bulbs", "Direction is outflow"],
            [],
            [], CharacteristicsDirection.Outflow, CharacteristicsAnalyticsTreatment.Expense, 0.6),
        new(null, 110404, "Garden tools: spades, secateurs, mowers as tools.",
            ["New secateurs and trowel"],
            ["Item is a garden tool", "Direction is outflow"],
            [],
            [], CharacteristicsDirection.Outflow, CharacteristicsAnalyticsTreatment.Expense, 0.6),
        new(null, 110405, "Lawn care goods: feed, seed, weedkiller.",
            ["Lawn feed and moss killer"],
            ["Goods maintain the lawn", "Direction is outflow"],
            ["Hired landscaping belongs to Seasonal & Outdoor Maintenance"],
            [], CharacteristicsDirection.Outflow, CharacteristicsAnalyticsTreatment.Expense, 0.6),
        new(null, 110406, "Outdoor furniture: patio sets, benches.",
            ["Patio set for summer"],
            ["Item is outdoor furniture", "Direction is outflow"],
            [],
            [], CharacteristicsDirection.Outflow, CharacteristicsAnalyticsTreatment.Expense, 0.6),
        new(null, 110407, "BBQ and patio supplies: barbecues, gas, charcoal, covers.",
            ["Charcoal and firelighters"],
            ["Goods serve the BBQ or patio", "Direction is outflow"],
            ["Bottled gas for home heating belongs to Gas & Heating"],
            ["BARBECUE", "BBQ"], CharacteristicsDirection.Outflow, CharacteristicsAnalyticsTreatment.Expense, 0.6),
        new(null, 110408, "Pots and planters.",
            ["Planters for the patio"],
            ["Item is a pot or planter", "Direction is outflow"],
            [],
            [], CharacteristicsDirection.Outflow, CharacteristicsAnalyticsTreatment.Expense, 0.55),
        new(null, 110409, "Watering: hoses, sprinklers, butts, irrigation.",
            ["New hose and sprinkler"],
            ["Goods water the garden", "Direction is outflow"],
            [],
            [], CharacteristicsDirection.Outflow, CharacteristicsAnalyticsTreatment.Expense, 0.55),

        // -- 11050 Seasonal & Outdoor Maintenance --
        new(null, 110501, "Winter supplies: salt, grit, shovels.",
            ["Grit and a snow shovel"],
            ["Goods handle snow or ice", "Direction is outflow"],
            [],
            [], CharacteristicsDirection.Outflow, CharacteristicsAnalyticsTreatment.Expense, 0.6),
        new(null, 110502, "Gutter cleaning supplies you use yourself.",
            ["Gutter scoop and guards"],
            ["Goods clean or protect gutters", "Direction is outflow"],
            ["Hired gutter cleaning is a service under this category's services"],
            [], CharacteristicsDirection.Outflow, CharacteristicsAnalyticsTreatment.Expense, 0.55),
        new(null, 110503, "Tree surgeons and trimming services.",
            ["Tree surgeon visit"],
            ["Service trims or removes trees", "Direction is outflow"],
            [],
            ["TREE SURGEON", "TREE CARE"], CharacteristicsDirection.Outflow, CharacteristicsAnalyticsTreatment.Expense, 0.7),
        new(null, 110504, "Landscaping services: design and build of outdoor space.",
            ["Landscaper invoice for the back garden"],
            ["Service landscapes the property", "Direction is outflow"],
            [],
            ["LANDSCAPING", "LANDSCAPES"], CharacteristicsDirection.Outflow, CharacteristicsAnalyticsTreatment.Expense, 0.7),
        new(null, 110505, "Pool or hot tub upkeep: chemicals and servicing.",
            ["Hot tub chemicals"],
            ["Cost maintains a pool or hot tub", "Direction is outflow"],
            [],
            [], CharacteristicsDirection.Outflow, CharacteristicsAnalyticsTreatment.Expense, 0.6),
        new(null, 110506, "Outdoor cleaning: power washing, driveway cleaning.",
            ["Driveway power wash"],
            ["Service cleans outdoor surfaces", "Direction is outflow"],
            [],
            ["POWER WASH", "POWERWASH"], CharacteristicsDirection.Outflow, CharacteristicsAnalyticsTreatment.Expense, 0.65),
        new(null, 110507, "Fence and shed upkeep: stain, repairs, replacement panels.",
            ["Fence panels and stain"],
            ["Cost maintains fences or sheds", "Direction is outflow"],
            [],
            [], CharacteristicsDirection.Outflow, CharacteristicsAnalyticsTreatment.Expense, 0.55),

        // -- 11060 Workshop & Projects --
        new(null, 110601, "Materials for a defined DIY project.",
            ["Materials run for the bench build"],
            ["Purchase serves a specific home project", "Direction is outflow"],
            ["House-repair materials belong to DIY & Improvement Supplies"],
            [], CharacteristicsDirection.Outflow, CharacteristicsAnalyticsTreatment.Expense, 0.5),
        new(null, 110602, "Workshop consumables: blades, sandpaper, bits.",
            ["Sandpaper and blades restock"],
            ["Goods are workshop consumables", "Direction is outflow"],
            [],
            [], CharacteristicsDirection.Outflow, CharacteristicsAnalyticsTreatment.Expense, 0.5),
        new(null, 110603, "Craft or build materials used around the home.",
            ["Plywood for a home build"],
            ["Materials serve home making rather than art", "Direction is outflow"],
            ["Art supplies belong to Arts & Crafts"],
            [], CharacteristicsDirection.Outflow, CharacteristicsAnalyticsTreatment.Expense, 0.5),
        new(null, 110604, "Tools bought to make a repair.",
            ["Cheap tool for a one-off fix"],
            ["Tool purchase enables a repair", "Direction is outflow"],
            [],
            [], CharacteristicsDirection.Outflow, CharacteristicsAnalyticsTreatment.Expense, 0.5),
        new(null, 110605, "Replacing worn utility tools.",
            ["Replacement hammer"],
            ["Purchase replaces a worn tool", "Direction is outflow"],
            [],
            [], CharacteristicsDirection.Outflow, CharacteristicsAnalyticsTreatment.Expense, 0.5),

        // -- 11070 Other Home & Garden (deterministic-only catch-alls) --
        new(11070, null, "Home and garden costs that fit nowhere else; a human choice, never an AI guess.",
            ["Genuinely unclassifiable home & garden expense"],
            ["Only deterministic rules or the user may assign this catch-all"],
            [],
            [], CharacteristicsDirection.Outflow, CharacteristicsAnalyticsTreatment.Expense, null),
        new(null, 110701, "Miscellaneous home & garden, user-assigned.",
            ["One-off with no better node"],
            ["Only deterministic rules or the user may assign this catch-all"],
            [],
            [], CharacteristicsDirection.Outflow, CharacteristicsAnalyticsTreatment.Expense, null),
        new(null, 110702, "Unclassified home & garden, user-assigned.",
            ["Awaiting proper classification"],
            ["Only deterministic rules or the user may assign this catch-all"],
            [],
            [], CharacteristicsDirection.Outflow, CharacteristicsAnalyticsTreatment.Expense, null)
    ];
}
