namespace NSFinance.Shared.Taxonomy;

// Full-coverage characteristics: Healthcare (160) subcategories. Deep and
// clinical; floors stay modest because statement text rarely names the
// specialty - the AI-lane and user choices carry precision here.
public static partial class CategoryCharacteristicsCatalog
{
    private static readonly IReadOnlyList<CategoryCharacteristicsDefinition> HealthcareSubcategoryDefinitions =
    [
        // -- 16010 Primary Care & Specialists --
        new(null, 160101, "GP visits.",
            ["GP consultation fee"],
            ["Provider is a general practitioner", "Direction is outflow"],
            [],
            [], CharacteristicsDirection.Outflow, CharacteristicsAnalyticsTreatment.Expense, 0.6),
        new(null, 160102, "Paediatrician visits.",
            ["Child's paediatric appointment"],
            ["Provider is a paediatrician", "Direction is outflow"],
            [],
            ["PAEDIATRIC", "PEDIATRIC"], CharacteristicsDirection.Outflow, CharacteristicsAnalyticsTreatment.Expense, 0.6),
        new(null, 160103, "Obstetrics and gynaecology.",
            ["Gynae consultation"],
            ["Provider is an obstetrician or gynaecologist", "Direction is outflow"],
            [],
            ["GYNAE", "OBSTETRIC"], CharacteristicsDirection.Outflow, CharacteristicsAnalyticsTreatment.Expense, 0.6),
        new(null, 160104, "Dermatology.",
            ["Skin clinic consultation"],
            ["Provider is a dermatologist", "Direction is outflow"],
            ["Cosmetic skincare belongs to Grooming & Beauty"],
            ["DERMATOLOG"], CharacteristicsDirection.Outflow, CharacteristicsAnalyticsTreatment.Expense, 0.6),
        new(null, 160105, "Cardiology.",
            ["Cardiology review"],
            ["Provider is a cardiologist", "Direction is outflow"],
            [],
            ["CARDIOLOG"], CharacteristicsDirection.Outflow, CharacteristicsAnalyticsTreatment.Expense, 0.6),
        new(null, 160106, "Neurology.",
            ["Neurology consultation"],
            ["Provider is a neurologist", "Direction is outflow"],
            [],
            ["NEUROLOG"], CharacteristicsDirection.Outflow, CharacteristicsAnalyticsTreatment.Expense, 0.6),
        new(null, 160107, "Gastroenterology.",
            ["GI consultation"],
            ["Provider is a gastroenterologist", "Direction is outflow"],
            [],
            ["GASTRO"], CharacteristicsDirection.Outflow, CharacteristicsAnalyticsTreatment.Expense, 0.55),
        new(null, 160108, "Endocrinology.",
            ["Endocrine clinic visit"],
            ["Provider is an endocrinologist", "Direction is outflow"],
            [],
            ["ENDOCRIN"], CharacteristicsDirection.Outflow, CharacteristicsAnalyticsTreatment.Expense, 0.55),
        new(null, 160109, "Psychiatry.",
            ["Psychiatric consultation"],
            ["Provider is a psychiatrist", "Direction is outflow"],
            [],
            ["PSYCHIATR"], CharacteristicsDirection.Outflow, CharacteristicsAnalyticsTreatment.Expense, 0.6),
        new(null, 160110, "Psychologists and talk therapists in clinical settings.",
            ["Clinical psychology session"],
            ["Provider is a psychologist or therapist", "Direction is outflow"],
            ["Ongoing therapy programs belong to Mental & Behavioral Health"],
            [], CharacteristicsDirection.Outflow, CharacteristicsAnalyticsTreatment.Expense, 0.5),
        new(null, 160111, "Chiropractors.",
            ["Chiropractic adjustment"],
            ["Provider is a chiropractor", "Direction is outflow"],
            [],
            ["CHIROPRACT"], CharacteristicsDirection.Outflow, CharacteristicsAnalyticsTreatment.Expense, 0.65),
        new(null, 160112, "Physiotherapy as treatment for a condition.",
            ["Physio block after an injury"],
            ["Provider is a physical therapist treating a condition", "Direction is outflow"],
            ["Wellness physio belongs to Preventive & Wellness"],
            [], CharacteristicsDirection.Outflow, CharacteristicsAnalyticsTreatment.Expense, 0.5),
        new(null, 160113, "Occupational therapy.",
            ["OT assessment"],
            ["Provider is an occupational therapist", "Direction is outflow"],
            [],
            ["OCCUPATIONAL THERAP"], CharacteristicsDirection.Outflow, CharacteristicsAnalyticsTreatment.Expense, 0.6),
        new(null, 160114, "Speech and language therapy.",
            ["SLT session"],
            ["Provider is a speech therapist", "Direction is outflow"],
            [],
            ["SPEECH THERAP", "SPEECH & LANGUAGE"], CharacteristicsDirection.Outflow, CharacteristicsAnalyticsTreatment.Expense, 0.6),

        // -- 16020 Dental Care --
        new(null, 160201, "Checkups and cleanings.",
            ["Checkup and scale & polish"],
            ["Visit is routine dental care", "Direction is outflow"],
            [],
            [], CharacteristicsDirection.Outflow, CharacteristicsAnalyticsTreatment.Expense, 0.55),
        new(null, 160202, "Fillings and extractions.",
            ["Filling appointment"],
            ["Treatment is fillings or extractions", "Direction is outflow"],
            [],
            [], CharacteristicsDirection.Outflow, CharacteristicsAnalyticsTreatment.Expense, 0.5),
        new(null, 160203, "Root canals.",
            ["Root canal treatment"],
            ["Treatment is endodontic", "Direction is outflow"],
            [],
            ["ENDODONT"], CharacteristicsDirection.Outflow, CharacteristicsAnalyticsTreatment.Expense, 0.55),
        new(null, 160204, "Crowns and bridges.",
            ["Crown fitted"],
            ["Treatment is crowns or bridges", "Direction is outflow"],
            [],
            [], CharacteristicsDirection.Outflow, CharacteristicsAnalyticsTreatment.Expense, 0.5),
        new(null, 160205, "Dentures.",
            ["Denture fitting"],
            ["Treatment is dentures", "Direction is outflow"],
            [],
            ["DENTURE"], CharacteristicsDirection.Outflow, CharacteristicsAnalyticsTreatment.Expense, 0.6),
        new(null, 160206, "Orthodontics: braces and aligners.",
            ["Monthly orthodontic instalment"],
            ["Treatment is orthodontic", "Direction is outflow"],
            [],
            ["ORTHODONT", "INVISALIGN"], CharacteristicsDirection.Outflow, CharacteristicsAnalyticsTreatment.Expense, 0.65),
        new(null, 160207, "Teeth whitening.",
            ["Whitening treatment"],
            ["Treatment is cosmetic whitening", "Direction is outflow"],
            [],
            ["WHITENING"], CharacteristicsDirection.Outflow, CharacteristicsAnalyticsTreatment.Expense, 0.55),
        new(null, 160208, "Oral surgery.",
            ["Wisdom tooth surgery"],
            ["Treatment is oral surgery", "Direction is outflow"],
            [],
            ["ORAL SURGERY"], CharacteristicsDirection.Outflow, CharacteristicsAnalyticsTreatment.Expense, 0.6),

        // -- 16030 Vision & Eye Care --
        new(null, 160301, "Eye exams.",
            ["Eye test fee"],
            ["Service is an eye exam", "Direction is outflow"],
            [],
            ["EYE TEST", "EYE EXAM"], CharacteristicsDirection.Outflow, CharacteristicsAnalyticsTreatment.Expense, 0.6),
        new(null, 160302, "Glasses.",
            ["New frames and lenses"],
            ["Purchase is eyeglasses", "Direction is outflow"],
            [],
            [], CharacteristicsDirection.Outflow, CharacteristicsAnalyticsTreatment.Expense, 0.5),
        new(null, 160303, "Contact lenses.",
            ["Monthly lens supply"],
            ["Purchase is contact lenses", "Direction is outflow"],
            [],
            ["CONTACT LENS"], CharacteristicsDirection.Outflow, CharacteristicsAnalyticsTreatment.Expense, 0.65),
        new(null, 160304, "Prescription sunglasses.",
            ["Prescription shades"],
            ["Purchase is prescription sunglasses", "Direction is outflow"],
            ["Fashion sunglasses belong to Shoes & Accessories"],
            [], CharacteristicsDirection.Outflow, CharacteristicsAnalyticsTreatment.Expense, 0.5),
        new(null, 160305, "Laser vision correction.",
            ["LASIK procedure payment"],
            ["Treatment is vision-correction surgery", "Direction is outflow"],
            [],
            ["LASIK", "LASER EYE"], CharacteristicsDirection.Outflow, CharacteristicsAnalyticsTreatment.Expense, 0.7),
        new(null, 160306, "Eye medications: drops and treatments.",
            ["Prescribed eye drops"],
            ["Purchase is eye medication", "Direction is outflow"],
            [],
            [], CharacteristicsDirection.Outflow, CharacteristicsAnalyticsTreatment.Expense, 0.5),
        new(null, 160307, "Eye patches and supplies.",
            ["Patching supplies"],
            ["Purchase is eye-care supplies", "Direction is outflow"],
            [],
            [], CharacteristicsDirection.Outflow, CharacteristicsAnalyticsTreatment.Expense, 0.5),

        // -- 16040 Prescriptions & Medications --
        new(null, 160401, "Prescription medicines dispensed.",
            ["Monthly prescription collection"],
            ["Purchase is prescription medicine", "Direction is outflow"],
            [],
            [], CharacteristicsDirection.Outflow, CharacteristicsAnalyticsTreatment.Expense, 0.55),
        new(null, 160402, "Mail-order and online pharmacy prescriptions.",
            ["Repeat prescription delivered"],
            ["Purchase is a mail-order prescription", "Direction is outflow"],
            [],
            [], CharacteristicsDirection.Outflow, CharacteristicsAnalyticsTreatment.Expense, 0.55),
        new(null, 160403, "Insulin and diabetic supplies.",
            ["Insulin and strips"],
            ["Purchase is diabetic medication or supplies", "Direction is outflow"],
            [],
            ["INSULIN"], CharacteristicsDirection.Outflow, CharacteristicsAnalyticsTreatment.Expense, 0.6),
        new(null, 160404, "Contraception.",
            ["Contraceptive prescription"],
            ["Purchase is birth control", "Direction is outflow"],
            [],
            [], CharacteristicsDirection.Outflow, CharacteristicsAnalyticsTreatment.Expense, 0.5),
        new(null, 160405, "Allergy medications.",
            ["Antihistamines for the season"],
            ["Purchase is allergy medication", "Direction is outflow"],
            [],
            [], CharacteristicsDirection.Outflow, CharacteristicsAnalyticsTreatment.Expense, 0.5),
        new(null, 160406, "Mental-health medications.",
            ["Prescribed mental-health medicine"],
            ["Purchase is psychiatric medication", "Direction is outflow"],
            [],
            [], CharacteristicsDirection.Outflow, CharacteristicsAnalyticsTreatment.Expense, 0.5),
        new(null, 160407, "Pain relievers on prescription.",
            ["Prescribed analgesics"],
            ["Purchase is prescription pain relief", "Direction is outflow"],
            ["Over-the-counter painkillers belong to Over-the-Counter Medications"],
            [], CharacteristicsDirection.Outflow, CharacteristicsAnalyticsTreatment.Expense, 0.5),
        new(null, 160408, "Antibiotics.",
            ["Antibiotic course"],
            ["Purchase is antibiotics", "Direction is outflow"],
            [],
            [], CharacteristicsDirection.Outflow, CharacteristicsAnalyticsTreatment.Expense, 0.5),

        // -- 16050 Medical Equipment & Supplies --
        new(null, 160501, "Hearing aids and their batteries.",
            ["Hearing aid purchase"],
            ["Purchase is hearing aids or batteries", "Direction is outflow"],
            [],
            ["HEARING AID", "HIDDEN HEARING"], CharacteristicsDirection.Outflow, CharacteristicsAnalyticsTreatment.Expense, 0.7),
        new(null, 160502, "Mobility aids: crutches, walkers, wheelchairs.",
            ["Wheelchair purchase"],
            ["Purchase is a mobility aid", "Direction is outflow"],
            [],
            ["WHEELCHAIR", "MOBILITY"], CharacteristicsDirection.Outflow, CharacteristicsAnalyticsTreatment.Expense, 0.6),
        new(null, 160503, "Blood pressure monitors.",
            ["Home BP monitor"],
            ["Purchase is a blood pressure monitor", "Direction is outflow"],
            [],
            [], CharacteristicsDirection.Outflow, CharacteristicsAnalyticsTreatment.Expense, 0.5),
        new(null, 160504, "Glucose meters and strips.",
            ["Glucose strips restock"],
            ["Purchase is glucose monitoring supplies", "Direction is outflow"],
            [],
            [], CharacteristicsDirection.Outflow, CharacteristicsAnalyticsTreatment.Expense, 0.5),
        new(null, 160505, "CPAP machines and supplies.",
            ["CPAP mask replacement"],
            ["Purchase is CPAP equipment", "Direction is outflow"],
            [],
            ["CPAP"], CharacteristicsDirection.Outflow, CharacteristicsAnalyticsTreatment.Expense, 0.7),
        new(null, 160506, "Nebulizers and inhalers as devices.",
            ["Nebulizer purchase"],
            ["Purchase is a respiratory device", "Direction is outflow"],
            [],
            ["NEBULIZER", "NEBULISER"], CharacteristicsDirection.Outflow, CharacteristicsAnalyticsTreatment.Expense, 0.6),
        new(null, 160507, "Prosthetics and orthotics.",
            ["Orthotic insoles fitted"],
            ["Purchase is prosthetic or orthotic", "Direction is outflow"],
            [],
            ["ORTHOTIC", "PROSTHETIC"], CharacteristicsDirection.Outflow, CharacteristicsAnalyticsTreatment.Expense, 0.6),
        new(null, 160508, "Compression stockings.",
            ["Compression wear purchase"],
            ["Purchase is compression garments", "Direction is outflow"],
            [],
            ["COMPRESSION"], CharacteristicsDirection.Outflow, CharacteristicsAnalyticsTreatment.Expense, 0.55),
        new(null, 160509, "Ostomy supplies.",
            ["Ostomy supplies order"],
            ["Purchase is ostomy supplies", "Direction is outflow"],
            [],
            ["OSTOMY"], CharacteristicsDirection.Outflow, CharacteristicsAnalyticsTreatment.Expense, 0.65),
        new(null, 160510, "Catheters and urological supplies.",
            ["Urological supplies order"],
            ["Purchase is urological supplies", "Direction is outflow"],
            [],
            ["CATHETER"], CharacteristicsDirection.Outflow, CharacteristicsAnalyticsTreatment.Expense, 0.65),

        // -- 16060 Hospital & Surgery --
        new(null, 160601, "Inpatient hospital stays.",
            ["Private room charge"],
            ["Charge is an inpatient stay", "Direction is outflow"],
            [],
            [], CharacteristicsDirection.Outflow, CharacteristicsAnalyticsTreatment.Expense, 0.5),
        new(null, 160602, "Emergency department charges.",
            ["ED attendance charge"],
            ["Charge is an emergency visit", "Direction is outflow"],
            [],
            [], CharacteristicsDirection.Outflow, CharacteristicsAnalyticsTreatment.Expense, 0.5),
        new(null, 160603, "Day-case and outpatient surgery.",
            ["Day procedure payment"],
            ["Charge is outpatient surgery", "Direction is outflow"],
            [],
            [], CharacteristicsDirection.Outflow, CharacteristicsAnalyticsTreatment.Expense, 0.5),
        new(null, 160604, "Anaesthesia fees billed separately.",
            ["Anaesthetist's fee"],
            ["Charge is anaesthesia", "Direction is outflow"],
            [],
            ["ANAESTHE", "ANESTHE"], CharacteristicsDirection.Outflow, CharacteristicsAnalyticsTreatment.Expense, 0.6),
        new(null, 160605, "Diagnostic procedures: scopes, biopsies.",
            ["Endoscopy fee"],
            ["Charge is a diagnostic procedure", "Direction is outflow"],
            [],
            [], CharacteristicsDirection.Outflow, CharacteristicsAnalyticsTreatment.Expense, 0.5),
        new(null, 160606, "Ambulance and emergency transport.",
            ["Ambulance call-out charge"],
            ["Charge is emergency transport", "Direction is outflow"],
            [],
            ["AMBULANCE"], CharacteristicsDirection.Outflow, CharacteristicsAnalyticsTreatment.Expense, 0.7),
        new(null, 160607, "Lab tests and blood work.",
            ["Blood panel fee"],
            ["Charge is laboratory testing", "Direction is outflow"],
            [],
            [], CharacteristicsDirection.Outflow, CharacteristicsAnalyticsTreatment.Expense, 0.5),
        new(null, 160608, "Imaging: X-ray, MRI, CT.",
            ["MRI scan fee"],
            ["Charge is medical imaging", "Direction is outflow"],
            [],
            ["RADIOLOG", "MRI ", "X-RAY"], CharacteristicsDirection.Outflow, CharacteristicsAnalyticsTreatment.Expense, 0.6),

        // -- 16070 Mental & Behavioral Health --
        new(null, 160701, "Ongoing therapy sessions.",
            ["Weekly therapy"],
            ["Charge is a therapy session", "Direction is outflow"],
            [],
            [], CharacteristicsDirection.Outflow, CharacteristicsAnalyticsTreatment.Expense, 0.5),
        new(null, 160702, "Counselling services.",
            ["Counselling block"],
            ["Charge is counselling", "Direction is outflow"],
            [],
            [], CharacteristicsDirection.Outflow, CharacteristicsAnalyticsTreatment.Expense, 0.5),
        new(null, 160703, "Addiction treatment programs.",
            ["Program enrolment"],
            ["Charge is addiction treatment", "Direction is outflow"],
            [],
            ["ADDICTION"], CharacteristicsDirection.Outflow, CharacteristicsAnalyticsTreatment.Expense, 0.6),
        new(null, 160704, "Residential rehab stays.",
            ["Rehab facility payment"],
            ["Charge is a rehab stay", "Direction is outflow"],
            [],
            ["REHAB"], CharacteristicsDirection.Outflow, CharacteristicsAnalyticsTreatment.Expense, 0.55),
        new(null, 160705, "Smoking cessation programs.",
            ["Cessation program fee"],
            ["Charge is a quit-smoking program", "Direction is outflow"],
            ["Nicotine substitutes belong to Nicotine Alternatives"],
            [], CharacteristicsDirection.Outflow, CharacteristicsAnalyticsTreatment.Expense, 0.5),
        new(null, 160706, "Eating disorder treatment.",
            ["Specialist program fee"],
            ["Charge is eating-disorder treatment", "Direction is outflow"],
            [],
            [], CharacteristicsDirection.Outflow, CharacteristicsAnalyticsTreatment.Expense, 0.5),
        new(null, 160707, "Autism and ADHD assessments.",
            ["Assessment fee"],
            ["Charge is a neurodevelopmental assessment", "Direction is outflow"],
            [],
            ["ADHD", "AUTISM"], CharacteristicsDirection.Outflow, CharacteristicsAnalyticsTreatment.Expense, 0.6),

        // -- 16080 Preventive & Wellness --
        new(null, 160801, "Vaccinations.",
            ["Flu jab"],
            ["Charge is a vaccination", "Direction is outflow"],
            [],
            ["VACCIN"], CharacteristicsDirection.Outflow, CharacteristicsAnalyticsTreatment.Expense, 0.65),
        new(null, 160802, "Cancer screenings.",
            ["Screening appointment"],
            ["Charge is a cancer screening", "Direction is outflow"],
            [],
            ["SCREENING"], CharacteristicsDirection.Outflow, CharacteristicsAnalyticsTreatment.Expense, 0.55),
        new(null, 160803, "STI testing.",
            ["Sexual health screen"],
            ["Charge is STI testing", "Direction is outflow"],
            [],
            [], CharacteristicsDirection.Outflow, CharacteristicsAnalyticsTreatment.Expense, 0.55),
        new(null, 160804, "Genetic testing.",
            ["DNA health test"],
            ["Charge is genetic testing", "Direction is outflow"],
            [],
            [], CharacteristicsDirection.Outflow, CharacteristicsAnalyticsTreatment.Expense, 0.55),
        new(null, 160805, "Weight-loss programs.",
            ["Program membership"],
            ["Charge is a weight-loss program", "Direction is outflow"],
            [],
            ["WEIGHT WATCHERS", "SLIMMING WORLD"], CharacteristicsDirection.Outflow, CharacteristicsAnalyticsTreatment.Expense, 0.7),
        new(null, 160806, "Fertility treatment and IVF.",
            ["IVF cycle payment"],
            ["Charge is fertility treatment", "Direction is outflow"],
            [],
            ["FERTILITY", "IVF"], CharacteristicsDirection.Outflow, CharacteristicsAnalyticsTreatment.Expense, 0.65),
        new(null, 160807, "Prenatal classes and supplies.",
            ["Antenatal class booking"],
            ["Charge is prenatal preparation", "Direction is outflow"],
            [],
            ["ANTENATAL", "PRENATAL"], CharacteristicsDirection.Outflow, CharacteristicsAnalyticsTreatment.Expense, 0.6),

        // -- 16090 Travel & Accessibility --
        new(null, 160901, "Own-car mileage to treatment, recorded as spend.",
            ["Fuel attributed to hospital runs"],
            ["Cost is travel to medical care by own car", "Direction is outflow"],
            [],
            [], CharacteristicsDirection.Outflow, CharacteristicsAnalyticsTreatment.Expense, 0.5),
        new(null, 160902, "Public transport to medical visits.",
            ["Bus to the clinic"],
            ["Fare exists for a medical visit", "Direction is outflow"],
            [],
            [], CharacteristicsDirection.Outflow, CharacteristicsAnalyticsTreatment.Expense, 0.5),
        new(null, 160903, "Staying near treatment away from home.",
            ["Hotel near the hospital"],
            ["Stay enables out-of-town treatment", "Direction is outflow"],
            ["Holiday stays belong to Travel Lodging"],
            [], CharacteristicsDirection.Outflow, CharacteristicsAnalyticsTreatment.Expense, 0.5),
        new(null, 160904, "Medical home modifications.",
            ["Bathroom grab rails for care needs"],
            ["Modification exists for medical need", "Direction is outflow"],
            ["General accessibility upgrades belong to Housing"],
            [], CharacteristicsDirection.Outflow, CharacteristicsAnalyticsTreatment.Expense, 0.5),
        new(null, 160905, "Service animals and their training.",
            ["Assistance dog training fee"],
            ["Cost is a service animal or its training", "Direction is outflow"],
            ["Ordinary pet costs belong to Pets"],
            [], CharacteristicsDirection.Outflow, CharacteristicsAnalyticsTreatment.Expense, 0.55),
        new(null, 160906, "Special transportation services for medical needs.",
            ["Accessible transport booking"],
            ["Service is specialized medical transport", "Direction is outflow"],
            [],
            [], CharacteristicsDirection.Outflow, CharacteristicsAnalyticsTreatment.Expense, 0.5),

        // -- 16100 Other Medical Expenses (real activities; no pure catch-all) --
        new(null, 161001, "Over-the-counter medicines.",
            ["Paracetamol and cold remedies"],
            ["Purchase is OTC medicine", "Direction is outflow"],
            ["Pharmacy visits overall follow the pharmacy profile"],
            [], CharacteristicsDirection.Outflow, CharacteristicsAnalyticsTreatment.Expense, 0.5),
        new(null, 161002, "Menstrual care products.",
            ["Period products"],
            ["Purchase is menstrual care", "Direction is outflow"],
            [],
            [], CharacteristicsDirection.Outflow, CharacteristicsAnalyticsTreatment.Expense, 0.5),
        new(null, 161003, "Lactation supplies.",
            ["Breast pump purchase"],
            ["Purchase is lactation supplies", "Direction is outflow"],
            [],
            ["BREAST PUMP"], CharacteristicsDirection.Outflow, CharacteristicsAnalyticsTreatment.Expense, 0.6),
        new(null, 161004, "Medical alert devices and monitoring.",
            ["Personal alarm pendant subscription"],
            ["Purchase is a medical alert device or service", "Direction is outflow"],
            [],
            ["MEDICAL ALERT"], CharacteristicsDirection.Outflow, CharacteristicsAnalyticsTreatment.Expense, 0.6),
        new(null, 161005, "Lead paint removal for health reasons.",
            ["Lead abatement work"],
            ["Work removes a health hazard", "Direction is outflow"],
            [],
            [], CharacteristicsDirection.Outflow, CharacteristicsAnalyticsTreatment.Expense, 0.5),
        new(null, 161006, "Medically required special diets billed as such.",
            ["Clinical nutrition product"],
            ["Purchase is a clinically required diet product", "Direction is outflow"],
            ["Ordinary specialty food belongs to Special Dietary Spending"],
            [], CharacteristicsDirection.Outflow, CharacteristicsAnalyticsTreatment.Expense, 0.5)
    ];
}
