namespace NSFinance.Shared.Taxonomy;

// Full-coverage characteristics: Utilities (140) subcategories, Personal
// Care (190), and Family & Childcare (200) - categories and subcategories.
public static partial class CategoryCharacteristicsCatalog
{
    private static readonly IReadOnlyList<CategoryCharacteristicsDefinition> UtilitiesPersonalFamilyDefinitions =
    [
        // -- 14010 Electricity subs --
        new(null, 140101, "The standard electricity bill.",
            ["Bi-monthly electricity bill"],
            ["Charge is an electricity bill", "Direction is outflow"],
            [],
            [], CharacteristicsDirection.Outflow, CharacteristicsAnalyticsTreatment.Expense, 0.55),
        new(null, 140102, "Prepay electricity plans.",
            ["Prepay plan payment"],
            ["Charge is prepay electricity", "Direction is outflow"],
            [],
            ["PREPAYPOWER", "PINERGY"], CharacteristicsDirection.Outflow, CharacteristicsAnalyticsTreatment.Expense, 0.75),
        new(null, 140103, "Meter top-ups at shops or apps.",
            ["Electricity meter top-up"],
            ["Payment tops up a meter", "Direction is outflow"],
            [],
            [], CharacteristicsDirection.Outflow, CharacteristicsAnalyticsTreatment.Expense, 0.55),
        new(null, 140104, "Electricity arrears repayments.",
            ["Arrears instalment"],
            ["Payment clears electricity arrears", "Direction is outflow"],
            [],
            [], CharacteristicsDirection.Outflow, CharacteristicsAnalyticsTreatment.Expense, 0.5),

        // -- 14020 Gas & Heating subs --
        new(null, 140201, "The piped gas bill.",
            ["Gas bill payment"],
            ["Charge is a gas bill", "Direction is outflow"],
            [],
            [], CharacteristicsDirection.Outflow, CharacteristicsAnalyticsTreatment.Expense, 0.55),
        new(null, 140202, "Home heating oil deliveries.",
            ["Fill of the oil tank"],
            ["Purchase is heating oil", "Direction is outflow"],
            [],
            ["HEATING OIL", "OIL DELIVER"], CharacteristicsDirection.Outflow, CharacteristicsAnalyticsTreatment.Expense, 0.7),
        new(null, 140203, "Propane and bottled gas.",
            ["Gas bottle refill"],
            ["Purchase is bottled gas", "Direction is outflow"],
            ["BBQ gas follows BBQ & Patio Supplies when clearly leisure"],
            [], CharacteristicsDirection.Outflow, CharacteristicsAnalyticsTreatment.Expense, 0.55),
        new(null, 140204, "Solid fuel: coal, briquettes, firewood, pellets.",
            ["Bags of coal and briquettes"],
            ["Purchase is solid fuel", "Direction is outflow"],
            [],
            ["FIREWOOD", "BRIQUETTE"], CharacteristicsDirection.Outflow, CharacteristicsAnalyticsTreatment.Expense, 0.6),
        new(null, 140205, "Boiler servicing.",
            ["Annual boiler service"],
            ["Charge services the boiler", "Direction is outflow"],
            [],
            ["BOILER SERVICE", "BOILER MAINT"], CharacteristicsDirection.Outflow, CharacteristicsAnalyticsTreatment.Expense, 0.7),

        // -- 14030 Water & Waste subs (140303 Bins already defined) --
        new(null, 140301, "Water charges.",
            ["Water bill"],
            ["Charge is a water bill", "Direction is outflow"],
            [],
            [], CharacteristicsDirection.Outflow, CharacteristicsAnalyticsTreatment.Expense, 0.55),
        new(null, 140302, "Sewer and wastewater charges.",
            ["Wastewater charge"],
            ["Charge is sewage or wastewater", "Direction is outflow"],
            [],
            [], CharacteristicsDirection.Outflow, CharacteristicsAnalyticsTreatment.Expense, 0.5),
        new(null, 140304, "Recycling centre and civic amenity fees.",
            ["Recycling centre entry"],
            ["Charge is recycling or civic amenity", "Direction is outflow"],
            [],
            ["RECYCLING CENTRE", "CIVIC AMENITY", "BRING CENTRE"], CharacteristicsDirection.Outflow, CharacteristicsAnalyticsTreatment.Expense, 0.7),
        new(null, 140305, "Septic tank emptying and service.",
            ["Septic tank service"],
            ["Charge services a septic tank", "Direction is outflow"],
            [],
            ["SEPTIC"], CharacteristicsDirection.Outflow, CharacteristicsAnalyticsTreatment.Expense, 0.7),

        // -- 14040 Internet & Communications subs --
        new(null, 140401, "Home broadband bills.",
            ["Monthly broadband bill"],
            ["Charge is home internet", "Direction is outflow"],
            [],
            [], CharacteristicsDirection.Outflow, CharacteristicsAnalyticsTreatment.Expense, 0.55),
        new(null, 140402, "Broadband installation and activation.",
            ["Install and activation fee"],
            ["Charge installs broadband", "Direction is outflow"],
            [],
            [], CharacteristicsDirection.Outflow, CharacteristicsAnalyticsTreatment.Expense, 0.5),
        new(null, 140403, "Landline charges.",
            ["Landline line rental"],
            ["Charge is a landline", "Direction is outflow"],
            [],
            ["LANDLINE"], CharacteristicsDirection.Outflow, CharacteristicsAnalyticsTreatment.Expense, 0.6),
        new(null, 140404, "Mobile phone bills on contract.",
            ["Monthly phone bill"],
            ["Charge is a mobile contract bill", "Direction is outflow"],
            [],
            [], CharacteristicsDirection.Outflow, CharacteristicsAnalyticsTreatment.Expense, 0.55),
        new(null, 140405, "Prepay mobile top-ups.",
            ["Prepay credit top-up"],
            ["Payment is a mobile top-up", "Direction is outflow"],
            [],
            ["MOBILE TOPUP", "MOBILE TOP-UP"], CharacteristicsDirection.Outflow, CharacteristicsAnalyticsTreatment.Expense, 0.65),
        new(null, 140406, "Family and group phone plans.",
            ["Family plan bill"],
            ["Charge is a family phone plan", "Direction is outflow"],
            [],
            [], CharacteristicsDirection.Outflow, CharacteristicsAnalyticsTreatment.Expense, 0.5),
        new(null, 140407, "International calling: cards and add-ons.",
            ["International call bundle"],
            ["Charge is international calling", "Direction is outflow"],
            [],
            [], CharacteristicsDirection.Outflow, CharacteristicsAnalyticsTreatment.Expense, 0.5),

        // -- 14050 TV & Media Utilities subs --
        new(null, 140501, "Cable TV packages.",
            ["Cable TV bill"],
            ["Charge is cable television", "Direction is outflow"],
            [],
            [], CharacteristicsDirection.Outflow, CharacteristicsAnalyticsTreatment.Expense, 0.5),
        new(null, 140502, "Satellite TV packages.",
            ["Satellite subscription"],
            ["Charge is satellite television", "Direction is outflow"],
            [],
            [], CharacteristicsDirection.Outflow, CharacteristicsAnalyticsTreatment.Expense, 0.5),
        new(null, 140503, "The TV licence.",
            ["Annual TV licence"],
            ["Charge is the television licence", "Direction is outflow"],
            [],
            [], CharacteristicsDirection.Outflow, CharacteristicsAnalyticsTreatment.Expense, 0.6),
        new(null, 140504, "Phone-TV-broadband bundles billed together.",
            ["Triple-play bundle bill"],
            ["Charge is a media bundle", "Direction is outflow"],
            [],
            [], CharacteristicsDirection.Outflow, CharacteristicsAnalyticsTreatment.Expense, 0.5),

        // -- 14060 Utility Setup & Service Fees subs --
        new(null, 140601, "Utility deposits.",
            ["New-account deposit"],
            ["Charge is a utility deposit", "Direction is outflow"],
            [],
            [], CharacteristicsDirection.Outflow, CharacteristicsAnalyticsTreatment.Expense, 0.5),
        new(null, 140602, "Reconnection fees.",
            ["Reconnection charge"],
            ["Charge reconnects a utility", "Direction is outflow"],
            [],
            ["RECONNECTION"], CharacteristicsDirection.Outflow, CharacteristicsAnalyticsTreatment.Expense, 0.6),
        new(null, 140603, "Installation fees.",
            ["Meter installation fee"],
            ["Charge installs utility equipment", "Direction is outflow"],
            [],
            [], CharacteristicsDirection.Outflow, CharacteristicsAnalyticsTreatment.Expense, 0.5),
        new(null, 140604, "Late payment fees on utility bills.",
            ["Late fee on a bill"],
            ["Charge is a utility late fee", "Direction is outflow"],
            [],
            [], CharacteristicsDirection.Outflow, CharacteristicsAnalyticsTreatment.Expense, 0.5),
        new(null, 140605, "Service transfer fees when moving.",
            ["Transfer-of-service fee"],
            ["Charge transfers utility service", "Direction is outflow"],
            [],
            [], CharacteristicsDirection.Outflow, CharacteristicsAnalyticsTreatment.Expense, 0.5),

        // -- 14070 Other Utilities (catch-all) --
        new(14070, null, "Utility costs that fit nowhere else; a human choice, never an AI guess.",
            ["Genuinely unclassifiable utility expense"],
            ["Only deterministic rules or the user may assign this catch-all"],
            [],
            [], CharacteristicsDirection.Outflow, CharacteristicsAnalyticsTreatment.Expense, null),
        new(null, 140701, "Miscellaneous utilities, user-assigned.",
            ["One-off with no better node"],
            ["Only deterministic rules or the user may assign this catch-all"],
            [],
            [], CharacteristicsDirection.Outflow, CharacteristicsAnalyticsTreatment.Expense, null),
        new(null, 140702, "Your share of a utility bill someone else holds.",
            ["Paying a housemate your share of the broadband"],
            ["Payment contributes to a shared utility bill", "Direction is outflow"],
            ["Housemates paying you back is a shared expense repayment inflow"],
            [], CharacteristicsDirection.Outflow, CharacteristicsAnalyticsTreatment.Expense, 0.5),

        // -- 190 Personal Care: categories 19020-19050 + all subs --
        new(19020, null, "Everyday hygiene: toiletries and personal upkeep goods.",
            ["Toiletries restock"],
            ["Goods are personal hygiene products", "Direction is outflow"],
            ["Grooming services belong to Grooming & Beauty"],
            [], CharacteristicsDirection.Outflow, CharacteristicsAnalyticsTreatment.Expense, 0.6),
        new(19030, null, "Caring for clothes: cleaning, repair, alteration.",
            ["Dry cleaning drop-off"],
            ["Service cleans or repairs clothing", "Direction is outflow"],
            ["Buying clothes belongs to Clothing"],
            [], CharacteristicsDirection.Outflow, CharacteristicsAnalyticsTreatment.Expense, 0.65),
        new(19040, null, "Moving and minding the body: classes, trainers, wellness.",
            ["Fitness class block"],
            ["Charge is fitness or wellness activity", "Direction is outflow"],
            ["Gym memberships follow the Gym Membership definition"],
            [], CharacteristicsDirection.Outflow, CharacteristicsAnalyticsTreatment.Expense, 0.6),

        // 19010 subs (190101-190107 semantics; category def holds brand signals)
        new(null, 190101, "Haircuts and barbering.",
            ["Barber visit"],
            ["Service is a haircut", "Direction is outflow"],
            [],
            ["BARBER"], CharacteristicsDirection.Outflow, CharacteristicsAnalyticsTreatment.Expense, 0.7),
        new(null, 190102, "Salon services beyond the cut: colour, styling.",
            ["Colour and blow-dry"],
            ["Service is salon hair treatment", "Direction is outflow"],
            [],
            ["HAIR STUDIO"], CharacteristicsDirection.Outflow, CharacteristicsAnalyticsTreatment.Expense, 0.6),
        new(null, 190103, "Skincare products and treatments.",
            ["Skincare order"],
            ["Purchase is skincare", "Direction is outflow"],
            [],
            ["SKINCARE", "THE ORDINARY"], CharacteristicsDirection.Outflow, CharacteristicsAnalyticsTreatment.Expense, 0.6),
        new(null, 190104, "Makeup.",
            ["Makeup haul"],
            ["Purchase is cosmetics", "Direction is outflow"],
            [],
            ["SEPHORA", "INGLOT"], CharacteristicsDirection.Outflow, CharacteristicsAnalyticsTreatment.Expense, 0.65),
        new(null, 190105, "Nails.",
            ["Gel nails appointment"],
            ["Service is nail care", "Direction is outflow"],
            [],
            ["NAIL BAR", "NAILS"], CharacteristicsDirection.Outflow, CharacteristicsAnalyticsTreatment.Expense, 0.65),
        new(null, 190106, "Waxing and threading.",
            ["Waxing appointment"],
            ["Service is hair removal", "Direction is outflow"],
            [],
            ["WAXING"], CharacteristicsDirection.Outflow, CharacteristicsAnalyticsTreatment.Expense, 0.65),
        new(null, 190107, "Spa treatments.",
            ["Spa day treatment"],
            ["Service is a spa treatment", "Direction is outflow"],
            [],
            ["SPA "], CharacteristicsDirection.Outflow, CharacteristicsAnalyticsTreatment.Expense, 0.55),
        new(null, 190108, "Tattoos and piercings.",
            ["New tattoo session"],
            ["Service is tattooing or piercing", "Direction is outflow"],
            [],
            ["TATTOO", "PIERCING"], CharacteristicsDirection.Outflow, CharacteristicsAnalyticsTreatment.Expense, 0.75),

        // 19020 subs
        new(null, 190201, "Oral hygiene products.",
            ["Toothpaste and brushes"],
            ["Purchase is oral hygiene goods", "Direction is outflow"],
            [],
            [], CharacteristicsDirection.Outflow, CharacteristicsAnalyticsTreatment.Expense, 0.5),
        new(null, 190202, "Soap and body wash.",
            ["Body wash restock"],
            ["Purchase is soap or body wash", "Direction is outflow"],
            [],
            [], CharacteristicsDirection.Outflow, CharacteristicsAnalyticsTreatment.Expense, 0.5),
        new(null, 190203, "Hair care products.",
            ["Shampoo and conditioner"],
            ["Purchase is hair care products", "Direction is outflow"],
            [],
            [], CharacteristicsDirection.Outflow, CharacteristicsAnalyticsTreatment.Expense, 0.5),
        new(null, 190204, "Deodorant.",
            ["Deodorant purchase"],
            ["Purchase is deodorant", "Direction is outflow"],
            [],
            [], CharacteristicsDirection.Outflow, CharacteristicsAnalyticsTreatment.Expense, 0.5),
        new(null, 190205, "Feminine hygiene products.",
            ["Feminine hygiene purchase"],
            ["Purchase is feminine hygiene goods", "Direction is outflow"],
            [],
            [], CharacteristicsDirection.Outflow, CharacteristicsAnalyticsTreatment.Expense, 0.5),
        new(null, 190206, "Shaving supplies.",
            ["Razors and shave gel"],
            ["Purchase is shaving supplies", "Direction is outflow"],
            [],
            [], CharacteristicsDirection.Outflow, CharacteristicsAnalyticsTreatment.Expense, 0.5),
        new(null, 190207, "Toiletry refills and travel sizes.",
            ["Travel-size toiletries"],
            ["Purchase is toiletry refills", "Direction is outflow"],
            [],
            [], CharacteristicsDirection.Outflow, CharacteristicsAnalyticsTreatment.Expense, 0.5),

        // 19030 subs
        new(null, 190301, "Dry cleaning.",
            ["Suits dry-cleaned"],
            ["Service is dry cleaning", "Direction is outflow"],
            [],
            ["DRY CLEAN"], CharacteristicsDirection.Outflow, CharacteristicsAnalyticsTreatment.Expense, 0.75),
        new(null, 190302, "Laundry services and launderettes.",
            ["Service wash"],
            ["Service is laundry", "Direction is outflow"],
            [],
            ["LAUNDERETTE", "LAUNDRY"], CharacteristicsDirection.Outflow, CharacteristicsAnalyticsTreatment.Expense, 0.7),
        new(null, 190303, "Tailoring and alterations.",
            ["Trousers taken up"],
            ["Service is alteration or tailoring", "Direction is outflow"],
            [],
            ["ALTERATIONS", "TAILOR"], CharacteristicsDirection.Outflow, CharacteristicsAnalyticsTreatment.Expense, 0.7),
        new(null, 190304, "Shoe repair.",
            ["Heels re-soled"],
            ["Service is shoe repair", "Direction is outflow"],
            [],
            ["SHOE REPAIR", "COBBLER"], CharacteristicsDirection.Outflow, CharacteristicsAnalyticsTreatment.Expense, 0.75),

        // 19040 subs (190401 Gym already defined)
        new(null, 190402, "Yoga and pilates.",
            ["Yoga class pass"],
            ["Charge is yoga or pilates", "Direction is outflow"],
            [],
            ["YOGA", "PILATES"], CharacteristicsDirection.Outflow, CharacteristicsAnalyticsTreatment.Expense, 0.7),
        new(null, 190403, "Fitness classes outside the gym contract.",
            ["Spin class drop-in"],
            ["Charge is a fitness class", "Direction is outflow"],
            [],
            [], CharacteristicsDirection.Outflow, CharacteristicsAnalyticsTreatment.Expense, 0.55),
        new(null, 190404, "Personal training.",
            ["PT session block"],
            ["Charge is personal training", "Direction is outflow"],
            [],
            ["PERSONAL TRAIN"], CharacteristicsDirection.Outflow, CharacteristicsAnalyticsTreatment.Expense, 0.65),
        new(null, 190405, "Massage.",
            ["Sports massage"],
            ["Service is massage", "Direction is outflow"],
            ["Clinical physio belongs to Healthcare"],
            ["MASSAGE"], CharacteristicsDirection.Outflow, CharacteristicsAnalyticsTreatment.Expense, 0.7),
        new(null, 190406, "Supplements and vitamins bought as wellness.",
            ["Daily vitamins"],
            ["Purchase is supplements", "Direction is outflow"],
            ["Sports nutrition belongs to Special Dietary Spending"],
            [], CharacteristicsDirection.Outflow, CharacteristicsAnalyticsTreatment.Expense, 0.5),
        new(null, 190407, "Wellness apps.",
            ["Meditation app subscription"],
            ["Charge is a wellness app", "Direction is outflow"],
            ["General software belongs to Software & Digital Tools"],
            ["HEADSPACE", "CALM.COM"], CharacteristicsDirection.Outflow, CharacteristicsAnalyticsTreatment.Expense, 0.65),

        // 19050 Other Personal Care (real activities + catch-all)
        new(19050, null, "Personal care that fits nowhere else; a human choice, never an AI guess.",
            ["Genuinely unclassifiable personal care expense"],
            ["Only deterministic rules or the user may assign this catch-all"],
            [],
            [], CharacteristicsDirection.Outflow, CharacteristicsAnalyticsTreatment.Expense, null),
        new(null, 190501, "Fragrances.",
            ["Perfume purchase"],
            ["Purchase is fragrance", "Direction is outflow"],
            [],
            ["PERFUME", "FRAGRANCE"], CharacteristicsDirection.Outflow, CharacteristicsAnalyticsTreatment.Expense, 0.65),
        new(null, 190502, "Tanning.",
            ["Spray tan"],
            ["Service is tanning", "Direction is outflow"],
            [],
            ["TANNING"], CharacteristicsDirection.Outflow, CharacteristicsAnalyticsTreatment.Expense, 0.7),
        new(null, 190503, "Cosmetic procedures.",
            ["Aesthetic clinic treatment"],
            ["Service is a cosmetic procedure", "Direction is outflow"],
            ["Medical dermatology belongs to Healthcare"],
            ["AESTHETIC"], CharacteristicsDirection.Outflow, CharacteristicsAnalyticsTreatment.Expense, 0.6),
        new(null, 190504, "Other self-care spending, user-assigned.",
            ["Self-care one-off with no better node"],
            ["Only deterministic rules or the user may assign this catch-all"],
            [],
            [], CharacteristicsDirection.Outflow, CharacteristicsAnalyticsTreatment.Expense, null),

        // -- 200 Family & Childcare: categories + subs --
        new(20010, null, "Paying for childcare.",
            ["Monthly creche bill"],
            ["Charge is childcare", "Direction is outflow"],
            [],
            ["CRECHE", "MONTESSORI"], CharacteristicsDirection.Outflow, CharacteristicsAnalyticsTreatment.Expense, 0.7),
        new(20020, null, "The things children need: nappies to school gear.",
            ["School supplies run"],
            ["Purchase is child essentials", "Direction is outflow"],
            [],
            [], CharacteristicsDirection.Outflow, CharacteristicsAnalyticsTreatment.Expense, 0.55),
        new(20030, null, "Children's activities: sport, music, clubs, parties.",
            ["Kids' sports term fee"],
            ["Charge is a child's activity", "Direction is outflow"],
            [],
            [], CharacteristicsDirection.Outflow, CharacteristicsAnalyticsTreatment.Expense, 0.55),
        new(20040, null, "Caring for adult dependents.",
            ["Home-care support invoice"],
            ["Charge is dependent care", "Direction is outflow"],
            [],
            ["HOMECARE", "HOME CARE"], CharacteristicsDirection.Outflow, CharacteristicsAnalyticsTreatment.Expense, 0.6),
        new(20050, null, "Family occasions and support.",
            ["Family celebration costs"],
            ["Charge is a family event or support", "Direction is outflow"],
            [],
            [], CharacteristicsDirection.Outflow, CharacteristicsAnalyticsTreatment.Expense, 0.5),

        // 20010 subs
        new(null, 200101, "Daycare and creche.",
            ["Creche fees"],
            ["Charge is daycare", "Direction is outflow"],
            [],
            [], CharacteristicsDirection.Outflow, CharacteristicsAnalyticsTreatment.Expense, 0.55),
        new(null, 200102, "Nannies and babysitters.",
            ["Saturday babysitter"],
            ["Charge is a nanny or babysitter", "Direction is outflow"],
            [],
            ["BABYSIT"], CharacteristicsDirection.Outflow, CharacteristicsAnalyticsTreatment.Expense, 0.6),
        new(null, 200103, "After-school care.",
            ["After-school club fee"],
            ["Charge is after-school care", "Direction is outflow"],
            [],
            ["AFTERSCHOOL", "AFTER SCHOOL"], CharacteristicsDirection.Outflow, CharacteristicsAnalyticsTreatment.Expense, 0.65),
        new(null, 200104, "Preschool and playschool.",
            ["Playschool term fee"],
            ["Charge is preschool", "Direction is outflow"],
            [],
            ["PRESCHOOL", "PLAYSCHOOL", "NAIONRA"], CharacteristicsDirection.Outflow, CharacteristicsAnalyticsTreatment.Expense, 0.65),
        new(null, 200105, "Childcare-shaped summer camps.",
            ["Summer camp week"],
            ["Charge is a childcare summer camp", "Direction is outflow"],
            [],
            ["SUMMER CAMP"], CharacteristicsDirection.Outflow, CharacteristicsAnalyticsTreatment.Expense, 0.65),
        new(null, 200106, "Childminders.",
            ["Weekly childminder payment"],
            ["Charge is a childminder", "Direction is outflow"],
            [],
            ["CHILDMIND"], CharacteristicsDirection.Outflow, CharacteristicsAnalyticsTreatment.Expense, 0.65),

        // 20020 subs
        new(null, 200201, "Nappies and wipes.",
            ["Nappy stock-up"],
            ["Purchase is nappies or wipes", "Direction is outflow"],
            [],
            [], CharacteristicsDirection.Outflow, CharacteristicsAnalyticsTreatment.Expense, 0.5),
        new(null, 200202, "Formula bought as such.",
            ["Formula tins"],
            ["Purchase is infant formula", "Direction is outflow"],
            ["Grocery-run formula follows the basket profile"],
            [], CharacteristicsDirection.Outflow, CharacteristicsAnalyticsTreatment.Expense, 0.5),
        new(null, 200203, "Baby gear: buggies, car seats, monitors.",
            ["Buggy purchase"],
            ["Purchase is baby equipment", "Direction is outflow"],
            [],
            ["MOTHERCARE", "SMYTHS BABY"], CharacteristicsDirection.Outflow, CharacteristicsAnalyticsTreatment.Expense, 0.6),
        new(null, 200204, "School lunches paid to the school or provider.",
            ["School lunch account top-up"],
            ["Payment is school lunches", "Direction is outflow"],
            [],
            ["SCHOOL LUNCH"], CharacteristicsDirection.Outflow, CharacteristicsAnalyticsTreatment.Expense, 0.65),
        new(null, 200205, "School supplies: books, stationery, bags.",
            ["Back-to-school haul"],
            ["Purchase is school supplies", "Direction is outflow"],
            [],
            [], CharacteristicsDirection.Outflow, CharacteristicsAnalyticsTreatment.Expense, 0.5),
        new(null, 200206, "Children's clothing.",
            ["Kids' clothes shop"],
            ["Purchase is children's clothing", "Direction is outflow"],
            ["Adult clothing belongs to Clothing"],
            [], CharacteristicsDirection.Outflow, CharacteristicsAnalyticsTreatment.Expense, 0.5),
        new(null, 200207, "Baby furniture: cots, changing tables.",
            ["Cot purchase"],
            ["Purchase is baby furniture", "Direction is outflow"],
            [],
            [], CharacteristicsDirection.Outflow, CharacteristicsAnalyticsTreatment.Expense, 0.5),

        // 20030 subs
        new(null, 200301, "Children's sports fees.",
            ["GAA membership for the kids"],
            ["Charge is a child's sport", "Direction is outflow"],
            [],
            [], CharacteristicsDirection.Outflow, CharacteristicsAnalyticsTreatment.Expense, 0.5),
        new(null, 200302, "Children's music lessons.",
            ["Piano lessons term"],
            ["Charge is a child's music tuition", "Direction is outflow"],
            [],
            [], CharacteristicsDirection.Outflow, CharacteristicsAnalyticsTreatment.Expense, 0.5),
        new(null, 200303, "Dance lessons.",
            ["Dance class term"],
            ["Charge is dance tuition", "Direction is outflow"],
            [],
            ["DANCE ACADEMY", "SCHOOL OF DANCE"], CharacteristicsDirection.Outflow, CharacteristicsAnalyticsTreatment.Expense, 0.65),
        new(null, 200304, "Tutoring and grinds.",
            ["Weekly grinds"],
            ["Charge is tutoring", "Direction is outflow"],
            [],
            ["GRINDS", "TUTOR"], CharacteristicsDirection.Outflow, CharacteristicsAnalyticsTreatment.Expense, 0.65),
        new(null, 200305, "Clubs and scouts.",
            ["Scouts registration"],
            ["Charge is a youth club", "Direction is outflow"],
            [],
            ["SCOUTS", "FORÓIGE", "FOROIGE"], CharacteristicsDirection.Outflow, CharacteristicsAnalyticsTreatment.Expense, 0.65),
        new(null, 200306, "Kids' entertainment outings.",
            ["Play centre visit"],
            ["Charge entertains children", "Direction is outflow"],
            [],
            ["PLAY CENTRE", "PLAYZONE"], CharacteristicsDirection.Outflow, CharacteristicsAnalyticsTreatment.Expense, 0.6),
        new(null, 200307, "Children's birthday parties you host.",
            ["Party venue booking"],
            ["Charge hosts a child's party", "Direction is outflow"],
            ["Gifts for other children belong to Children's Gifts"],
            [], CharacteristicsDirection.Outflow, CharacteristicsAnalyticsTreatment.Expense, 0.5),

        // 20040 subs (200407 already defined semantics here)
        new(null, 200401, "Elder care services.",
            ["Care service invoice"],
            ["Charge is elder care", "Direction is outflow"],
            [],
            [], CharacteristicsDirection.Outflow, CharacteristicsAnalyticsTreatment.Expense, 0.5),
        new(null, 200402, "Assisted living contributions.",
            ["Assisted living monthly charge"],
            ["Charge is assisted living", "Direction is outflow"],
            [],
            ["ASSISTED LIVING"], CharacteristicsDirection.Outflow, CharacteristicsAnalyticsTreatment.Expense, 0.6),
        new(null, 200403, "Respite care.",
            ["Respite week payment"],
            ["Charge is respite care", "Direction is outflow"],
            [],
            ["RESPITE"], CharacteristicsDirection.Outflow, CharacteristicsAnalyticsTreatment.Expense, 0.65),
        new(null, 200404, "In-home support services.",
            ["Home help hours"],
            ["Charge is in-home support", "Direction is outflow"],
            [],
            [], CharacteristicsDirection.Outflow, CharacteristicsAnalyticsTreatment.Expense, 0.5),
        new(null, 200405, "Supporting a caregiver.",
            ["Caregiver contribution"],
            ["Payment supports a caregiver", "Direction is outflow"],
            [],
            [], CharacteristicsDirection.Outflow, CharacteristicsAnalyticsTreatment.Expense, 0.5),
        new(null, 200406, "Adult day care.",
            ["Day centre fees"],
            ["Charge is adult day care", "Direction is outflow"],
            [],
            ["DAY CENTRE"], CharacteristicsDirection.Outflow, CharacteristicsAnalyticsTreatment.Expense, 0.6),
        new(null, 200407, "Maintenance and child support you pay.",
            ["Monthly maintenance payment"],
            ["Payment is family maintenance or child support", "Direction is outflow"],
            ["Money received is Maintenance & Child Support Received"],
            ["MAINTENANCE"], CharacteristicsDirection.Outflow, CharacteristicsAnalyticsTreatment.Expense, 0.55),

        // 20050 subs
        new(null, 200501, "Family celebrations you fund.",
            ["Communion party costs"],
            ["Charge funds a family celebration", "Direction is outflow"],
            [],
            [], CharacteristicsDirection.Outflow, CharacteristicsAnalyticsTreatment.Expense, 0.5),
        new(null, 200502, "School events: trips, fundraisers, tickets.",
            ["School trip payment"],
            ["Charge is a school event", "Direction is outflow"],
            [],
            ["SCHOOL TRIP"], CharacteristicsDirection.Outflow, CharacteristicsAnalyticsTreatment.Expense, 0.6),
        new(null, 200503, "Family travel costs recorded as family support.",
            ["Bringing the family over for the occasion"],
            ["Travel exists for a family occasion", "Direction is outflow"],
            ["Ordinary holidays belong to Travel"],
            [], CharacteristicsDirection.Outflow, CharacteristicsAnalyticsTreatment.Expense, 0.5),
        new(null, 200504, "Gifts for the children.",
            ["Toys for the kids"],
            ["Purchase is a child's gift", "Direction is outflow"],
            [],
            ["SMYTHS"], CharacteristicsDirection.Outflow, CharacteristicsAnalyticsTreatment.Expense, 0.5),
        new(null, 200505, "Child maintenance recorded at family level.",
            ["Support payment for a child"],
            ["Payment is child support", "Direction is outflow"],
            ["Formal maintenance follows Maintenance & Child Support Paid"],
            [], CharacteristicsDirection.Outflow, CharacteristicsAnalyticsTreatment.Expense, 0.5),
        new(null, 200506, "Adoption and fostering costs.",
            ["Adoption process fee"],
            ["Charge is adoption or fostering", "Direction is outflow"],
            [],
            ["ADOPTION"], CharacteristicsDirection.Outflow, CharacteristicsAnalyticsTreatment.Expense, 0.6),
        new(null, 200507, "Family legal support costs.",
            ["Family law consultation"],
            ["Charge is family legal work", "Direction is outflow"],
            ["General legal fees belong to Legal Services"],
            [], CharacteristicsDirection.Outflow, CharacteristicsAnalyticsTreatment.Expense, 0.5)
    ];
}
