namespace NSFinance.Api.Modules.ExpenseTracker.DTOs;

public sealed record ExpensePlanLineItemDto(
    Guid Id,
    Guid PlanId,
    int TaxonomyDomainId,
    string DomainName,
    int TaxonomyCategoryId,
    string CategoryName,
    int? TaxonomySubcategoryId,
    string? SubcategoryName,
    string DisplayNameSnapshot,
    string HierarchyPathSnapshot,
    decimal ExpectedAmount,
    string? Notes,
    int SortOrder,
    DateTime CreatedAtUtc,
    DateTime UpdatedAtUtc);

public sealed record ExpensePlanComparisonLineItemDto(
    Guid PlanLineItemId,
    int TaxonomyDomainId,
    string DomainName,
    int TaxonomyCategoryId,
    string CategoryName,
    int? TaxonomySubcategoryId,
    string? SubcategoryName,
    string DisplayName,
    decimal ExpectedAmount,
    decimal ActualAmount,
    decimal VarianceAmount,
    decimal VariancePercent,
    decimal RemainingPlannedAmount,
    decimal PercentOfPlanUsed,
    int MatchedTransactionCount);

public sealed record ExpensePlanUnexpectedSpendDto(
    int? TaxonomyDomainId,
    string DomainName,
    int? TaxonomyCategoryId,
    string CategoryName,
    int? TaxonomySubcategoryId,
    string? SubcategoryName,
    decimal ActualAmount,
    int MatchingTransactionCount,
    IReadOnlyList<Guid> MatchingTransactionIds);

public sealed record ExpensePlanComparisonDto(
    Guid PlanId,
    decimal PlannedSpendTotal,
    decimal ActualSpendTotal,
    decimal VarianceAmount,
    decimal VariancePercent,
    decimal RemainingPlannedAmount,
    decimal PercentOfPlanUsed,
    int MatchedTransactionCount,
    int UnexpectedTransactionCount,
    decimal ProgressToDatePercent,
    string PeriodState,
    bool ShouldAutoComplete,
    DateTime CalculatedAtUtc,
    IReadOnlyList<ExpensePlanComparisonLineItemDto> PlannedLineItems,
    IReadOnlyList<ExpensePlanUnexpectedSpendDto> UnexpectedCategories);

public sealed record ExpensePlanDto(
    Guid Id,
    Guid CreatorUserId,
    string CreatorDisplayNameSnapshot,
    string CreatorTagSnapshot,
    string Title,
    string? Description,
    string? Notes,
    string Status,
    string PlanType,
    string PlanOriginType,
    int PlanVersion,
    DateTime StartDateUtc,
    DateTime EndDateUtc,
    string CurrencyCode,
    decimal ExpectedIncomeTotal,
    decimal ExpectedSpendTotal,
    decimal ExpectedRemainingTotal,
    IReadOnlyList<string> Tags,
    string? StatusReason,
    DateTime CreatedAtUtc,
    DateTime UpdatedAtUtc,
    DateTime? ActivatedAtUtc,
    DateTime? CompletedAtUtc,
    DateTime? LockedAtUtc,
    DateTime? ArchivedAtUtc,
    DateTime? CancelledAtUtc,
    DateTime? LastCalculatedAtUtc,
    Guid? SourcePlanId,
    Guid? ImportedFromPublicPlanId,
    bool IsTemplate,
    bool IsRecurring,
    ExpensePlanRecurrenceDto? Recurrence,
    bool IsShared,
    string? SharingMode,
    string? SharedIdentity,
    ExpensePlanComparisonDto Comparison,
    IReadOnlyList<ExpensePlanLineItemDto> LineItems);
